// This file is auto-generated by refactor.js

import { renderAuthPage } from '../features/auth/render.js';
import { renderAuthenticatedApp } from './router.js';
import { renderClientApp } from '../apps/client/layout.js';

export function render() {
    const app = document.getElementById('app');
    let newHTML = '';
    
    if (state.showAuthPage) {
        newHTML = renderAuthPage();
    } else if (!state.isAuthenticated) {
        newHTML = renderClientApp();
    } else {
        newHTML = renderAuthenticatedApp();
    }

    // Создаём временный контейнер с тем же тегом и id
    const tmp = document.createElement('div');
    tmp.id = 'app';
    tmp.innerHTML = newHTML;

    // morphdom обновляет только изменившиеся DOM-узлы
    if (typeof morphdom === 'function') {
        morphdom(app, tmp, {
            onBeforeElUpdated: function(fromEl, toEl) {
                // Не трогать элемент, у которого сейчас фокус (input)
                if (fromEl === document.activeElement && fromEl.tagName === 'INPUT') {
                    return false;
                }
                return true;
            }
        });
    } else {
        // Fallback если morphdom не загрузился
        app.innerHTML = newHTML;
    }

    attachEvents();
}

window.render = render;

export function attachEvents() { }

window.attachEvents = attachEvents;

