// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { handleLogout } from '../../features/auth/actions.js';
import { renderThemeSwitcher, renderMasterMobileNav, renderToast } from '../../components/ui.js';
import { state, masters, salons, services, timeSlots, salonApplications, users, categories } from '../../state.js';
import { formatPrice, getSalonPrice, showToast, getSalonPriceHistory, getDurationText } from '../../utils.js';

export function renderMasterApp() {
    return `
${renderMasterHeader()}
<div class="flex min-h-screen">
    ${renderMasterSidebar()}
    <div class="flex-1 p-4 sm:p-6 bg-system-main pb-24 md:pb-6">
        ${renderMasterContent()}
    </div>
</div>
${renderMasterMobileNav()}
${state.toast ? renderToast() : ''}
    `;
}

window.renderMasterApp = renderMasterApp;

export function renderMasterHeader() {
    const master = masters.find(m => m.id === state.currentUser.masterId);
    const masterName = master ? master.name : (state.currentUser.name || 'Мастер');
    return `
    <div class="px-2 sm:px-4 pt-1 sm:pt-2 sticky top-1 sm:top-2 z-[100] transition-all">
        <header class="island-header max-w-7xl mx-auto px-3 sm:px-4">
            <div class="flex items-center justify-between h-11 sm:h-12">
                <div class="flex items-center gap-2">
                    <div class="w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-primary-500 flex items-center justify-center shadow-md">
                        <span class="text-white"><svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line x1="20" y1="4" x2="8.12" y2="15.88"/><line x1="14.47" y1="14.48" x2="14.48" y2="14.48"/><line x1="20" y1="20" x2="8.12" y2="8.12"/></svg></span>
                    </div>
                    <div class="flex flex-col">
                        <span class="leading-none text-base sm:text-lg font-bold text-system-text">SuluuMaster</span>
                        <span class="leading-none text-[10px] sm:text-xs text-system-muted mt-0.5">${masterName}</span>
                    </div>
                </div>
                <div class="flex items-center gap-3">
                    ${renderThemeSwitcher()}
                    <button onclick="handleLogout()" class="text-sm px-3 py-1.5 rounded-lg bg-red-50 text-red-500 hover:bg-red-100 hover:text-red-700 font-medium transition-colors hidden sm:block">Выйти</button>
                    <button onclick="handleLogout()" class="p-1.5 rounded-lg bg-red-50 text-red-500 hover:bg-red-100 sm:hidden">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline stroke-linecap="round" stroke-linejoin="round" points="16 17 21 12 16 7"/><line stroke-linecap="round" stroke-linejoin="round" x1="21" x2="9" y1="12" y2="12"/></svg>
                    </button>
                </div>
            </div>
        </header>
    </div>`;
}

window.renderMasterHeader = renderMasterHeader;

export function renderMasterSidebar() {
    const tabs = [
        { id: 'schedule', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg>', label: 'Расписание' },
        { id: 'bookings', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 7v5l3 3"/></svg>', label: 'Записи' },
        { id: 'my_salons', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 6h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 10h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 14h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 18h4"/></svg>', label: 'Мои салоны' },
        { id: 'services', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7h-3a2 2 0 0 1-2-2V2"/><path stroke-linecap="round" stroke-linejoin="round" d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2 2Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 15h6"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 18h6"/></svg>', label: 'Мои услуги' },
        { id: 'profile', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 2v2"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 20v2"/><path stroke-linecap="round" stroke-linejoin="round" d="m4.93 4.93 1.41 1.41"/><path stroke-linecap="round" stroke-linejoin="round" d="m17.66 17.66 1.41 1.41"/><path stroke-linecap="round" stroke-linejoin="round" d="M2 12h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M20 12h2"/><path stroke-linecap="round" stroke-linejoin="round" d="m6.34 17.66-1.41 1.41"/><path stroke-linecap="round" stroke-linejoin="round" d="m19.07 4.93-1.41 1.41"/></svg>', label: 'Профиль' },
    ];
    return `
    <aside class="w-64 bg-system-surface border-r border-system-border min-h-screen p-4 hidden md:block">
<div class="space-y-1">
    ${tabs.map(tab => `
        <a href="#" onclick="state.masterTab='${tab.id}';render()" class="sidebar-link flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm ${state.masterTab === tab.id ? 'active' : 'text-system-muted'}">
            <span>${tab.icon}</span> ${tab.label}
        </a>
    `).join('')}
</div>
    </aside>`;
}

window.renderMasterSidebar = renderMasterSidebar;

export function renderMasterContent() {
    const master = masters.find(m => m.id === state.currentUser.masterId);
    if (!master) return '<div class="text-center py-20 text-system-muted opacity-70">Мастер не найден</div>';

    const masterBookings = getUserBookings();
    const masterServices = services.filter(s => master.services.includes(s.id));
    const projectedRevenue = masterBookings.filter(b => b.status === 'confirmed').reduce((sum, b) => {
        const svc = services.find(s => s.id === b.serviceId);
        return sum + (svc ? svc.price : 0);
    }, 0);
    const actualRevenue = masterBookings.filter(b => b.status === 'completed').reduce((sum, b) => {
        const svc = services.find(s => s.id === b.serviceId);
        return sum + (svc ? svc.price : 0);
    }, 0);

    const tab = state.masterTab;

    if (tab === 'schedule') {
        const now = new Date();
        const today = String(now.getDate()).padStart(2, '0') + '.' + String(now.getMonth() + 1).padStart(2, '0') + '.' + now.getFullYear();
        
        const todayBookings = masterBookings.filter(b => b.date === today && b.status !== 'cancelled').sort((a, b) => a.time.localeCompare(b.time));
        const statusColors = { pending: 'bg-yellow-100 text-yellow-700', confirmed: 'bg-green-100 text-green-700', completed: 'bg-blue-100 text-blue-700', cancelled: 'bg-red-100 text-red-700' };
        const statusLabels = { pending: 'Ожидает', confirmed: 'Подтверждена', completed: 'Завершена', cancelled: 'Отменена' };

        return `
<div class="animate-fade-in">
    <h1 class="text-2xl font-bold text-system-text mb-6">Операционный дашборд — ${master.name}</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <div class="stat-card"><div class="text-2xl font-bold text-system-text">${masterBookings.length}</div><div class="text-xs text-system-muted">Всего записей</div></div>
        <div class="stat-card"><div class="text-2xl font-bold text-yellow-600">${masterBookings.filter(b => b.status === 'pending').length}</div><div class="text-xs text-system-muted">Ожидают</div></div>
        <div class="stat-card"><div class="text-2xl font-bold text-green-600">${formatPrice(projectedRevenue)}</div><div class="text-xs text-system-muted">Прогнозируемый доход</div></div>
        <div class="stat-card"><div class="text-2xl font-bold text-blue-600">${formatPrice(actualRevenue)}</div><div class="text-xs text-system-muted">Фактический заработок</div></div>
    </div>
    ${masterBookings.filter(b => b.status === 'pending').length > 0 ? `
        <div class="bg-system-surface rounded-2xl border border-2 border-yellow-400 overflow-hidden mb-6">
            <h3 class="font-semibold text-system-text p-4 border-b border-system-border bg-transparent text-yellow-500"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 22h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M5 2h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22"/><path stroke-linecap="round" stroke-linejoin="round" d="M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2"/></svg> Записи для подтверждения</h3>
            <div class="divide-y divide-system-border">
                ${masterBookings.filter(b => b.status === 'pending').map(b => {
            const svc = services.find(s => s.id === b.serviceId);
            return `<div class="p-4 flex items-center justify-between">
                        <div>
                            <p class="font-medium text-system-text">${svc ? svc.name : 'Услуга'}</p>
                            <p class="text-sm text-system-muted">${b.clientName} · ${b.clientPhone}</p>
                            <p class="text-xs text-system-muted opacity-70">${b.date} в ${b.time} · ${svc ? formatPrice(svc.price) : ''}</p>
                        </div>
                    </div>`;
        }).join('')}
            </div>
        </div>
    ` : ''}
    <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden mb-6">
        <h3 class="font-semibold text-system-text p-4 border-b border-system-border bg-system-main"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg> Записи на сегодня (${today})</h3>
        ${todayBookings.length > 0 ? `
            <div class="divide-y divide-system-border">
                ${todayBookings.map(b => {
                    const svc = services.find(s => s.id === b.serviceId);
                    return `<div class="p-4 flex items-center justify-between hover:bg-system-main transition-colors">
                                <div>
                                    <p class="font-medium text-system-text">${svc ? svc.name : 'Услуга'}</p>
                                    <p class="text-sm text-system-muted">${b.clientName} · ${b.clientPhone}</p>
                                    <p class="text-xs font-bold text-system-text mt-1">${b.time} · ${svc ? formatPrice(svc.price) : ''}</p>
                                </div>
                                <div class="text-right flex flex-col items-end gap-2">
                                    <span class="badge ${statusColors[b.status]}">${statusLabels[b.status]}</span>
                                </div>
                            </div>`;
                }).join('')}
            </div>
        ` : '<div class="p-8 text-center text-system-muted opacity-70">На сегодня записей нет</div>'}
    </div>
</div>`;
    } else if (tab === 'my_salons') {
        return renderMasterSalonsTab(master);
    } else if (tab === 'bookings') {
        state.masterBookingFilter = state.masterBookingFilter || 'upcoming';
        const statusColors = { pending: 'bg-yellow-100 text-yellow-700', confirmed: 'bg-green-100 text-green-700', completed: 'bg-blue-100 text-blue-700', cancelled: 'bg-red-100 text-red-700' };
        const statusLabels = { pending: 'Ожидает', confirmed: 'Подтверждена', completed: 'Завершена', cancelled: 'Отменена' };
        
        const filteredBookings = masterBookings.filter(b => {
            if (state.masterBookingFilter === 'upcoming') return b.status === 'pending' || b.status === 'confirmed';
            return b.status === 'completed' || b.status === 'cancelled';
        }).sort((a, b) => {
            if (state.masterBookingFilter === 'history') return -1;
            return 1;
        });

        return `
<div class="animate-fade-in">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <h1 class="text-2xl font-bold text-system-text">Записи</h1>
        <div class="flex bg-system-main rounded-xl p-1">
            <button onclick="state.masterBookingFilter='upcoming'; render()" class="flex-1 sm:flex-none px-4 py-2 rounded-lg text-sm font-bold transition-colors ${state.masterBookingFilter === 'upcoming' ? 'bg-system-surface shadow-sm text-system-text' : 'text-system-muted hover:text-system-text'}">Предстоящие</button>
            <button onclick="state.masterBookingFilter='history'; render()" class="flex-1 sm:flex-none px-4 py-2 rounded-lg text-sm font-bold transition-colors ${state.masterBookingFilter === 'history' ? 'bg-system-surface shadow-sm text-system-text' : 'text-system-muted hover:text-system-text'}">История</button>
        </div>
    </div>
    ${filteredBookings.length > 0 ? `
        <div class="space-y-3">
            ${filteredBookings.map(b => {
            const svc = services.find(s => s.id === b.serviceId);
            return `<div class="bg-system-surface rounded-2xl border border-system-border p-5">
                    <div class="flex items-center justify-between mb-2">
                        <h3 class="font-bold text-system-text">${svc ? svc.name : 'Услуга'}</h3>
                        <span class="badge ${statusColors[b.status]}">${statusLabels[b.status]}</span>
                    </div>
                    <div class="flex flex-wrap gap-4 text-sm text-system-muted">
                        <span>👤 ${b.clientName}</span><span>📞 ${b.clientPhone}</span>
                        <span><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg> ${b.date}</span><span>🕐 ${b.time}</span>
                        <span><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path stroke-linecap="round" stroke-linejoin="round" d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 18V6"/></svg> ${svc ? formatPrice(svc.price) : ''}</span>
                    </div>
                </div>`;
        }).join('')}
        </div>
    ` : `<div class="text-center py-12 text-system-muted opacity-70 bg-system-surface rounded-2xl border border-system-border">${state.masterBookingFilter === 'upcoming' ? 'Нет предстоящих записей' : 'История пуста'}</div>`}
</div>`;
    }

        if (tab === 'services') {
        const grouped = services.reduce((acc, svc) => {
            const catId = svc.category;
            if (!acc[catId]) { acc[catId] = { cat: categories.find(c => c.id === catId), services: [] }; }
            acc[catId].services.push(svc);
            return acc;
        }, {});

        return `
<div class="animate-fade-in max-w-2xl mx-auto">
    <h1 class="text-2xl font-bold text-system-text mb-6">Услуги и стоимость</h1>
    <div class="space-y-4">
        ${Object.values(grouped).map(g => {
            const isExpanded = state.expandedMasterCat !== undefined ? state.expandedMasterCat[g.cat?.id || 0] : false;
            const selectedCount = g.services.filter(s => (master.services || []).includes(s.id)).length;
            return `
            <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden">
                <div class="p-4 flex items-center justify-between cursor-pointer hover:bg-system-main transition-colors"
                     onclick="if(!state.expandedMasterCat) state.expandedMasterCat={}; state.expandedMasterCat[${g.cat?.id || 0}] = !${isExpanded}; render()">
                    <div class="flex items-center gap-3">
                        <span class="text-xl">${g.cat ? g.cat.icon : '✨'}</span>
                        <h3 class="font-bold text-system-text">${g.cat ? g.cat.name : 'Другое'}</h3>
                        <span class="text-xs px-2 py-0.5 rounded-full bg-system-main text-system-muted">${selectedCount}/${g.services.length}</span>
                    </div>
                    <span class="text-system-muted transition-transform ${isExpanded ? 'rotate-180' : ''}">▾</span>
                </div>
                ${isExpanded ? `
                <div class="border-t border-system-border divide-y divide-system-border">
                    ${g.services.map(svc => {
                        const isChecked = (master.services || []).includes(svc.id);
                        const customVal = (master.customPrices && master.customPrices[svc.id] !== undefined) ? master.customPrices[svc.id] : svc.price;
                        return `
                        <div class="p-4 flex flex-col sm:flex-row gap-3 sm:items-center justify-between hover:bg-system-main/50 transition-colors ${!isChecked ? 'opacity-60' : ''}">
                            <div class="flex items-start sm:items-center gap-3">
                                <input type="checkbox" ${isChecked ? 'checked' : ''} class="mt-1 sm:mt-0 w-5 h-5 rounded border-system-border text-primary-500 focus:ring-primary-400 cursor-pointer"
                                       onchange="toggleMasterSelfService(${master.id}, ${svc.id})">
                                <div>
                                    <h4 class="text-sm font-medium text-system-text">${svc.name}</h4>
                                    <p class="text-xs text-system-muted">${Math.floor(svc.duration / 60) > 0 ? Math.floor(svc.duration / 60) + ' ч ' : ''}${svc.duration % 60 > 0 ? (svc.duration % 60) + ' мин' : ''} · Базовая цена: ${svc.price} сом</p>
                                </div>
                            </div>
                            <div class="flex items-center gap-2 self-end sm:self-auto">
                                <label class="text-[10px] text-system-muted font-medium w-16 text-right leading-tight">Ваша цена<br>(сом)</label>
                                <input type="number" min="0" ${!isChecked ? 'disabled' : ''} class="w-20 px-3 py-1.5 rounded-xl border border-system-border text-sm font-bold focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-center"
                                       value="${customVal}" onchange="updateMasterSelfPrice(${master.id}, ${svc.id}, this.value)">
                            </div>
                        </div>
                        `;
                    }).join('')}
                </div>
                ` : ''}
            </div>
            `;
        }).join('')}
    </div>
</div>`;
    }

    if (tab === 'profile') {
        let tariffText = 'Работа за процент (40% по умолчанию)';
        if (master.tariff_type === 'rent') {
             tariffText = `Аренда места: ${master.tariff_details ? master.tariff_details.rent_amount : 0} сом / ${master.tariff_details && master.tariff_details.rent_period === 'monthly' ? 'месяц' : master.tariff_details && master.tariff_details.rent_period === 'weekly' ? 'неделю' : 'день'}`;
        } else if (master.tariff_type === 'percentage') {
             tariffText = `Процент от услуг: ${master.tariff_details && master.tariff_details.percentage_value !== undefined ? master.tariff_details.percentage_value : (master.commissionRate || 40)}%`;
        }

        return `
<div class="animate-fade-in max-w-lg">
    <h1 class="text-2xl font-bold text-system-text mb-6">Мой профиль</h1>
    <div class="bg-system-surface rounded-2xl border border-system-border p-6 space-y-4">
        
        <div class="p-4 rounded-xl bg-primary-50 border border-primary-100 flex items-start gap-3 mb-2">
            <span class="text-primary-500 mt-0.5"><svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg></span>
            <div>
                <p class="text-xs font-bold text-primary-600 uppercase tracking-wide mb-1">Мой тариф</p>
                <p class="text-sm font-medium text-system-text">${tariffText}</p>
                <p class="text-[10px] text-system-muted mt-1 leading-tight">Установлено вашим салоном. Для изменения свяжитесь с руководителем.</p>
            </div>
        </div>

        <div class="flex items-center gap-4 mb-4">
            <img src="${master.avatar}" class="w-20 h-20 rounded-full border-4 border-primary-100">
            <div>
                <h2 class="font-bold text-system-text text-lg">${master.name}</h2>
                <p class="text-primary-500">${master.specialty}</p>
            </div>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Специальность</label>
            <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${master.specialty}" oninput="masters.find(m=>m.id===${master.id}).specialty=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">О себе</label>
            <textarea class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm resize-none" rows="3" oninput="masters.find(m=>m.id===${master.id}).about=this.value">${master.about}</textarea>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Статус</label>
            <div class="flex gap-3">
                <button onclick="masters.find(m=>m.id===${master.id}).available=true;showToast('Статус: Доступна');render()" class="flex-1 py-2.5 rounded-xl border-2 ${master.available ? 'border-green-400 bg-green-50 text-green-700' : 'border-system-border text-system-muted'} text-sm font-medium">● Доступна</button>
                <button onclick="masters.find(m=>m.id===${master.id}).available=false;showToast('Статус: Недоступна');render()" class="flex-1 py-2.5 rounded-xl border-2 ${!master.available ? 'border-red-400 bg-red-50 text-red-700' : 'border-system-border text-system-muted'} text-sm font-medium">○ Недоступна</button>
            </div>
        </div>
        <button onclick="showToast('Профиль сохранён')" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm shadow-xl shadow-primary-200">Сохранить</button>
    </div>
</div>`;
    }
}


window.toggleMasterSelfService = function(masterId, serviceId) {
    const m = masters.find(x => x.id === masterId);
    if (!m) return;
    if (!m.services) m.services = [];
    const idx = m.services.indexOf(serviceId);
    if (idx >= 0) { m.services.splice(idx, 1); }
    else { m.services.push(serviceId); }
    render();
};

window.updateMasterSelfPrice = function(masterId, serviceId, val) {
    const m = masters.find(x => x.id === masterId);
    if (!m) return;
    if (!m.customPrices) m.customPrices = {};
    m.customPrices[serviceId] = parseInt(val, 10) || 0;
    render();
};

window.renderMasterContent = renderMasterContent;

export function renderMasterSalonsTab(master) {
    const currentSalon = salons.find(s => s.id === master.salonId);
    const availableSalons = salons.filter(s => s.id !== master.salonId);
    const myApps = salonApplications.filter(a => a.userId === state.currentUser.id);

    return `
    <div class="animate-fade-in space-y-8">
        <h1 class="text-2xl font-bold text-system-text">Мои салоны</h1>

        <div class="space-y-4">
            <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">Текущее место работы</h3>
            ${currentSalon ? `
                <div class="bg-gradient-to-br from-green-500 to-green-600 rounded-3xl p-6 text-white shadow-xl shadow-green-100 flex items-center justify-between">
                    <div>
                        <h2 class="text-xl font-bold">${currentSalon.name}</h2>
                        <p class="text-green-100 text-sm">${currentSalon.address}</p>
                        <div class="mt-4 inline-flex items-center gap-2 px-3 py-1 bg-system-surface/20 rounded-full text-[10px] font-bold uppercase tracking-widest">
                            Вы в штате
                        </div>
                    </div>
                    <div class="w-16 h-16 bg-system-surface/10 rounded-2xl flex items-center justify-center text-3xl">🏦</div>
                </div>
            ` : `
                <div class="p-8 bg-system-surface rounded-3xl border border-dashed border-system-border text-center text-system-muted opacity-70 italic">
                    Вы пока не привязаны ни к одному салону
                </div>
            `}
        </div>

        ${myApps.length > 0 ? `
            <div class="space-y-4">
                <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">Мои заявки</h3>
                <div class="grid grid-cols-1 gap-3">
                    ${myApps.map(app => {
                        const salon = salons.find(s => s.id === app.salonId);
                        const statusColor = app.status === 'approved' ? 'text-green-600 bg-green-50' : (app.status === 'pending' ? 'text-yellow-600 bg-transparent text-yellow-500' : 'text-red-600 bg-red-50');
                        return `
                        <div class="bg-system-surface p-4 rounded-2xl border border-system-border flex items-center justify-between">
                            <div>
                                <h4 class="font-bold text-system-text">${salon?.name || '---'}</h4>
                                <p class="text-xs text-system-muted opacity-70">${new Date(app.createdAt).toLocaleDateString()}</p>
                            </div>
                            <span class="px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest ${statusColor}">
                                ${app.status}
                            </span>
                        </div>
                        `;
                    }).join('')}
                </div>
            </div>
        ` : ''}

        <div class="space-y-4">
            <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">Доступные салоны</h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                ${availableSalons.map(s => {
                    const hasApp = myApps.find(a => a.salonId === s.id && a.status === 'pending');
                    return `
                    <div class="bg-system-surface rounded-3xl p-5 border border-system-border shadow-sm hover:shadow-md transition-all">
                        <h4 class="font-bold text-system-text mb-1">${s.name}</h4>
                        <p class="text-xs text-system-muted mb-4">${s.address}</p>
                        <button onclick="handleApplyToSalon(${s.id})" ${hasApp ? 'disabled' : ''} 
                            class="w-full py-3 rounded-xl font-bold text-xs transition-all ${hasApp ? 'bg-system-main text-system-muted opacity-70 cursor-default' : 'bg-green-600 text-white hover:bg-green-700 shadow-lg shadow-green-100'}">
                            ${hasApp ? 'Заявка подана' : 'Подать заявку'}
                        </button>
                    </div>
                    `;
                }).join('')}
            </div>
        </div>
    </div>
    `;
}

window.renderMasterSalonsTab = renderMasterSalonsTab;

async function handleApplyToSalon(salonId) {
    const res = await applyToSalon(salonId, state.currentUser.id, 'master');
    if (res.success) {
        showToast('Заявка успешно подана');
        render();
    } else {
        showToast(res.error || 'Ошибка', 'error');
    }
}
window.handleApplyToSalon = handleApplyToSalon;
