// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { renderClientMobileNav, renderThemeSwitcher, renderUserDropdown, renderClientFooter, toggleMobileMenu, renderToast } from '../../components/ui.js';
import { renderHomePage, renderSalonsPage, renderMastersPage, renderServicesPage, renderSalonDetailPage, renderMasterDetailPage, renderServiceDetailPage, renderBookingsPage } from './pages.js';
import { renderReviewModal, renderProfileEditModal, renderTrackModal } from '../../components/modals.js';
import { renderBookingModal } from '../../features/booking/wizard.js';
import { navigate } from '../../core/router.js';
import { state } from '../../state.js';
import { getUserBookings } from '../../utils.js';

export function renderClientApp() {
    return `
${renderClientHeader()}
<main class="pb-20">
    ${renderClientMainContent()}
</main>
${renderClientFooter()}
${renderClientMobileNav()}
${state.bookingModal ? renderBookingModal() : ''}
${state.toast ? renderToast() : ''}
${state.showProfileEdit ? renderProfileEditModal() : ''}
${state.reviewModalTarget ? renderReviewModal() : ''}
${state.trackModalTarget ? renderTrackModal() : ''}
    `;
}

window.renderClientApp = renderClientApp;

export function renderClientHeader() {
    const bookingCount = getUserBookings().filter(b => b.status === 'pending').length;
    let userSection = '';
    
    if (state.currentUser) {
        const userName = state.currentUser.name || state.currentUser.phone;
        const initials = userName.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase();
        userSection = `
            <div class="relative cursor-pointer" onclick="navigate('bookings')">
                <svg class="w-6 h-6 ${state.currentPage === 'bookings' ? 'text-primary-600' : 'text-system-muted'}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
                </svg>
                ${bookingCount > 0 ? `<span class="notification-badge">${bookingCount}</span>` : ''}
            </div>
            <div class="relative">
                <div class="w-9 h-9 rounded-full bg-primary-100 flex items-center justify-center cursor-pointer hover:bg-primary-200 transition-colors" onclick="toggleMobileMenu()">
                    <span class="text-sm font-bold text-primary-600">${initials}</span>
                </div>
                ${state.mobileMenu ? renderUserDropdown() : ''}
            </div>
        `;
    } else {
        userSection = `
            <button onclick="state.showAuthPage=true; render()" class="text-sm font-bold text-primary-600 hover:text-primary-700 bg-primary-50 px-4 py-2 rounded-xl transition-colors">Войти</button>
        `;
    }

    return `
    <div class="px-2 sm:px-4 pt-1 sm:pt-2 sticky top-1 sm:top-2 z-[100] transition-all">
        <header class="island-header max-w-7xl mx-auto px-3 sm:px-4">
            <div class="flex items-center justify-between h-11 sm:h-12">
                <div class="flex items-center gap-2 cursor-pointer" onclick="navigate('home')">
                    <div class="w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-primary-500 flex items-center justify-center shadow-md">
                        <span class="text-white"><svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg></span>
                    </div>
                    <span class="text-base sm:text-lg font-bold text-system-text hidden sm:block">SuluuMarket</span>
                </div>
                <nav class="hidden md:flex items-center gap-6 lg:gap-8">
                    <a href="#" onclick="navigate('home')" class="flex items-center gap-1.5 text-sm font-medium ${state.currentPage === 'home' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'} transition-colors">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg>
                        Главная
                    </a>
                    <a href="#" onclick="navigate('salons')" class="flex items-center gap-1.5 text-sm font-medium ${state.currentPage === 'salons' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'} transition-colors">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"/></svg>
                        Салоны
                    </a>
                    <a href="#" onclick="navigate('masters')" class="flex items-center gap-1.5 text-sm font-medium ${state.currentPage === 'masters' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'} transition-colors">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                        Мастера
                    </a>
                    <a href="#" onclick="navigate('services')" class="flex items-center gap-1.5 text-sm font-medium ${state.currentPage === 'services' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'} transition-colors">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
                        Услуги
                    </a>
                    <a href="#" onclick="navigate('bookings')" class="flex items-center gap-1.5 text-sm font-medium ${state.currentPage === 'bookings' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'} transition-colors relative">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                        Мои записи${bookingCount > 0 ? `<span class="absolute -top-2 -right-3 bg-primary-600 text-white text-[10px] w-4 h-4 rounded-full flex items-center justify-center font-bold border border-system-surface">${bookingCount}</span>` : ''}
                    </a>
                </nav>
                <div class="flex items-center gap-2 sm:gap-3">
                    <div class="relative flex items-center justify-end h-9">
                        <div class="flex items-center overflow-hidden transition-all duration-300 ease-in-out ${state.isSearchExpanded ? 'w-40 sm:w-64 opacity-100' : 'w-0 opacity-0'}">
                            <input type="text" placeholder="Поиск..." 
                                class="w-full px-4 py-1.5 rounded-full border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-sm bg-system-surface text-system-text shadow-sm transition-all"
                                value="${state.searchQuery || ''}" 
                                oninput="state.searchQuery=this.value; if(window.location.hash.includes('salons') || window.location.hash.includes('masters') || window.location.hash.includes('services')) window.render();" 
                                onkeydown="if(event.key==='Enter'){ state.isSearchExpanded=false; window.performSearch?window.performSearch():window.render(); }"
                                onblur="if(!this.value){ state.isSearchExpanded = false; window.render(); }"
                                id="navSearchInput"
                            >
                        </div>
                        <button onclick="state.isSearchExpanded = !state.isSearchExpanded; window.render(); if(state.isSearchExpanded) setTimeout(() => document.getElementById('navSearchInput').focus(), 100);" 
                            class="w-9 h-9 shrink-0 outline-none rounded-full flex items-center justify-center transition-all text-system-text z-[1] ${state.isSearchExpanded ? 'absolute right-2 opacity-0 pointer-events-none' : 'hover:bg-system-border'}" title="Поиск">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                        </button>
                    </div>
                    ${renderThemeSwitcher()}
                    ${userSection}
                </div>
            </div>
        </header>
    </div>`;
}

window.renderClientHeader = renderClientHeader;

export function renderClientMainContent() {
    switch (state.currentPage) {
        case 'home': return renderHomePage();
        case 'salons': return renderSalonsPage();
        case 'masters': return renderMastersPage();
        case 'services': return renderServicesPage();
        case 'bookings': return renderBookingsPage();
        case 'salon-detail': return renderSalonDetailPage();
        case 'master-detail': return renderMasterDetailPage();
        case 'service-detail': return renderServiceDetailPage();
        default: return renderHomePage();
    }
}

window.renderClientMainContent = renderClientMainContent;

