// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { renderClientMobileNav, renderThemeSwitcher, renderUserDropdown, renderClientFooter, toggleMobileMenu, renderToast } from '../../components/ui.js';
import { renderHomePage, renderSalonsPage, renderMastersPage, renderServicesPage, renderSalonDetailPage, renderMasterDetailPage, renderServiceDetailPage, renderBookingsPage } from './pages.js';
import { renderReviewModal, renderProfileEditModal, renderTrackModal } from '../../components/modals.js';
import { renderBookingModal } from '../../features/booking/wizard.js';
import { navigate } from '../../core/router.js';
import { state } from '../../state.js';
import { getUserBookings } from '../../utils.js';

export function renderClientApp() {
    return `
${renderClientHeader()}
<main class="pb-20">
    ${renderClientMainContent()}
</main>
${renderClientFooter()}
${renderClientMobileNav()}
${state.bookingModal ? renderBookingModal() : ''}
${state.toast ? renderToast() : ''}
${state.showProfileEdit ? renderProfileEditModal() : ''}
${state.reviewModalTarget ? renderReviewModal() : ''}
${state.trackModalTarget ? renderTrackModal() : ''}
    `;
}

window.renderClientApp = renderClientApp;

export function renderClientHeader() {
    const bookingCount = getUserBookings().filter(b => b.status === 'pending').length;
    let userSection = '';
    
    if (state.currentUser) {
        const userName = state.currentUser.name || state.currentUser.phone;
        const initials = userName.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase();
        userSection = `
            <div class="relative cursor-pointer" onclick="navigate('bookings')">
                <svg class="w-6 h-6 ${state.currentPage === 'bookings' ? 'text-primary-600' : 'text-system-muted'}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
                </svg>
                ${bookingCount > 0 ? `<span class="notification-badge">${bookingCount}</span>` : ''}
            </div>
            <div class="relative">
                <div class="w-9 h-9 rounded-full bg-primary-100 flex items-center justify-center cursor-pointer hover:bg-primary-200 transition-colors" onclick="toggleMobileMenu()">
                    <span class="text-sm font-bold text-primary-600">${initials}</span>
                </div>
                ${state.mobileMenu ? renderUserDropdown() : ''}
            </div>
        `;
    } else {
        userSection = `
            <button onclick="state.showAuthPage=true; render()" class="text-sm font-bold text-primary-600 hover:text-primary-700 bg-primary-50 px-4 py-2 rounded-xl transition-colors">Войти</button>
        `;
    }

    return `
    <header class="bg-system-surface/80 backdrop-blur-lg border-b border-system-border sticky top-0 z-50">
<div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex items-center justify-between h-16">
        <div class="flex items-center gap-2 cursor-pointer" onclick="navigate('home')">
            <div class="w-9 h-9 rounded-xl bg-primary-500 flex items-center justify-center">
                <span class="text-white text-lg">✦</span>
            </div>
            <span class="text-xl font-bold text-system-text">BeautyPlace KG</span>
        </div>
        <nav class="hidden md:flex items-center gap-8">
            <a href="#" onclick="navigate('home')" class="text-sm font-medium ${state.currentPage === 'home' ? 'text-primary-600' : 'text-system-muted hover:text-primary-600'} transition-colors">Главная</a>
            <a href="#" onclick="navigate('salons')" class="text-sm font-medium ${state.currentPage === 'salons' ? 'text-primary-600' : 'text-system-muted hover:text-primary-600'} transition-colors">Салоны</a>
            <a href="#" onclick="navigate('masters')" class="text-sm font-medium ${state.currentPage === 'masters' ? 'text-primary-600' : 'text-system-muted hover:text-primary-600'} transition-colors">Мастера</a>
            <a href="#" onclick="navigate('services')" class="text-sm font-medium ${state.currentPage === 'services' ? 'text-primary-600' : 'text-system-muted hover:text-primary-600'} transition-colors">Услуги</a>
            <a href="#" onclick="navigate('bookings')" class="text-sm font-medium ${state.currentPage === 'bookings' ? 'text-primary-600' : 'text-system-muted hover:text-primary-600'} transition-colors relative">
                Мои записи${bookingCount > 0 ? `<span class="absolute -top-2 -right-3 bg-primary-600 text-white text-[10px] w-4 h-4 rounded-full flex items-center justify-center font-bold border border-system-surface">${bookingCount}</span>` : ''}
            </a>
        </nav>
        <div class="flex items-center gap-3">
            ${renderThemeSwitcher()}
            ${userSection}
        </div>
    </div>
</div>
    </header>`;
}

window.renderClientHeader = renderClientHeader;

export function renderClientMainContent() {
    switch (state.currentPage) {
        case 'home': return renderHomePage();
        case 'salons': return renderSalonsPage();
        case 'masters': return renderMastersPage();
        case 'services': return renderServicesPage();
        case 'bookings': return renderBookingsPage();
        case 'salon-detail': return renderSalonDetailPage();
        case 'master-detail': return renderMasterDetailPage();
        case 'service-detail': return renderServiceDetailPage();
        default: return renderHomePage();
    }
}

window.renderClientMainContent = renderClientMainContent;

