// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { handleLogout } from '../../features/auth/actions.js';
import { renderServiceCard, renderSalonCard, renderMasterCard } from '../../components/cards.js';
import { editBooking, openBookingForSalon, openBookingForMaster, openBookingForService, openBookingForServiceInSalon, openBookingForServiceWithMaster, goToBookingStep, cancelBooking, trackBooking } from '../../features/booking/actions.js';
import { navigate } from '../../core/router.js';
import { state, services, salons, masters, categories, users, timeSlots } from '../../state.js';
import { formatPrice, getDurationText, getPriceLevel, getSalonPrice, getSalonDuration, getSalonServices, formatDate, getStars, showToast, ThemeManager } from '../../utils.js';
import { getAvatarPlaceholder } from '../../api.js';

export function renderHomePage() {
    const popularServices = services.filter(s => s.popular).slice(0, 8);
    const topSalons = [...salons].sort((a, b) => b.rating - a.rating).slice(0, 3);
    const topMasters = [...masters].filter(m => m.available).sort((a, b) => b.rating - a.rating).slice(0, 4);

    return `
    <main>
<section class="island hero-gradient max-w-7xl mx-auto px-4 sm:px-6 mx-4 mb-8 mt-4 py-16 md:py-24">
        <div class="text-center max-w-3xl mx-auto animate-fade-in">
            <h1 class="text-4xl md:text-6xl font-bold text-system-text mb-6 leading-tight">
                Найдите идеального <span class="gradient-text">beauty-мастера</span>
            </h1>
            <p class="text-lg md:text-xl text-system-muted mb-10 leading-relaxed">
                Записывайтесь в лучшие салоны красоты и к проверенным мастерам онлайн. Быстро, удобно, без звонков.
            </p>
            
            <div class="flex flex-wrap justify-center gap-2 mt-6">
                <span class="text-xs text-system-muted">Популярное:</span>
                ${['Маникюр', 'Стрижка', 'Макияж', 'Массаж'].map(t =>
        `<span class="text-xs text-primary-500 cursor-pointer hover:underline" onclick="state.searchQuery='${t}';performSearch()">${t}</span>`
    ).join('')}
            </div>
        </div>
</section>

<section class="island max-w-7xl mx-auto px-4 sm:px-6 mx-4 mb-8 mt-4">
        <h2 class="text-2xl font-bold text-system-text mb-8">Категории услуг</h2>
        <div class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-3">
            ${categories.map(cat => `
                <div class="category-pill cursor-pointer bg-system-main hover:bg-primary-50 rounded-2xl p-4 text-center transition-all"
                     onclick="filterByCategory(${cat.id})">
                    <div class="text-3xl mb-2">${cat.icon}</div>
                    <div class="text-sm font-medium text-system-text opacity-90">${cat.name}</div>
                    <div class="text-xs text-system-muted opacity-80 mt-1">${services.filter(s => s.category === cat.id).length} услуг</div>
                </div>
            `).join('')}
        </div>
    </section>

<section class="island max-w-7xl mx-auto px-4 sm:px-6 mx-4 mb-8">
        <div class="flex items-center justify-between mb-8">
            <h2 class="text-2xl font-bold text-system-text">Рекомендуемые услуги</h2>
            <a href="#" onclick="navigate('services')" class="text-sm text-primary-500 font-medium hover:underline">Все услуги →</a>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            ${popularServices.map(svc => renderServiceCard(svc)).join('')}
        </div>
    </section>

<section class="island max-w-7xl mx-auto px-4 sm:px-6 mx-4 mb-8 mt-4">
        <div class="flex items-center justify-between mb-8">
            <h2 class="text-2xl font-bold text-system-text">Лучшие салоны</h2>
            <a href="#" onclick="navigate('salons')" class="text-sm text-primary-500 font-medium hover:underline">Все салоны →</a>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            ${topSalons.map(salon => renderSalonCard(salon)).join('')}
        </div>
    </section>

<section class="island max-w-7xl mx-auto px-4 sm:px-6 mx-4 mb-8">
        <div class="flex items-center justify-between mb-8">
            <h2 class="text-2xl font-bold text-system-text">Топ-мастера</h2>
            <a href="#" onclick="navigate('masters')" class="text-sm text-primary-500 font-medium hover:underline">Все мастера →</a>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            ${topMasters.map(master => renderMasterCard(master)).join('')}
        </div>
    </section>

${!state.currentUser ? `
<section id="track-booking" class="island max-w-3xl mx-auto px-4 sm:px-6 text-center mx-4 mb-8">
        <h2 class="text-2xl font-bold text-system-text mb-4">Проверить статус записи</h2>
        <p class="text-system-muted mb-8">Введите код отслеживания, который вы получили при создании записи</p>
        <div class="flex flex-col sm:flex-row gap-3 max-w-md mx-auto">
            <input type="text" id="trackingCodeInput" placeholder="Например: A7X9Q2" class="flex-1 px-4 py-3.5 rounded-2xl border border-system-border focus:border-primary-400 bg-system-surface text-system-text font-mono tracking-widest uppercase text-center outline-none">
            <button onclick="trackBooking()" class="btn-primary px-8 py-3.5 rounded-2xl text-white font-bold whitespace-nowrap shadow-md shadow-primary-200 hover:-translate-y-0.5 transition-transform">Найти запись</button>
        </div>
    </section>
` : ''}

<section class="island max-w-3xl mx-auto px-4 text-center bg-gradient-to-r from-primary-500 to-primary-600 !border-none mx-4 mb-8">
        <h2 class="text-3xl font-bold text-white mb-4">Вы beauty-мастер или владелец салона?</h2>
        <p class="text-primary-100 mb-8 text-lg">Присоединяйтесь к Suluu и получайте новых клиентов каждый день</p>
        <button onclick="handleLogout()" class="bg-system-surface text-primary-600 px-8 py-3.5 rounded-2xl font-semibold text-sm hover:bg-primary-50 transition-colors shadow-lg">
            Зарегистрироваться
        </button>
    </section>
    </main>`;
}

window.renderHomePage = renderHomePage;

export function renderSalonsPage() {
    let filtered = salons;
    if (state.activeCategory) filtered = filtered.filter(s => s.categories.includes(state.activeCategory));
    if (state.searchQuery) {
        const q = state.searchQuery.toLowerCase();
        filtered = filtered.filter(s => s.name.toLowerCase().includes(q) || s.address.toLowerCase().includes(q));
    }

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
    <h1 class="text-3xl font-bold text-system-text">Салоны красоты</h1>
    <div class="relative">
        <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-system-muted opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
        </svg>
        <input type="text" placeholder="Поиск салонов..."
            class="pl-9 pr-4 py-2.5 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm w-full md:w-64"
            value="${state.searchQuery}" oninput="state.searchQuery=this.value;render()">
    </div>
</div>
<div class="flex gap-2 overflow-x-auto scrollbar-hide mb-8 pb-4 px-4 -mx-4 snap-x snap-mandatory">
    <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${!state.activeCategory ? 'active' : 'bg-system-main text-system-muted'}"
         onclick="state.activeCategory=null;render()">Все</div>
    ${categories.map(cat => `
        <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${state.activeCategory === cat.id ? 'active' : 'bg-system-main text-system-muted'}"
             onclick="state.activeCategory=${cat.id};render()">${cat.icon} ${cat.name}</div>
    `).join('')}
</div>
<p class="text-sm text-system-muted mb-6">Найдено: ${filtered.length} салонов</p>
${filtered.length > 0 ? `
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        ${filtered.map(salon => renderSalonCard(salon)).join('')}
    </div>
` : `<div class="text-center py-20"><div class="text-5xl mb-4">🔍</div><h3 class="text-lg font-semibold text-system-text mb-2">Салоны не найдены</h3><p class="text-system-muted opacity-70">Попробуйте изменить параметры поиска</p></div>`}
    </main>`;
}

window.renderSalonsPage = renderSalonsPage;

export function renderMastersPage() {
    let filtered = masters;
    if (state.activeCategory) filtered = filtered.filter(m => m.categories.includes(state.activeCategory));
    if (state.searchQuery) {
        const q = state.searchQuery.toLowerCase();
        filtered = filtered.filter(m => m.name.toLowerCase().includes(q) || m.specialty.toLowerCase().includes(q));
    }

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
    <h1 class="text-3xl font-bold text-system-text">Мастера</h1>
    <div class="relative">
        <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-system-muted opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
        </svg>
        <input type="text" placeholder="Поиск мастеров..."
            class="pl-9 pr-4 py-2.5 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm w-full md:w-64"
            value="${state.searchQuery}" oninput="state.searchQuery=this.value;render()">
    </div>
</div>
<div class="flex gap-2 overflow-x-auto scrollbar-hide mb-8 pb-4 px-4 -mx-4 snap-x snap-mandatory">
    <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${!state.activeCategory ? 'active' : 'bg-system-main text-system-muted'}"
         onclick="state.activeCategory=null;render()">Все</div>
    ${categories.map(cat => `
        <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${state.activeCategory === cat.id ? 'active' : 'bg-system-main text-system-muted'}"
             onclick="state.activeCategory=${cat.id};render()">${cat.icon} ${cat.name}</div>
    `).join('')}
</div>
<p class="text-sm text-system-muted mb-6">Найдено: ${filtered.length} мастеров</p>
${filtered.length > 0 ? `
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        ${filtered.map(master => renderMasterCard(master)).join('')}
    </div>
` : `<div class="text-center py-20"><div class="text-5xl mb-4">🔍</div><h3 class="text-lg font-semibold text-system-text mb-2">Мастера не найдены</h3><p class="text-system-muted opacity-70">Попробуйте изменить параметры поиска</p></div>`}
    </main>`;
}

window.renderMastersPage = renderMastersPage;

export function renderServicesPage() {
    let filtered = services;
    if (state.activeCategory) filtered = filtered.filter(s => s.category === state.activeCategory);
    if (state.serviceGenderFilter && state.serviceGenderFilter !== 'all') {
        filtered = filtered.filter(s => s.gender === state.serviceGenderFilter || s.gender === 'all');
    }
    if (state.searchQuery) {
        const q = state.searchQuery.toLowerCase();
        filtered = filtered.filter(s => s.name.toLowerCase().includes(q));
    }

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
    <h1 class="text-3xl font-bold text-system-text">Услуги</h1>
    <div class="relative">
        <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-system-muted opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
        </svg>
        <input type="text" placeholder="Поиск услуг..."
            class="pl-9 pr-4 py-2.5 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm w-full md:w-64"
            value="${state.searchQuery}" oninput="state.searchQuery=this.value;render()">
    </div>
</div>
<div class="flex gap-2 mb-6 scrollbar-hide overflow-x-auto">
    <button onclick="state.serviceGenderFilter='all'; render()" class="shrink-0 px-4 py-1.5 rounded-xl text-sm font-medium transition-colors ${(!state.serviceGenderFilter || state.serviceGenderFilter === 'all') ? 'bg-gray-900 text-white' : 'bg-system-main text-system-muted hover:bg-gray-200'}">Все типы</button>
    <button onclick="state.serviceGenderFilter='female'; render()" class="shrink-0 px-4 py-1.5 rounded-xl text-sm font-medium transition-colors ${state.serviceGenderFilter === 'female' ? 'bg-gray-900 text-white' : 'bg-system-main text-system-muted hover:bg-gray-200'}">Женские</button>
    <button onclick="state.serviceGenderFilter='male'; render()" class="shrink-0 px-4 py-1.5 rounded-xl text-sm font-medium transition-colors ${state.serviceGenderFilter === 'male' ? 'bg-gray-900 text-white' : 'bg-system-main text-system-muted hover:bg-gray-200'}">Мужские</button>
</div>
<div class="flex gap-2 overflow-x-auto scrollbar-hide mb-8 pb-4 px-4 -mx-4 snap-x snap-mandatory">
    <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${!state.activeCategory ? 'active' : 'bg-system-main text-system-muted'}"
         onclick="state.activeCategory=null;render()">Все</div>
    ${categories.map(cat => `
        <div class="snap-start shrink-0 category-pill cursor-pointer px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${state.activeCategory === cat.id ? 'active' : 'bg-system-main text-system-muted'}"
             onclick="state.activeCategory=${cat.id};render()">${cat.icon} ${cat.name}</div>
    `).join('')}
</div>
<p class="text-sm text-system-muted mb-6">Найдено: ${filtered.length} услуг</p>
${filtered.length > 0 ? `
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        ${filtered.map(svc => renderServiceCard(svc)).join('')}
    </div>
` : `<div class="text-center py-20"><div class="text-5xl mb-4">🔍</div><h3 class="text-lg font-semibold text-system-text mb-2">Услуги не найдены</h3><p class="text-system-muted opacity-70">Попробуйте изменить параметры поиска</p></div>`}
    </main>`;
}

window.renderServicesPage = renderServicesPage;

export function renderSalonDetailPage() {
    const salon = salons.find(s => s.id === state.selectedSalon);
    if (!salon) return '<div class="text-center py-20"><p>Салон не найден</p></div>';
    const salonMasters = masters.filter(m => m.salonId === salon.id);
    const salonServices = getSalonServices(salon, services);

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<button onclick="navigate('salons')" class="flex items-center gap-2 text-sm text-system-muted hover:text-primary-500 mb-6 transition-colors">
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
    Назад к салонам
</button>
<div class="bg-system-surface rounded-3xl border border-system-border overflow-hidden mb-8 animate-fade-in">
    <img src="${salon.image}" alt="${salon.name}" class="w-full h-64 md:h-80 object-cover">
    <div class="p-6 md:p-8">
        <div class="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-4">
            <div>
                <div class="flex items-center gap-3 mb-2">
                    <h1 class="text-3xl font-bold text-system-text">${salon.name}${isPrivateMaster ? ` <span class="text-lg font-normal text-system-muted opacity-70 ml-2">Частный мастер</span>` : ``}</h1>
                    ${salon.verified ? '<span class="badge bg-blue-100 text-blue-600">✓ Проверен</span>' : ''}
                </div>
                <div class="flex items-center gap-2 mb-2">
                    <span class="star">★</span><span class="font-semibold text-system-text opacity-90">${salon.rating}</span>
                    <span class="text-system-muted opacity-80">(${salon.reviews} отзывов)</span>
                    <span class="text-system-muted opacity-80 ml-2">${getPriceLevel(salon.priceLevel)}</span>
                </div>
                <p class="text-system-muted">📍 ${salon.address}, ${salon.city || 'Бишкек'}</p>
                <p class="text-system-muted opacity-80 text-sm mt-1">🕐 ${salon.openTime}–${salon.closeTime} · ${isPrivateMaster ? `Частный мастер` : salonMasters.length + ` мастерог`}</p>>
            </div>
            <button onclick="openBookingForSalon(${salon.id})" class="btn-primary px-8 py-3 rounded-2xl text-white font-semibold whitespace-nowrap">Записаться</button>
        </div>
        <div class="flex flex-wrap gap-2 mt-4">
            ${salon.features.map(f => `<span class="badge bg-green-50 text-green-700">${f}</span>`).join('')}
        </div>
    </div>
</div>
<div class="mb-8">
    <h2 class="text-xl font-bold text-system-text mb-4">Услуги ${isPrivateMaster ? `мастер` : `салона`}</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        ${salonServices.map(svc => `
            <div class="bg-system-surface rounded-xl border border-system-border/50 p-4 flex items-center justify-between card-hover cursor-pointer" onclick="openBookingForServiceInSalon(${svc.id}, ${salon.id})">
                <div class="flex-1 min-w-0 pr-2">
                    <h3 class="font-medium text-system-text truncate">
                        <span class="text-xs mr-1 opacity-60">${svc.gender === 'male' ? '👨' : svc.gender === 'female' ? '👩' : '🚻'}</span>
                        ${svc.name}
                    </h3>
                    <p class="text-sm text-system-muted opacity-80">${getDurationText(getSalonDuration(salon.id, svc.id, services))} · <span class="star text-xs">★</span> ${svc.rating}</p>
                </div>
                <div class="text-right"><p class="font-bold text-system-text">${formatPrice(getSalonPrice(salon.id, svc.id, services, typeof master !== 'undefined' ? master.id : undefined))}</p></div>
            </div>
        `).join('')}
    </div>
</div>
${salonMasters.length > 0 ? `
    <div>
        <h2 class="text-xl font-bold text-system-text mb-4">Мастера салона</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            ${salonMasters.map(master => renderMasterCard(master)).join('')}
        </div>
    </div>
` : ''}
${renderReviewsSection('salon', salon.id)}
    </main>`;
}

window.renderSalonDetailPage = renderSalonDetailPage;

export function renderMasterDetailPage() {
    const master = masters.find(m => m.id === state.selectedMaster);
    if (!master) return '<div class="text-center py-20"><p>Мастер не найден</p></div>';
    const masterServices = services.filter(s => master.services.includes(s.id));
    const salon = master.salonId ? salons.find(s => s.id === master.salonId) : null;

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<button onclick="navigate('masters')" class="flex items-center gap-2 text-sm text-system-muted hover:text-primary-500 mb-6 transition-colors">
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
    Назад к мастерам
</button>
<div class="bg-system-surface rounded-3xl border border-system-border/50 p-6 md:p-8 mb-8 animate-fade-in">
    <div class="flex flex-col md:flex-row gap-6">
        <div class="flex-shrink-0">
            <img src="${master.avatar}" alt="${master.name}" class="w-32 h-32 rounded-full object-cover border-4 border-primary-100 mx-auto md:mx-0">
        </div>
        <div class="flex-1 text-center md:text-left">
            <h1 class="text-3xl font-bold text-system-text mb-1">${master.name}</h1>
            <p class="text-primary-500 font-medium text-lg mb-2">${master.specialty}</p>
            <div class="flex items-center justify-center md:justify-start gap-2 mb-3">
                <span class="star">★</span><span class="font-semibold text-system-text opacity-90">${master.rating}</span>
                <span class="text-system-muted opacity-80">(${master.reviews} отзывов)</span>
                <span class="text-system-muted opacity-80 ml-2">${getPriceLevel(master.priceLevel)}</span>
            </div>
            <p class="text-system-muted mb-2">Опыт работы: ${master.experience} лет</p>
            ${salon ? `<p class="text-system-muted mb-2">📍 Салон: <a href="#" onclick="openSalonDetail(${salon.id})" class="text-primary-500 hover:underline">${salon.name}</a></p>` : '<p class="text-system-muted mb-2">📍 Работает на выезде</p>'}
            <p class="text-system-text opacity-80 mt-3 leading-relaxed">${master.about}</p>
            ${master.available ? `<button onclick="openBookingForMaster(${master.id})" class="btn-primary px-8 py-3 rounded-2xl text-white font-semibold mt-4">Записаться</button>` : '<p class="text-system-muted opacity-80 mt-4">Нет свободных слотов</p>'}
        </div>
    </div>
</div>
<div>
    <h2 class="text-xl font-bold text-system-text mb-4">Услуги мастера</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        ${masterServices.map(svc => `
            <div class="bg-system-surface rounded-xl border border-system-border/50 p-4 flex items-center justify-between card-hover cursor-pointer" onclick="openBookingForServiceWithMaster(${svc.id}, ${master.id})">
                <div class="flex-1 min-w-0 pr-2">
                    <h3 class="font-medium text-system-text truncate">
                        <span class="text-xs mr-1 opacity-60">${svc.gender === 'male' ? '👨' : svc.gender === 'female' ? '👩' : '🚻'}</span>
                        ${svc.name}
                    </h3>
                    <p class="text-sm text-system-muted opacity-70">${getDurationText(salon ? getSalonDuration(salon.id, svc.id, services) : svc.duration)} · <span class="star text-xs">★</span> ${svc.rating}</p>
                </div>
                <div class="text-right"><p class="font-bold text-system-text">${formatPrice(salon ? getSalonPrice(salon.id, svc.id, services, typeof master !== 'undefined' ? master.id : undefined) : svc.price)}</p></div>
            </div>
        `).join('')}
    </div>
</div>
${renderReviewsSection('master', master.id)}
    </main>`;
}

window.renderMasterDetailPage = renderMasterDetailPage;

export function renderServiceDetailPage() {
    const svc = services.find(s => s.id === state.selectedService);
    if (!svc) return '<div class="text-center py-20"><p>Услуга не найдена</p></div>';
    
    const cat = categories.find(c => c.id === svc.category);
    
    // Gather all salons and masters that offer this service
    const offeringSalons = salons.filter(s => getSalonServices(s, services).some(ss => ss.id === svc.id));
    const independentMasters = masters.filter(m => !m.salonId && m.services && m.services.includes(svc.id));

    return `
    <main class="island max-w-7xl mx-auto px-4 sm:px-6 mt-6 mx-4">
<button onclick="navigate('services')" class="flex items-center gap-2 text-sm text-system-muted hover:text-primary-500 mb-6 transition-colors">
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
    Назад к услугам
</button>
<div class="bg-system-surface rounded-3xl border border-system-border/50 p-6 md:p-8 mb-8 animate-fade-in">
    <div class="flex flex-col md:flex-row gap-6">
        <!-- If there's an image, we can show it here. For now, a placeholder or icon. -->
        <div class="w-full md:w-1/3 flex-shrink-0">
            <div class="w-full h-48 md:h-64 rounded-2xl bg-gradient-to-br from-primary-50 to-purple-50 flex items-center justify-center border-2 border-dashed border-primary-100">
                <span class="text-6xl">${cat ? cat.icon : '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m12 3-1.9 5.8a2 2 0 0 1-1.287 1.288L3 12l5.8 1.9a2 2 0 0 1 1.288 1.287L12 21l1.9-5.8a2 2 0 0 1 1.287-1.288L21 12l-5.8-1.9a2 2 0 0 1-1.288-1.287Z"/></svg>'}</span>
            </div>
        </div>
        <div class="flex-1 text-center md:text-left flex flex-col justify-center">
            <div class="flex items-center justify-center md:justify-start gap-2 mb-2">
                <span class="text-xs font-bold text-system-muted uppercase tracking-widest">${cat ? cat.name : 'Категория'}</span>
                ${svc.popular ? '' : ''}
            </div>
            <h1 class="text-3xl md:text-4xl font-black text-system-text mb-4">${svc.name}</h1>
            <div class="flex items-center justify-center md:justify-start gap-4 mb-4 text-sm text-system-muted">
                <div class="flex items-center gap-1"><span class="star">★</span> <span class="font-semibold text-system-text">${svc.rating}</span></div>
                <div>${svc.gender === 'male' ? '🧔 Для мужчин' : svc.gender === 'female' ? '👩 Для женщин' : '🚻 Для всех'}</div>
                <div>⏱ <span class="font-medium">${getDurationText(svc.duration)}</span></div>
                <div class="font-bold text-primary-600 text-lg">от ${formatPrice(svc.price)}</div>
            </div>
            <p class="text-system-muted leading-relaxed mb-6">${svc.description || 'Идеальная процедура для вашего преображения. Наши мастера используют только качественные материалы и профессиональный подход.'}</p>
            <div>
                <button onclick="openBookingForService(${svc.id})" class="btn-primary w-full md:w-auto px-8 py-3.5 rounded-2xl text-white font-bold text-sm">Записаться на процедуру</button>
            </div>
        </div>
    </div>
</div>

<div class="mb-8">
    <h2 class="text-2xl font-bold text-system-text mb-6">Эта услуга в других местах</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        ${offeringSalons.length > 0 || independentMasters.length > 0 ? `
            ${offeringSalons.map(salon => {
                const salonPrice = getSalonPrice(salon.id, svc.id, services, typeof master !== 'undefined' ? master.id : undefined);
                return `
                <div class="island-card border-none p-5 cart-hover cursor-pointer" onclick="openSalonDetail(${salon.id})">
                    <div class="flex justify-between items-start mb-3">
                        <h3 class="font-bold text-system-text">${salon.name} <span class="text-xs text-system-muted opacity-70 font-normal ml-1">Салон</span></h3>
                        <div class="flex items-center gap-1 text-sm"><span class="star">★</span><span class="font-semibold">${salon.rating}</span></div>
                    </div>
                    <div class="flex justify-between items-end mt-4">
                        <span class="text-sm text-system-muted">📍 ${salon.address}</span>
                        <span class="font-bold text-primary-600">${formatPrice(salonPrice)}</span>
                    </div>
                </div>`;
            }).join('')}
            ${independentMasters.map(master => {
                return `
                <div class="island-card border-none p-5 cart-hover cursor-pointer" onclick="openMasterDetail(${master.id})">
                    <div class="flex justify-between items-start mb-3">
                        <div class="flex items-center gap-3">
                            <img src="${master.avatar}" class="w-10 h-10 rounded-full object-cover">
                            <h3 class="font-bold text-system-text">${master.name} <span class="text-xs text-system-muted opacity-70 font-normal ml-1">Частный мастер</span></h3>
                        </div>
                        <div class="flex items-center gap-1 text-sm"><span class="star">★</span><span class="font-semibold">${master.rating}</span></div>
                    </div>
                    <div class="flex justify-between items-end mt-4">
                        <span class="text-sm text-system-muted">Выезд / На дому</span>
                        <span class="font-bold text-primary-600">${formatPrice(svc.price)}</span>
                    </div>
                </div>`;
            }).join('')}
        ` : `<p class="col-span-3 text-center text-system-muted py-10 bg-system-main rounded-2xl">Пока никто не оказывает эту услугу</p>`}
    </div>
</div>
${renderReviewsSection('service', svc.id)}
    </main>`;
}

window.renderServiceDetailPage = renderServiceDetailPage;

export function renderBookingsPage() {
    const myBookings = getUserBookings();
    
    // Add initial active tab if not set
    if (!state.clientBookingsTab) state.clientBookingsTab = 'active';

    const activeBookings = myBookings.filter(b => b.status === 'pending' || b.status === 'confirmed');
    const historyBookings = myBookings.filter(b => b.status === 'completed' || b.status === 'cancelled');

    const displayedBookings = state.clientBookingsTab === 'active' ? activeBookings : historyBookings;

    const renderBookingCard = (b, isActive) => {
        const svc = services.find(s => s.id === b.serviceId);
        const salon = salons.find(s => s.id === b.targetId);
        const statusColors = { pending: 'bg-yellow-100 text-yellow-700', confirmed: 'bg-green-100 text-green-700', completed: 'bg-blue-100 text-blue-700', cancelled: 'bg-red-100 text-red-700' };
        const statusLabels = { pending: 'Ожидает', confirmed: 'Подтверждена', completed: 'Завершена', cancelled: 'Отменена' };
        const isExpanded = state.expandedBooking === b.id;
        
        return `
        <div class="island-card border-none p-4 shadow-sm hover:shadow-md transition-shadow">
            <div class="flex justify-between items-center cursor-pointer" onclick="state.expandedBooking = state.expandedBooking === '${b.id}' ? null : '${b.id}'; render();">
                <div class="flex items-center gap-3">
                    <div class="w-10 h-10 rounded-full bg-primary-50 flex items-center justify-center text-lg shadow-inner">
                        ${svc ? '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line stroke-linecap="round" stroke-linejoin="round" x1="20" x2="8.12" y1="4" y2="15.88"/><line stroke-linecap="round" stroke-linejoin="round" x1="14.47" x2="14.48" y1="14.48" y2="14.48"/><line stroke-linecap="round" stroke-linejoin="round" x1="20" x2="8.12" y1="20" y2="8.12"/></svg>' : '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7h-3a2 2 0 0 1-2-2V2"/><path stroke-linecap="round" stroke-linejoin="round" d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2 2Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 15h6"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 18h6"/></svg>'}
                    </div>
                    <div>
                        <h3 class="font-bold text-system-text leading-none">${svc ? svc.name : 'Услуга'}</h3>
                        <p class="text-xs text-system-muted mt-1">${salon ? salon.name : 'Салон'}</p>
                    </div>
                </div>
                <div class="text-right">
                    <span class="inline-block badge ${statusColors[b.status]} text-[10px] px-2 py-0.5 rounded-md mb-1">${statusLabels[b.status]}</span>
                    <div class="text-xs text-system-text font-bold tracking-tighter">${b.date} · ${b.time}</div>
                </div>
            </div>
            
            ${isExpanded ? `
                <div class="mt-4 pt-4 border-t border-gray-50 text-sm">
                    <div class="flex justify-between mb-2">
                        <span class="text-system-muted">Стоимость:</span>
                        <span class="font-bold text-system-text">${svc ? formatPrice(getSalonPrice(b.targetId, svc.id, services, b.masterId)) : ''}</span>
                    </div>
                    ${b.clientComment ? `
                        <div class="bg-system-main rounded-xl p-3 my-3 border border-system-border/50">
                            <p class="text-xs font-bold text-system-muted opacity-70 uppercase mb-1">Комментарий:</p>
                            <p class="text-sm text-system-text italic">"${b.clientComment}"</p>
                        </div>
                    ` : ''}
                    <div class="flex gap-2 mt-4">
                        ${isActive ? `
                            <button onclick="editBooking('${b.id}')" class="flex-1 py-2 rounded-xl bg-gray-900 text-white font-bold text-xs hover:bg-gray-800 transition-colors">Изменить</button>
                            <button onclick="cancelBooking('${b.id}')" class="flex-1 py-2 rounded-xl border border-system-border text-system-muted font-bold text-xs hover:bg-red-50 hover:text-red-500 hover:border-red-100 transition-all">Отменить</button>
                        ` : `
                            <div class="text-xs text-system-muted opacity-70 font-medium w-full text-center py-2">Статус: ${statusLabels[b.status]}</div>
                        `}
                    </div>
                </div>
            ` : ''}
        </div>`;
    };

    return `
    <div class="island max-w-4xl mx-auto mt-6 mx-4 px-4 sm:px-8 animate-fade-in">
    <h1 class="text-3xl font-black text-system-text mb-6">Мои записи</h1>
    
    ${myBookings.length > 0 ? `
        <div class="flex gap-2 border-b border-system-border mb-6">
            <button onclick="state.clientBookingsTab='active'; render();" class="pb-3 px-2 text-sm font-bold border-b-2 ${state.clientBookingsTab === 'active' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Активные</button>
            <button onclick="state.clientBookingsTab='history'; render();" class="pb-3 px-2 text-sm font-bold border-b-2 ${state.clientBookingsTab === 'history' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">История</button>
        </div>
        
        ${displayedBookings.length > 0 ? `
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                ${displayedBookings.map(b => renderBookingCard(b, state.clientBookingsTab === 'active')).join('')}
            </div>
        ` : `
            <div class="text-center py-10 bg-system-main rounded-2xl border border-dashed border-system-border mt-4">
                <p class="text-system-muted">В этой категории нет записей</p>
            </div>
        `}
    ` : `
        <div class="text-center py-20 bg-system-surface rounded-[40px] border-2 border-dashed border-system-border/50">
            <div class="text-6xl mb-4"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg></div>
            <h3 class="text-xl font-bold text-system-text">У вас пока нет записей</h3>
            <p class="text-system-muted mt-2 mb-8">Найдите подходящую услугу и запишитесь онлайн</p>
            <button onclick="navigate('services')" class="btn-primary px-8 py-4 rounded-2xl text-white font-bold">Найти услуги</button>
        </div>
    `}
</div>`;
}

window.renderBookingsPage = renderBookingsPage;

export function renderReviewsSection(targetType, targetId) {
    const targetReviews = state.reviews.filter(r => r.targetType === targetType && r.targetId === targetId);
    const canReview = !!state.currentUser; // Just basic auth check
    
    return `
    <div class="mt-12 mb-8 animate-fade-in">
        <div class="flex items-center justify-between mb-6">
            <h2 class="text-2xl font-bold text-system-text">Отзывы (${targetReviews.length})</h2>
            ${canReview ? `<button onclick="state.reviewModalTarget = {type: '${targetType}', id: ${targetId}}; render();" class="text-sm font-bold text-primary-600 hover:text-primary-700 bg-primary-50 px-4 py-2 rounded-xl">Оставить отзыв</button>` : `<div class="text-sm text-system-muted"><button onclick="state.showAuthPage=true; render()" class="text-primary-600 font-bold hover:underline bg-transparent border-0 p-0 cursor-pointer">Войдите</button>, чтобы оставить отзыв</div>`}
        </div>
        ${targetReviews.length > 0 ? `
            <div class="space-y-4">
                ${targetReviews.map(r => `
                    <div class="island-card border-none p-5">
                        <div class="flex justify-between items-start mb-2">
                            <div class="font-bold text-system-text">${r.userName}</div>
                            <div class="flex items-center gap-2">
                                <div class="flex">${Array(5).fill(0).map((_, i) => `<span class="text-xs ${i < r.rating ? 'text-yellow-400' : 'text-gray-300'}">★</span>`).join('')}</div>
                                <span class="text-xs text-system-muted opacity-70">${r.date}</span>
                            </div>
                        </div>
                        <p class="text-system-text text-sm mt-2">${r.comment}</p>
                    </div>
                `).join('')}
            </div>
        ` : `
            <div class="text-center py-10 bg-system-main rounded-2xl border border-dashed border-system-border">
                <p class="text-system-muted">Пока нет отзывов. Станьте первым!</p>
            </div>
        `}
    </div>
    `;
}

window.renderReviewsSection = renderReviewsSection;

export function filterByCategory(catId) {
    state.activeCategory = state.activeCategory === catId ? null : catId;
    if (state.currentPage === 'home') { navigate('services'); state.activeCategory = catId; }
    render();
}

window.filterByCategory = filterByCategory;

export function performSearch() {
    const q = state.searchQuery.trim().toLowerCase();
    if (!q) return;
    if (services.some(s => s.name.toLowerCase().includes(q))) navigate('services');
    else if (salons.some(s => s.name.toLowerCase().includes(q))) navigate('salons');
    else if (masters.some(m => m.name.toLowerCase().includes(q) || m.specialty.toLowerCase().includes(q))) navigate('masters');
    else navigate('services');
    state.searchQuery = q;
    render();
}

window.performSearch = performSearch;

export function openSalonDetail(salonId) { 
    const salon = salons.find(s => s.id === salonId);
    if (salon && salon.theme) {
        ThemeManager.setTheme(salon.theme);
    }
    state.selectedSalon = salonId; 
    state.currentPage = 'salon-detail'; 
    window.scrollTo(0, 0); 
    render(); 
}

window.openSalonDetail = openSalonDetail;

export function openMasterDetail(masterId) { state.selectedMaster = masterId; state.currentPage = 'master-detail'; window.scrollTo(0, 0); render(); }

window.openMasterDetail = openMasterDetail;

export function openServiceDetail(serviceId) { state.selectedService = serviceId; state.currentPage = 'service-detail'; window.scrollTo(0, 0); render(); }

window.openServiceDetail = openServiceDetail;

export function selectService(serviceId) {
    state.bookingData.serviceId = serviceId;
    goToBookingStep(2);
};

window.selectService = selectService;

export function selectMaster(masterId) {
    state.bookingData.masterId = masterId;
    goToBookingStep(3);
};

window.selectMaster = selectMaster;

