// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { fillDemo, handleLogin, handleRegStep1, handleRegStep2, handleRegStep3, selectRole } from './actions.js';
import { renderThemeSwitcher } from '../../components/ui.js';
import { state, categories, services } from '../../state.js';

export function renderAuthPage() {
    if (state.authMode === 'roleSelect') {
        return renderRoleSelect();
    }
    return `
    <div class="min-h-screen hero-gradient flex items-center justify-center p-4 relative">
<div class="fixed top-4 right-4 flex items-center gap-3 z-50">
    ${renderThemeSwitcher()}
    <button onclick="state.showAuthPage=false; render()" class="w-10 h-10 bg-system-surface/50 backdrop-blur rounded-xl border border-system-border/20 flex items-center justify-center text-system-text hover:bg-system-surface text-lg transition-colors" title="Вернуться к каталогу">✕</button>
</div>
<div class="w-full max-w-md">
    <!-- Logo -->
    <div class="text-center mb-8 animate-fade-in">
        <div class="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-primary-600 flex items-center justify-center mx-auto mb-4 shadow-lg cursor-pointer" onclick="state.showAuthPage=false; render()">
            <span class="text-white text-3xl">✦</span>
        </div>
        <h1 class="text-3xl font-bold gradient-text">Suluu</h1>
        <p class="text-system-muted mt-2 text-sm">Маркетплейс beauty-услуг в Кыргызстане</p>
    </div>

    <div class="bg-system-surface rounded-3xl shadow-xl p-8 animate-slide-up">
        ${state.authMode === 'login' ? renderLoginForm() : renderRegisterForm()}
    </div>

    <!-- Demo accounts -->
    <div class="mt-6 bg-system-surface/60 rounded-2xl p-4 animate-fade-in" style="animation-delay: 0.2s">
        <p class="text-xs text-system-muted font-semibold mb-2 uppercase tracking-wide">Демо-аккаунты:</p>
        <div class="grid grid-cols-2 lg:grid-cols-3 gap-2 text-xs max-h-48 overflow-y-auto pr-1">
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('admin1')">
                <span class="font-semibold text-system-text">Супер Админ</span><br>
                <span class="text-system-muted opacity-70">+996 555 000 000</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('salon1')">
                <span class="font-semibold text-system-text">Suluu Luxe (Салон)</span><br>
                <span class="text-system-muted opacity-70">+996 555 111 111</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('salon2')">
                <span class="font-semibold text-system-text">Aura Beauty (Салон)</span><br>
                <span class="text-system-muted opacity-70">+996 555 111 222</span>
            </div>
             <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('manager1')">
                <span class="font-semibold text-system-text">Менеджер Suluu</span><br>
                <span class="text-system-muted opacity-70">+996 555 200 111</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('master1')">
                <span class="font-semibold text-system-text">Айпери (Мастер Suluu)</span><br>
                <span class="text-system-muted opacity-70">+996 700 111 111</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('master4')">
                <span class="font-semibold text-system-text">Диана (Мастер Aura)</span><br>
                <span class="text-system-muted opacity-70">+996 700 444 444</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('client1')">
                <span class="font-semibold text-system-text">Айбек (Клиент)</span><br>
                <span class="text-system-muted opacity-70">+996 550 123 456</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('client2')">
                <span class="font-semibold text-system-text">Мария (Клиент)</span><br>
                <span class="text-system-muted opacity-70">+996 550 111 222</span>
            </div>
            <div class="bg-system-main rounded-lg p-2 cursor-pointer hover:bg-primary-50 transition-colors" onclick="fillDemo('client3')">
                <span class="font-semibold text-system-text">Нурлан (Клиент)</span><br>
                <span class="text-system-muted opacity-70">+996 550 999 888</span>
            </div>
        </div>
        <p class="text-xs text-system-muted opacity-70 mt-2">Пароли: <b>admin123</b> / <b>salon123</b> / <b>master123</b> / <b>client123</b> / менеджер: <b>manager1</b></p>
    </div>
</div>
    </div>`;
}

window.renderAuthPage = renderAuthPage;

export function renderLoginForm() {
    return `
    <div class="text-center mb-6">
<h2 class="text-xl font-bold text-system-text">Вход в аккаунт</h2>
<p class="text-sm text-system-muted mt-1">Введите номер телефона и пароль</p>
    </div>

    ${state.authError ? `<div class="bg-red-50 border border-red-200 text-red-600 text-sm rounded-xl px-4 py-3 mb-4 animate-shake">${state.authError}</div>` : ''}

    <div class="space-y-4">
<div>
    <label class="block text-sm font-medium text-system-text mb-1.5">Номер телефона</label>
    <div class="relative">
        <span class="absolute left-3 top-1/2 -translate-y-1/2 text-system-muted opacity-70 text-sm">🇰🇬</span>
        <input type="tel" id="login-phone" placeholder="(___) ___ ___"
            class="auth-input w-full pl-10 pr-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
            value="${state.loginPhone || ''}" oninput="if(window.formatPhoneInput) window.formatPhoneInput(this); state.loginPhone=this.value">
    </div>
</div>
<div>
    <label class="block text-sm font-medium text-system-text mb-1.5">Пароль</label>
    <input type="password" id="login-password" placeholder="Введите пароль"
        class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
        value="${state.loginPassword}" oninput="state.loginPassword=this.value"
        onkeydown="if(event.key==='Enter')handleLogin()">
</div>
<button onclick="handleLogin()" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">
    Войти
</button>
    </div>

    <div class="mt-6 text-center">
<p class="text-sm text-system-muted">Нет аккаунта? <a href="#" onclick="state.authMode='register';state.authError='';render()" class="text-primary-500 font-semibold hover:underline">Зарегистрироваться</a></p>
    </div>`;
}

window.renderLoginForm = renderLoginForm;

export function renderRegisterForm() {
    if (state.regStep === 1) {
        return `
<div class="text-center mb-6">
    <h2 class="text-xl font-bold text-system-text">Регистрация</h2>
    <p class="text-sm text-system-muted mt-1">Шаг 1 из 3: Номер телефона и пароль</p>
</div>

${state.authError ? `<div class="bg-red-50 border border-red-200 text-red-600 text-sm rounded-xl px-4 py-3 mb-4 animate-shake">${state.authError}</div>` : ''}

<div class="space-y-4">
    <div>
        <label class="block text-sm font-medium text-system-text mb-1.5">Номер телефона *</label>
        <div class="relative">
            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-system-muted opacity-70 text-sm">🇰🇬</span>
            <input type="tel" id="reg-phone" placeholder="(___) ___ ___"
                class="auth-input w-full pl-10 pr-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
                value="${state.regPhone || ''}" oninput="if(window.formatPhoneInput) window.formatPhoneInput(this); state.regPhone=this.value">
        </div>
    </div>
    <div>
        <label class="block text-sm font-medium text-system-text mb-1.5">Пароль *</label>
        <input type="password" id="reg-password" placeholder="Минимум 6 символов"
            class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
            value="${state.regPassword}" oninput="state.regPassword=this.value">
    </div>
    <div>
        <label class="block text-sm font-medium text-system-text mb-1.5">Подтвердите пароль *</label>
        <input type="password" id="reg-password-confirm" placeholder="Повторите пароль"
            class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
            value="${state.regPasswordConfirm}" oninput="state.regPasswordConfirm=this.value"
            onkeydown="if(event.key==='Enter')handleRegStep1()">
    </div>
    <button onclick="handleRegStep1()" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">
        Далее
    </button>
</div>

<div class="mt-6 text-center">
    <p class="text-sm text-system-muted">Уже есть аккаунт? <a href="#" onclick="state.authMode='login';state.authError='';render()" class="text-primary-500 font-semibold hover:underline">Войти</a></p>
</div>`;
    }

    if (state.regStep === 2) {
        return `
<div class="text-center mb-6">
    <h2 class="text-xl font-bold text-system-text">Регистрация</h2>
    <p class="text-sm text-system-muted mt-1">Шаг 2 из 3: Личные данные</p>
</div>

<div class="space-y-4">
    <div>
        <label class="block text-sm font-medium text-system-text mb-1.5">Имя и фамилия *</label>
        <input type="text" id="reg-name" placeholder="Например: Айгул Токтоналиева"
            class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
            value="${state.regName || ''}" oninput="state.regName=this.value">
    </div>
    <div>
        <label class="block text-sm font-medium text-system-text mb-1.5">Email (необязательно)</label>
        <input type="email" id="reg-email" placeholder="email@example.kg"
            class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
            value="${state.regEmail || ''}" oninput="state.regEmail=this.value"
            onkeydown="if(event.key==='Enter')handleRegStep2()">
    </div>
    <div class="flex gap-3">
        <button onclick="state.regStep=1;render()" class="flex-1 py-3.5 rounded-2xl border-2 border-system-border text-system-text font-semibold text-sm hover:border-system-border transition-colors">
            Назад
        </button>
        <button onclick="handleRegStep2()" class="flex-1 btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">
            Далее
        </button>
    </div>
</div>`;
    }

    if (state.regStep === 3) {
        return `
<div class="text-center mb-6">
    <h2 class="text-xl font-bold text-system-text">Регистрация</h2>
    <p class="text-sm text-system-muted mt-1">Шаг 3 из 3: Выберите роль</p>
</div>

<div class="grid grid-cols-2 gap-3 mb-6">
    <div class="role-card border-2 rounded-2xl p-4 text-center ${state.regRole === 'client' ? 'selected border-primary-400' : 'border-system-border'}" onclick="state.regRole='client';render()">
        <div class="text-3xl mb-2">👤</div>
        <div class="font-semibold text-sm text-system-text">Клиент</div>
        <div class="text-xs text-system-muted opacity-70 mt-1">Искать услуги и записываться</div>
    </div>
    <div class="role-card border-2 rounded-2xl p-4 text-center ${state.regRole === 'master' ? 'selected border-primary-400' : 'border-system-border'}" onclick="state.regRole='master';render()">
        <div class="text-3xl mb-2">💇‍♀️</div>
        <div class="font-semibold text-sm text-system-text">Мастер</div>
        <div class="text-xs text-system-muted opacity-70 mt-1">Принимать клиентов</div>
    </div>
    <div class="role-card border-2 rounded-2xl p-4 text-center ${state.regRole === 'salon' ? 'selected border-primary-400' : 'border-system-border'}" onclick="state.regRole='salon';render()">
        <div class="text-3xl mb-2">🏢</div>
        <div class="font-semibold text-sm text-system-text">Салон</div>
        <div class="text-xs text-system-muted opacity-70 mt-1">Управлять салоном</div>
    </div>
    <div class="role-card border-2 rounded-2xl p-4 text-center opacity-50 cursor-not-allowed border-system-border">
        <div class="text-3xl mb-2">🛡️</div>
        <div class="font-semibold text-sm text-system-text">Супер-админ</div>
        <div class="text-xs text-system-muted opacity-70 mt-1">Только по приглашению</div>
    </div>
</div>

${state.regRole === 'salon' ? `
    <div class="space-y-3 mb-6 animate-slide-up">
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Вид организации *</label>
            <select id="reg-salon-type" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface font-medium text-system-text" onchange="state.regSalonType=this.value">
                <option value="Салон красоты" ${state.regSalonType === 'Салон красоты' ? 'selected' : ''}>Салон красоты</option>
                <option value="Барбер" ${state.regSalonType === 'Барбер' ? 'selected' : ''}>Барбер</option>
                <option value="Парикмахерская" ${state.regSalonType === 'Парикмахерская' ? 'selected' : ''}>Парикмахерская</option>
                <option value="СПА" ${state.regSalonType === 'СПА' ? 'selected' : ''}>СПА</option>
                <option value="Массажный салон" ${state.regSalonType === 'Массажный салон' ? 'selected' : ''}>Массажный салон</option>
                <option value="Лечебный салон" ${state.regSalonType === 'Лечебный салон' ? 'selected' : ''}>Лечебный салон</option>
            </select>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Название *</label>
            <input type="text" id="reg-salon-name" placeholder="Название вашей организации"
                class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
                value="${state.regSalonName || ''}" oninput="state.regSalonName=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Адрес *</label>
            <input type="text" id="reg-salon-address" placeholder="ул. Чуйкова, 168, Бишкек"
                class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
                value="${state.regSalonAddress || ''}" oninput="state.regSalonAddress=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Принимаемые категории</label>
            <div class="grid grid-cols-2 gap-2">
                ${categories.map(c => `
                <label class="flex items-center gap-2 text-sm cursor-pointer border p-2 rounded-xl transition-colors ${state.regSalonCategories?.includes(c.id) ? 'border-primary-500 bg-primary-50 text-system-text shadow-sm' : 'border-system-border hover:border-primary-300 text-system-muted'}">
                    <input type="checkbox" class="hidden" 
                        ${state.regSalonCategories?.includes(c.id) ? 'checked' : ''}
                        onchange="
                            state.regSalonCategories = state.regSalonCategories || [];
                            if(this.checked) state.regSalonCategories.push(${c.id});
                            else state.regSalonCategories = state.regSalonCategories.filter(id => id !== ${c.id});
                            window.render();
                        ">
                    <span class="text-lg">${c.icon}</span> <span class="font-bold">${c.name}</span>
                </label>
                `).join('')}
            </div>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Оказываемые услуги</label>
            <div class="grid grid-cols-1 gap-2 max-h-48 overflow-y-auto pr-1">
                ${services.filter(s => !(state.regSalonCategories?.length > 0) || state.regSalonCategories.includes(s.category)).map(s => `
                <label class="flex items-center gap-2 text-sm cursor-pointer border p-3 rounded-xl transition-colors shadow-sm ${state.regSalonServices?.includes(s.id) ? 'border-primary-500 bg-primary-50' : 'border-system-border hover:border-primary-300'}">
                    <input type="checkbox" class="hidden" 
                        ${state.regSalonServices?.includes(s.id) ? 'checked' : ''}
                        onchange="
                            state.regSalonServices = state.regSalonServices || [];
                            if(this.checked) state.regSalonServices.push(${s.id});
                            else state.regSalonServices = state.regSalonServices.filter(id => id !== ${s.id});
                            window.render();
                        ">
                    <div class="flex flex-col flex-1 gap-0.5">
                        <span class="font-bold text-system-text">${s.name}</span>
                        <span class="text-xs text-system-muted font-medium whitespace-nowrap overflow-hidden text-ellipsis w-64">${s.price} сом · ${s.duration} мин</span>
                    </div>
                    <div class="w-6 h-6 rounded-md border-2 flex flex-shrink-0 items-center justify-center transition-colors ${state.regSalonServices?.includes(s.id) ? 'bg-primary-500 border-primary-500 text-white' : 'border-system-muted bg-system-surface shadow-inner'}">
                        ${state.regSalonServices?.includes(s.id) ? '<svg class="w-3 h-3 font-bold" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M5 13l4 4L19 7"/></svg>' : ''}
                    </div>
                </label>
                `).join('')}
            </div>
            ${(!state.regSalonCategories || state.regSalonCategories.length === 0) ? '<p class="text-xs text-system-muted font-medium mt-2">💡 Выберите категории выше, чтобы отфильтровать список услуг.</p>' : ''}
        </div>
    </div>
` : ''}

${state.regRole === 'master' ? `
    <div class="space-y-3 mb-6">
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Специальность *</label>
            <input type="text" id="master-specialty" placeholder="Например: Стилист-колорист"
                class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
                value="${state.regMasterSpecialty || ''}" oninput="state.regMasterSpecialty=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Опыт работы (лет)</label>
            <input type="number" id="master-experience" placeholder="5"
                class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm"
                value="${state.regMasterExperience || ''}" oninput="state.regMasterExperience=this.value">
        </div>
    </div>
` : ''}

<div class="flex gap-3">
    <button onclick="state.regStep=2;render()" class="flex-1 py-3.5 rounded-2xl border-2 border-system-border text-system-text font-semibold text-sm hover:border-system-border transition-colors">
        Назад
    </button>
    <button onclick="handleRegStep3()" class="flex-1 btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">
        Зарегистрироваться
    </button>
</div>`;
    }
}

window.renderRegisterForm = renderRegisterForm;

export function renderRoleSelect() {
    return `
    <div class="min-h-screen hero-gradient flex items-center justify-center p-4 relative">
<div class="fixed top-4 right-4 flex items-center gap-3 z-50">
    ${renderThemeSwitcher()}
    <button onclick="state.showAuthPage=false; render()" class="w-10 h-10 bg-system-surface/50 backdrop-blur rounded-xl border border-system-border/20 flex items-center justify-center text-system-text hover:bg-system-surface text-lg transition-colors" title="Вернуться к каталогу">✕</button>
</div>
<div class="w-full max-w-lg">
    <div class="text-center mb-8 animate-fade-in">
        <div class="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-primary-600 flex items-center justify-center mx-auto mb-4 shadow-lg cursor-pointer" onclick="state.showAuthPage=false; render()">
            <span class="text-white text-3xl">✦</span>
        </div>
        <h1 class="text-2xl font-bold text-system-text">Добро пожаловать!</h1>
        <p class="text-system-muted mt-2">Выберите режим входа</p>
    </div>

    <div class="grid grid-cols-2 gap-4 animate-slide-up">
        <div class="role-card bg-system-surface rounded-2xl border-2 border-system-border p-6 text-center" onclick="selectRole('superadmin')">
            <div class="w-14 h-14 rounded-2xl bg-red-100 flex items-center justify-center mx-auto mb-3">
                <span class="text-2xl">🛡️</span>
            </div>
            <h3 class="font-bold text-system-text">Супер-админ</h3>
            <p class="text-xs text-system-muted opacity-70 mt-1">Управление платформой</p>
        </div>
        <div class="role-card bg-system-surface rounded-2xl border-2 border-system-border p-6 text-center" onclick="selectRole('salon')">
            <div class="w-14 h-14 rounded-2xl bg-blue-100 flex items-center justify-center mx-auto mb-3">
                <span class="text-2xl">🏢</span>
            </div>
            <h3 class="font-bold text-system-text">Салон</h3>
            <p class="text-xs text-system-muted opacity-70 mt-1">Управление салоном</p>
        </div>
        <div class="role-card bg-system-surface rounded-2xl border-2 border-system-border p-6 text-center" onclick="selectRole('master')">
            <div class="w-14 h-14 rounded-2xl bg-green-100 flex items-center justify-center mx-auto mb-3">
                <span class="text-2xl">💇‍♀️</span>
            </div>
            <h3 class="font-bold text-system-text">Мастер</h3>
            <p class="text-xs text-system-muted opacity-70 mt-1">Расписание и клиенты</p>
        </div>
        <div class="role-card bg-system-surface rounded-2xl border-2 border-system-border p-6 text-center" onclick="selectRole('client')">
            <div class="w-14 h-14 rounded-2xl bg-primary-100 flex items-center justify-center mx-auto mb-3">
                <span class="text-2xl">👤</span>
            </div>
            <h3 class="font-bold text-system-text">Клиент</h3>
            <p class="text-xs text-system-muted opacity-70 mt-1">Поиск и запись на услуги</p>
        </div>
    </div>

    <div class="mt-6 text-center">
        <a href="#" onclick="state.authMode='login';state.authError='';render()" class="text-sm text-system-muted hover:text-primary-500 transition-colors">← Вернуться ко входу</a>
    </div>
</div>
    </div>`;
}

window.renderRoleSelect = renderRoleSelect;

export function renderLoginPage() {
    return `
<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-purple-50 px-4 py-8">
    <div class="w-full max-w-[420px]">
        
        <!-- Заголовок и Логотип -->
        <div class="text-center mb-8 animate-fade-in">
            <div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-500 to-primary-500 text-white text-3xl mb-4 shadow-lg shadow-purple-200">✦</div>
            <h1 class="text-3xl font-bold text-primary-600 tracking-tight">Suluu</h1>
            <p class="text-system-muted mt-1 text-sm font-medium">Маркетплейс beauty-услуг в Кыргызстане</p>
        </div>
        
        <!-- Карточка логина -->
        <div class="bg-system-surface rounded-[32px] shadow-xl shadow-gray-200/50 p-8 mb-6 animate-slide-up">
            <div class="text-center mb-8">
                <h2 class="text-2xl font-bold text-system-text">Вход в аккаунт</h2>
                <p class="text-system-muted opacity-70 text-sm mt-1">Введите номер телефона и пароль</p>
            </div>

            <div class="space-y-5">
                <!-- Поле: Телефон -->
                <div>
                    <label class="block text-sm font-bold text-system-text mb-2">Номер телефона</label>
                    <div class="relative flex items-center">
                        <span class="absolute left-4 text-xs font-bold text-system-muted opacity-70">KG</span>
                        <input type="tel" id="loginPhoneInput" placeholder="+996 XXX XXX XXX" 
                               class="w-full pl-12 pr-4 py-3.5 rounded-xl border border-system-border focus:border-primary-500 focus:ring-2 focus:ring-primary-100 outline-none transition-all font-medium text-system-text"
                               value="${state.loginPhone}" oninput="state.loginPhone = this.value">
                    </div>
                </div>

                <!-- Поле: Пароль -->
                <div>
                    <label class="block text-sm font-bold text-system-text mb-2">Пароль</label>
                    <input type="password" id="loginPassInput" placeholder="Введите пароль" 
                           class="w-full px-4 py-3.5 rounded-xl border border-system-border focus:border-primary-500 focus:ring-2 focus:ring-primary-100 outline-none transition-all font-medium text-system-text"
                           value="${state.loginPassword}" oninput="state.loginPassword = this.value">
                </div>

                <!-- Ошибка -->
                ${state.authError ? `<p class="text-sm text-red-500 font-bold px-1 text-center">${state.authError}</p>` : ''}

                <!-- Кнопка Войти -->
                <button onclick="handleLogin()" class="w-full bg-primary-500 hover:bg-primary-600 py-4 rounded-2xl text-white font-bold text-lg transition-colors mt-2">Войти</button>
            </div>

            <!-- Ссылка на регистрацию -->
            <div class="text-center mt-6">
                <p class="text-sm text-system-muted font-medium">Нет аккаунта? <a href="#" onclick="state.authMode='register'; render()" class="text-primary-500 font-bold hover:underline">Зарегистрироваться</a></p>
            </div>
        </div>

        <!-- Блок демо-аккаунтов -->
        <div class="bg-system-main/80 rounded-[32px] p-6 animate-fade-in border border-system-border/50">
            <h3 class="text-xs font-bold text-system-muted uppercase tracking-widest mb-4">Демо-аккаунты</h3>
            
            <div class="grid grid-cols-2 gap-3 mb-4">
                <button onclick="fillDemo('0555000000', 'admin123')" class="text-left bg-system-surface p-3 rounded-xl border border-system-border/50 hover:border-primary-300 hover:shadow-sm transition-all">
                    <div class="text-sm font-bold text-system-text">Супер-админ</div>
                    <div class="text-xs text-system-muted opacity-70 mt-0.5">+996 555 000 000</div>
                </button>
                
                <button onclick="fillDemo('0555111111', 'salon123')" class="text-left bg-system-surface p-3 rounded-xl border border-system-border/50 hover:border-primary-300 hover:shadow-sm transition-all">
                    <div class="text-sm font-bold text-system-text">Салон</div>
                    <div class="text-xs text-system-muted opacity-70 mt-0.5">+996 555 111 111</div>
                </button>
                
                <button onclick="fillDemo('0700111111', 'master123')" class="text-left bg-system-surface p-3 rounded-xl border border-system-border/50 hover:border-primary-300 hover:shadow-sm transition-all">
                    <div class="text-sm font-bold text-system-text">Мастер</div>
                    <div class="text-xs text-system-muted opacity-70 mt-0.5">+996 700 111 111</div>
                </button>
                
                <button onclick="fillDemo('0550123456', 'client123')" class="text-left bg-system-surface p-3 rounded-xl border border-system-border/50 hover:border-primary-300 hover:shadow-sm transition-all">
                    <div class="text-sm font-bold text-system-text">Клиент</div>
                    <div class="text-xs text-system-muted opacity-70 mt-0.5">+996 550 123 456</div>
                </button>
            </div>
            
            <p class="text-[11px] text-system-muted opacity-70 font-medium text-center">Пароль: admin123 / salon123 / master123 / client123</p>
        </div>

    </div>
</div>`;
}

window.renderLoginPage = renderLoginPage;

