// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { state, salons, masters, services, timeSlots, users } from '../../state.js';
import { showToast, getSalonPrice, formatDate, validatePhone } from '../../utils.js';

export function goToBookingStep(step) {
    const bd = state.bookingData;
    
    // Валидация при движении ВПЕРЕД
    if (step > state.bookingStep) {
        if (state.bookingStep === 1 && !bd.serviceId) { showToast('Выберите услугу'); return; }
        if (state.bookingStep === 3 && !bd.date) { showToast('Выберите дату'); return; }
        if (state.bookingStep === 4 && !bd.time) { showToast('Выберите время'); return; }
    }

    // Если бронируем мастера напрямую, можно пропустить шаг 2 (выбор мастера)
    if (bd.type === 'master') {
        if (step === 2 && state.bookingStep === 1) step = 3; // От услуг сразу к календарю
        if (step === 2 && state.bookingStep === 3) step = 1; // Назад от календаря к услугам
    } else {
        // Если бронируем салон, мастер по умолчанию "Любой" (null), если еще не выбран
        if (step === 3 && state.bookingStep === 2 && bd.masterId === undefined) {
            bd.masterId = null;
        }
    }

    state.bookingStep = step;
    render();
}

window.goToBookingStep = goToBookingStep;

export function nextStepDefault() {
    const bd = state.bookingData;
    const step = state.bookingStep;
    
    if (step === 1) {
        if (!bd.serviceId) {
            let availableServices = [];
            if (bd.type === 'salon') {
                const salon = window.salons?.find(s => s.id === bd.targetId);
                if (salon) availableServices = window.services?.filter(s => salon.categories.includes(s.category)) || [];
            } else if (bd.type === 'master') {
                const master = window.masters?.find(m => m.id === bd.targetId);
                if (master) availableServices = window.services?.filter(s => master.services.includes(s.id)) || [];
            }
            if (availableServices.length > 0) bd.serviceId = availableServices[0].id;
        }
        if (bd.serviceId) goToBookingStep(step + (bd.type === 'master' ? 2 : 1));
        else { showToast('Нет доступных услуг'); return; }
    } else if (step === 2) {
        if (bd.masterId === undefined) bd.masterId = null;
        goToBookingStep(3);
    } else if (step === 3) {
        if (!bd.date) {
            bd.date = new Date();
            bd.date.setHours(0,0,0,0);
        }
        goToBookingStep(4);
    } else if (step === 4) {
        if (!bd.time) {
            const slots = window.timeSlots || [];
            if (slots.length > 0) bd.time = slots[0];
        }
        if (bd.time) goToBookingStep(5);
        else { showToast('Время не найдено'); return; }
    }
}

window.nextStepDefault = nextStepDefault;

export function submitBooking() {
    const bd = state.bookingData;
    const nameInput = document.getElementById('clientNameInput');
    if (nameInput) bd.clientName = nameInput.value;
    const phoneInput = document.getElementById('clientPhoneInput') || document.getElementById('bookingPhoneInput');
    if (phoneInput) bd.clientPhone = phoneInput.value;

    
    let phoneDigits = (bd.clientPhone || '').replace(/\D/g, '');
    let nameVal = (bd.clientName || '').trim();
    if (!nameVal || phoneDigits.length < 12) {
        showToast('Пожалуйста, заполните имя и корректный номер телефона');
        return;
    }

    if (bd.editingId) {
        // РЕЖИМ РЕДАКТИРОВАНИЯ
        const bIndex = state.bookings.findIndex(b => b.id === bd.editingId);
        if (bIndex !== -1) {
            state.bookings[bIndex] = {
                ...state.bookings[bIndex],
                serviceId: bd.serviceId,
                masterId: bd.masterId,
                date: formatDate(bd.date),
                time: bd.time,
                clientName: bd.clientName,
                clientPhone: bd.clientPhone,
                clientComment: bd.clientComment,
                status: 'pending' // Сбрасываем статус на проверку
            };
            showToast('Запись успешно обновлена!');
        }
    } else {
        // РЕЖИМ НОВОЙ ЗАПИСИ
        const booking = {
            id: generateId(),
            type: bd.type,
            targetId: bd.targetId,
            serviceId: bd.serviceId,
            masterId: bd.masterId,
            date: formatDate(bd.date),
            time: bd.time,
            clientName: bd.clientName,
            clientPhone: bd.clientPhone,
            clientComment: bd.clientComment,
            status: (state.currentUser && ['salon', 'master'].includes(state.currentUser.role)) ? 'confirmed' : 'pending',
            createdAt: new Date().toISOString(),
            clientUserId: (state.currentUser && state.currentUser.role === 'client') ? state.currentUser.id : null
        };
        
        if (!state.currentUser) {
            booking.trackingCode = Math.random().toString(36).substring(2, 8).toUpperCase();
        }
        
        state.bookings.push(booking);
        state.lastBooking = booking;
        
        // Save guest details
        if (!state.currentUser) {
            localStorage.setItem('guestClientName', bd.clientName);
            localStorage.setItem('guestClientPhone', bd.clientPhone);
            const gb = JSON.parse(localStorage.getItem('guestBookings') || '[]');
            gb.push(booking.id);
            localStorage.setItem('guestBookings', JSON.stringify(gb));
        }
    
    }
    
    // Go to success step instead of closing
    state.bookingStep = 6;
    
    render();
}

window.submitBooking = submitBooking;

export function closeBookingModal(event) {
    if (event && event.target !== event.currentTarget) return;
    state.bookingModal = false;
    state.bookingStep = 1;
    document.body.style.overflow = '';
    render();
}

window.closeBookingModal = closeBookingModal;

export function cancelBooking(bookingId) {
    const booking = state.bookings.find(b => b.id === bookingId);
    if (booking) { 
        booking.status = 'cancelled'; 
        showToast('Запись отменена'); 
        try {
            const gb = JSON.parse(localStorage.getItem('guestBookings')||'[]');
            const index = gb.findIndex(g => g.id === booking.id);
            if (index !== -1) {
                gb[index] = booking;
                localStorage.setItem('guestBookings', JSON.stringify(gb));
            }
        } catch(e){}
        render(); 
    }
}

window.cancelBooking = cancelBooking;

export function trackBooking() {
    const input = document.getElementById('trackingCodeInput');
    if (!input || !input.value.trim()) return showToast('Введите код отслеживания');
    const code = input.value.trim().toUpperCase();
    
    const booking = state.bookings.find(b => b.trackingCode === code);
    if (!booking) return showToast('Запись с таким кодом не найдена');
    
    state.trackModalTarget = booking;
    render();
}

window.trackBooking = trackBooking;

export function assignMasterToBooking(bookingId, masterId) {
    const booking = state.bookings.find(b => b.id === bookingId);
    if (booking) {
        booking.masterId = masterId ? parseInt(masterId) : null;
        showToast('Мастер назначен');
        render();
    }
}

window.assignMasterToBooking = assignMasterToBooking;

export function updateBookingTime(bookingId, newTime) {
    const booking = state.bookings.find(b => b.id === bookingId);
    if (booking) {
        booking.time = newTime;
        showToast('Время записи изменено');
        render();
    }
}

window.updateBookingTime = updateBookingTime;

export function handleTimelineDrop(event, newMasterId, newTime) {
    event.preventDefault();
    const bookingId = event.dataTransfer.getData('bookingId');
    const booking = state.bookings.find(b => b.id === bookingId);
    if (!booking) return;

    const newMaster = masters.find(m => m.id === newMasterId);
    if (!newMaster) return;

    // Валидация: мастер должен владеть услугой из записи
    if (booking.serviceId && !(newMaster.services || []).includes(booking.serviceId)) {
        const svc = services.find(s => s.id === booking.serviceId);
        showToast(`<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M18 6 6 18"/><path stroke-linecap="round" stroke-linejoin="round" d="m6 6 12 12"/></svg> ${newMaster.name} не выполняет услугу "${svc ? svc.name : ''}"`);
        return;
    }

    // Проверка конфликта: нет ли уже записи у мастера на это время
    const conflict = state.bookings.find(b => b.id !== bookingId && b.masterId === newMasterId && b.time === newTime && b.status !== 'cancelled');
    if (conflict) {
        showToast(`<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M18 6 6 18"/><path stroke-linecap="round" stroke-linejoin="round" d="m6 6 12 12"/></svg> У ${newMaster.name} уже есть запись на ${newTime}`);
        return;
    }

    booking.masterId = newMasterId;
    booking.time = newTime;
    showToast(`✓ Запись перемещена к ${newMaster.name} на ${newTime}`);
    render();
}

window.handleTimelineDrop = handleTimelineDrop;

export function editBooking(bookingId) {
    const booking = state.bookings.find(b => b.id === bookingId);
    if (!booking) return;

    state.bookingModal = true;
    state.bookingStep = 5; // Сразу на страницу подтверждения, но можно будет вернуться
    state.bookingData = {
        editingId: booking.id, // Сохраняем ID, чтобы знать, что мы редактируем
        type: booking.type,
        targetId: booking.targetId,
        serviceId: booking.serviceId,
        masterId: booking.masterId,
        date: new Date(booking.date.split('.').reverse().join('-')), // Конвертация обратно в Date
        time: booking.time,
        clientName: booking.clientName,
        clientPhone: booking.clientPhone,
        clientComment: booking.clientComment || ''
    };
    
    state._calYear = state.bookingData.date.getFullYear();
    state._calMonth = state.bookingData.date.getMonth();
    document.body.style.overflow = 'hidden';
    render();
}

window.editBooking = editBooking;

export function confirmBooking(bookingId) {
    const booking = state.bookings.find(b => b.id === bookingId);
    if (booking) { booking.status = 'confirmed'; showToast('Запись подтверждена!'); render(); }
}

window.confirmBooking = confirmBooking;

export function adminConfirmBooking(id) { const b = state.bookings.find(x => x.id === id); if (b) { b.status = 'confirmed'; showToast('Запись подтверждена'); render(); } }

window.adminConfirmBooking = adminConfirmBooking;

export function adminCancelBooking(id) { const b = state.bookings.find(x => x.id === id); if (b) { b.status = 'cancelled'; showToast('Запись отменена'); render(); } }

window.adminCancelBooking = adminCancelBooking;

export function salonConfirmBooking(id) { const b = state.bookings.find(x => x.id === id); if (b) { b.status = 'confirmed'; showToast('Запись подтверждена!'); render(); } }

window.salonConfirmBooking = salonConfirmBooking;

export function salonCancelBooking(id) { const b = state.bookings.find(x => x.id === id); if (b) { b.status = 'cancelled'; showToast('Запись отклонена'); render(); } }

window.salonCancelBooking = salonCancelBooking;

export function salonCompleteBooking(id) {
    const b = state.bookings.find(x => x.id === id);
    if (b && b.status === 'confirmed') {
        b.status = 'completed';
        showToast('Услуга успешно завершена');
        render();
    }
};

window.salonCompleteBooking = salonCompleteBooking;

export function openBookingForSalon(salonId) {
    state.bookingModal = true;
    state.bookingStep = 1;
    state.bookingData = { 
        type: 'salon', 
        targetId: salonId, 
        serviceId: null, 
        masterId: null,
        date: null, 
        time: null, 
        clientName: state.currentUser ? state.currentUser.name : (localStorage.getItem('guestClientName') || ''), 
        clientPhone: state.currentUser ? state.currentUser.phone : (localStorage.getItem('guestClientPhone') || '')
    };
    state._calYear = new Date().getFullYear();
    state._calMonth = new Date().getMonth();
    document.body.style.overflow = 'hidden';
    render();
}

window.openBookingForSalon = openBookingForSalon;

export function openBookingForMaster(masterId) {
    const master = masters.find(m => m.id === masterId);
    state.bookingModal = true;
    state.bookingStep = 1;
    state.bookingData = { 
        type: 'master', 
        targetId: masterId, 
        salonId: master ? master.salonId : null,
        serviceId: null, 
        masterId: masterId,
        date: null, 
        time: null, 
        clientName: state.currentUser ? state.currentUser.name : (localStorage.getItem('guestClientName') || ''), 
        clientPhone: state.currentUser ? state.currentUser.phone : (localStorage.getItem('guestClientPhone') || '')
    };
    state._calYear = new Date().getFullYear();
    state._calMonth = new Date().getMonth();
    document.body.style.overflow = 'hidden';
    render();
}

window.openBookingForMaster = openBookingForMaster;

export function openBookingForService(serviceId) {
    const svc = services.find(s => s.id === serviceId);
    if (!svc) return;
    const salon = salons.find(s => s.categories.includes(svc.category));
    if (salon) {
        window.openBookingForSalon(salon.id);
        state.bookingData.serviceId = serviceId;
        state.bookingStep = 2;
        render();
    } else {
        showToast('Услуга временно недоступна');
    }
}

window.openBookingForService = openBookingForService;

export function openBookingForServiceInSalon(serviceId, salonId) {
    window.openBookingForSalon(salonId);
    state.bookingData.serviceId = serviceId;
    state.bookingStep = 2; // Перекидываем сразу на выбор мастера
    render();
};

window.openBookingForServiceInSalon = openBookingForServiceInSalon;

export function openBookingForServiceWithMaster(serviceId, masterId) {
    window.openBookingForMaster(masterId);
    state.bookingData.serviceId = serviceId;
    state.bookingStep = 3; // Мастер уже известен, перекидываем сразу на выбор даты
    render();
};

window.openBookingForServiceWithMaster = openBookingForServiceWithMaster;

export function changeMonth(delta) {
    let m = (state._calMonth !== undefined ? state._calMonth : new Date().getMonth()) + delta;
    let y = state._calYear || new Date().getFullYear();
    if (m < 0) { m = 11; y--; }
    if (m > 11) { m = 0; y++; }
    state._calMonth = m;
    state._calYear = y;
    render();
}

window.changeMonth = changeMonth;

export function selectDate(year, month, day) { 
    state.bookingData.date = new Date(year, month, day); 
    state.bookingData.time = null; 
    render(); 
}

window.selectDate = selectDate;

export function getMonthName(m) {
    return ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][m];
}

window.getMonthName = getMonthName;

export function getDaysOfMonth(y, m) {
    const first = new Date(y, m, 1).getDay();
    const last = new Date(y, m + 1, 0).getDate();
    const days = [];
    const offset = first === 0 ? 6 : first - 1;
    for (let i = 0; i < offset; i++) days.push(null);
    for (let i = 1; i <= last; i++) days.push(i);
    return days;
}

window.getDaysOfMonth = getDaysOfMonth;

