// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { selectService, selectMaster } from '../../apps/client/pages.js';
import { goToBookingStep, submitBooking, closeBookingModal, changeMonth, selectDate, getMonthName, getDaysOfMonth } from './actions.js';
import { state, salons, masters, services, timeSlots, categories } from '../../state.js';
import { formatPrice, getSalonPrice, getDurationText, getSalonServices, formatDate, formatPhoneInput, showToast } from '../../utils.js';

export function renderBookingModal() {
    if (!state.bookingModal) return '';
    const step = state.bookingStep;
    return `
    <div class="fixed inset-0 z-[100] flex items-end sm:items-center justify-center sm:p-6 bg-black/40 backdrop-blur-sm" onclick="closeBookingModal(event)">
<div class="bg-system-surface w-full sm:max-w-lg rounded-t-[32px] sm:rounded-[32px] shadow-2xl overflow-hidden transform transition-all translate-y-0 animate-slide-up" onclick="event.stopPropagation()">
    <div class="w-12 h-1.5 bg-system-border rounded-full mx-auto mt-3 sm:hidden"></div>
    
    <div class="px-6 py-4 sm:py-5 border-b border-system-border flex items-center justify-between">
        <div>
            <h2 class="text-xl font-bold text-system-text">Запись на услугу</h2>
            <div class="flex gap-1 mt-1">
                ${[1, 2, 3, 4, 5].map(s => `<div class="h-1 w-8 rounded-full ${s <= step ? 'bg-primary-500' : 'bg-system-main'}"></div>`).join('')}
            </div>
        </div>
        <button onclick="closeBookingModal()" class="w-10 h-10 rounded-full bg-system-main flex items-center justify-center hover:bg-system-main transition-colors">
            <svg class="w-5 h-5 text-system-muted opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
    </div>
    <div class="p-6 max-h-[80vh] overflow-y-auto pb-[calc(1.5rem+env(safe-area-inset-bottom))]">
        ${renderBookingCurrentStep()}
    </div>
</div>
    </div>`;
}

window.renderBookingModal = renderBookingModal;

export function renderBookingCurrentStep() {
    switch(state.bookingStep) {
        case 1: return renderBookingStep1(); // Услуга
        case 2: return renderBookingStep2(); // Мастер
        case 3: return renderBookingStep3(); // Дата
        case 4: return renderBookingStep4(); // Время
        case 5: return renderBookingStep5(); // Итог
        case 6: return renderBookingStep6(); // Успех
        default: return renderBookingStep1();
    }
}

window.renderBookingCurrentStep = renderBookingCurrentStep;

export function renderBookingStep1() {
    const bd = state.bookingData;
    let availableServices = [];
    let priceTargetId = bd.targetId;

    let targetName = "";
    let targetSubtitle = "";

    if (bd.type === 'salon') {
        const salon = salons.find(s => s.id === bd.targetId);
        if (salon) {
            availableServices = getSalonServices(salon, services);
            targetName = salon.name;
            targetSubtitle = salon.address;
        }
    } else if (bd.type === 'master') {
        const master = masters.find(m => m.id === bd.targetId);
        if (master) {
            availableServices = services.filter(s => master.services.includes(s.id));
            if (master.salonId) {
                priceTargetId = master.salonId;
                const sln = salons.find(s => s.id === master.salonId);
                targetSubtitle = sln ? sln.name : '';
            } else {
                targetSubtitle = "На выезде";
            }
            targetName = master.name;
        }
    }
    
    const genderGroups = {
        female: 'Для женщин',
        male: 'Для мужчин',
        all: 'Универсальные'
    };
    
    // Группировка
    const grouped = {};
    availableServices.forEach(svc => {
        const g = svc.gender || 'all';
        if (!grouped[g]) grouped[g] = {};
        const cId = svc.category || 'other';
        if (!grouped[g][cId]) grouped[g][cId] = [];
        grouped[g][cId].push(svc);
    });

    return `
<div class="space-y-4 animate-fade-in">
    <div class="mb-4 bg-system-main rounded-2xl p-4">
        <h4 class="text-sm text-system-muted font-medium">Вы записываетесь к</h4>
        <p class="font-bold text-system-text text-lg mt-0.5">${targetName}</p>
        ${targetSubtitle ? `<p class="text-xs text-primary-500 mt-1">📍 ${targetSubtitle}</p>` : ''}
    </div>
    <h3 class="font-bold text-system-text text-lg mb-2">Выберите услугу</h3>
    <div class="space-y-6">
        ${Object.keys(grouped).length > 0 ? Object.keys(grouped).map(gKey => `
            <div>
                <h4 class="font-black text-xl text-system-text mb-4 border-b-2 border-system-border pb-2">${genderGroups[gKey] || gKey}</h4>
                <div class="space-y-5">
                    ${Object.keys(grouped[gKey]).map(cId => {
                        const cat = categories.find(c => String(c.id) === String(cId));
                        const catName = cat ? (cat.icon + ' ' + cat.name) : 'Другое';
                        return `
                        <div>
                            <h5 class="font-bold text-system-muted mb-3 flex items-center gap-2">
                                <span class="bg-system-main px-3 py-1 rounded-lg text-sm">${catName}</span>
                            </h5>
                            <div class="grid grid-cols-1 gap-3">
                                ${grouped[gKey][cId].map(svc => {
                                    const price = (bd.type === 'master' && !masters.find(m => m.id === bd.targetId).salonId) 
                                        ? svc.price 
                                        : getSalonPrice(priceTargetId, svc.id, services, state.bookingData.masterId);
                                    return `
                                    <div onclick="state.bookingData.serviceId = ${svc.id}; goToBookingStep(2)" 
                                         class="p-5 rounded-3xl border-2 cursor-pointer transition-all duration-300 hover:shadow-lg ${bd.serviceId === svc.id ? 'border-primary-500 bg-primary-50 ring-4 ring-primary-50' : 'border-system-border hover:border-primary-400'}">
                                        <div class="flex justify-between items-center">
                                            <span class="font-bold ${bd.serviceId === svc.id ? 'text-primary-500' : 'text-system-text'} text-lg">${svc.name}</span>
                                            <span class="text-xs text-system-muted font-medium ml-2 min-w-[70px]"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 22h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M5 2h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22"/><path stroke-linecap="round" stroke-linejoin="round" d="M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2"/></svg> ${svc.duration} мин</span>
                                            <span class="font-black text-primary-500 ml-auto whitespace-nowrap pl-2">${formatPrice(price)}</span>
                                        </div>
                                    </div>
                                    `;
                                }).join('')}
                            </div>
                        </div>
                        `;
                    }).join('')}
                </div>
            </div>
        `).join('') : '<p class="text-system-muted py-4">Нет доступных услуг</p>'}
    </div>
    <button onclick="nextStepDefault()" class="w-full py-4 rounded-2xl bg-primary-50 text-primary-500 font-bold hover:bg-primary-50 transition-colors mt-6">Далее →</button>
</div>`;
}

window.renderBookingStep1 = renderBookingStep1;

export function renderBookingStep2() {
    const bd = state.bookingData;
    const salonMasters = masters.filter(m => m.salonId === bd.targetId);

    return `
<div class="space-y-4 animate-fade-in">
    <h3 class="font-bold text-system-text text-lg">Выберите мастера</h3>
    <div class="grid grid-cols-1 gap-3">
        <div onclick="state.bookingData.masterId = null; goToBookingStep(3)" 
             class="p-5 rounded-3xl border-2 cursor-pointer transition-all duration-300 hover:shadow-lg ${bd.masterId === null ? 'border-primary-500 bg-primary-50 ring-4 ring-primary-50' : 'border-system-border hover:border-primary-400'}">
            <div class="flex items-center gap-4">
                <div class="w-12 h-12 rounded-2xl bg-system-main flex items-center justify-center text-2xl">🪄</div>
                <span class="font-bold ${bd.masterId === null ? 'text-primary-500' : 'text-system-text'}">Любой свободный мастер</span>
            </div>
        </div>
        ${salonMasters.map(m => `
            <div onclick="state.bookingData.masterId = ${m.id}; goToBookingStep(3)" 
                 class="p-5 rounded-3xl border-2 cursor-pointer transition-all duration-300 hover:shadow-lg ${bd.masterId === m.id ? 'border-primary-500 bg-primary-50 ring-4 ring-primary-50' : 'border-system-border hover:border-primary-400'}">
                <div class="flex items-center gap-4">
                    <img src="${m.avatar}" class="w-12 h-12 rounded-2xl object-cover shadow-sm">
                    <div>
                        <div class="font-bold ${bd.masterId === m.id ? 'text-primary-500' : 'text-system-text'}">${m.name}</div>
                        <div class="text-sm text-system-muted font-medium">${m.specialty}</div>
                    </div>
                </div>
            </div>
        `).join('')}
    </div>
    <div class="grid grid-cols-2 gap-2 mt-2">
        <button onclick="goToBookingStep(1)" class="w-full py-4 rounded-2xl border-2 border-system-border font-bold text-system-muted opacity-70 hover:bg-system-main transition-colors">← Назад</button>
        <button onclick="nextStepDefault()" class="w-full py-4 rounded-2xl bg-primary-50 text-primary-500 font-bold hover:bg-primary-50 transition-colors">Далее →</button>
    </div>
</div>`;
}

window.renderBookingStep2 = renderBookingStep2;

export function renderBookingStep3() {
    const bd = state.bookingData;
    const calYear = state._calYear || new Date().getFullYear();
    const calMonth = state._calMonth || new Date().getMonth();
    const days = getDaysOfMonth(calYear, calMonth);
    const today = new Date();
    const isCurrentMonth = today.getMonth() === calMonth && today.getFullYear() === calYear;

    return `
<div class="space-y-4 animate-fade-in">
    <h3 class="font-bold text-system-text text-lg">Выберите дату</h3>
    <div class="bg-system-main rounded-[32px] p-6 border border-system-border">
        <div class="flex items-center justify-between mb-6">
            <button onclick="changeMonth(-1)" class="w-10 h-10 flex items-center justify-center hover:bg-system-surface rounded-xl transition-all font-bold text-system-muted opacity-70">❮</button>
            <div class="flex flex-col items-center gap-1">
                <span class="font-black text-system-text tracking-tight">${getMonthName(calMonth)} ${calYear}</span>
                <span onclick="state._calMonth=new Date().getMonth(); state._calYear=new Date().getFullYear(); window.render();" class="text-xs font-bold text-primary-500 cursor-pointer hover:underline">Сегодня</span>
            </div>
            <button onclick="changeMonth(1)" class="w-10 h-10 flex items-center justify-center hover:bg-system-surface rounded-xl transition-all font-bold text-system-muted opacity-70">❯</button>
        </div>
        <div class="grid grid-cols-7 gap-2 text-center mb-4 text-[11px] font-black text-system-muted opacity-70 uppercase tracking-widest">
            <div>Пн</div><div>Вт</div><div>Ср</div><div>Чт</div><div>Пт</div><div>Сб</div><div>Вс</div>
        </div>
        <div class="grid grid-cols-7 gap-2">
            ${days.map(d => {
                if (!d) return '<div></div>';
                const dayDate = new Date(calYear, calMonth, d);
                const todayDate = new Date();
                const isPast = dayDate < new Date().setHours(0,0,0,0);
                const isSelected = bd.date && bd.date.getDate() === d && bd.date.getMonth() === calMonth && bd.date.getFullYear() === calYear;
                const isToday = d === todayDate.getDate() && calMonth === todayDate.getMonth() && calYear === todayDate.getFullYear();
                return `
                    <div onclick="${isPast ? '' : `selectDate(${calYear}, ${calMonth}, ${d}); goToBookingStep(4)`}" 
                         class="aspect-square flex items-center justify-center rounded-2xl text-sm font-bold cursor-pointer transition-all duration-200
                         ${isPast ? 'text-system-muted opacity-40 cursor-not-allowed' : isSelected ? 'bg-primary-500 text-system-surface shadow-lg shadow-primary-200 scale-110' : isToday ? 'bg-primary-50 text-primary-500 border-2 border-primary-400' : 'bg-system-surface hover:bg-primary-50 text-system-text shadow-sm border border-system-border'}">
                        ${d}
                    </div>`;
            }).join('')}
        </div>
    </div>
    <div class="grid grid-cols-2 gap-2 mt-2">
        <button onclick="goToBookingStep(2)" class="w-full py-4 rounded-2xl border-2 border-system-border font-bold text-system-muted opacity-70 hover:bg-system-main transition-colors">← Назад</button>
        <button onclick="nextStepDefault()" class="w-full py-4 rounded-2xl bg-primary-50 text-primary-500 font-bold hover:bg-primary-50 transition-colors">Далее →</button>
    </div>
</div>`;
}

window.renderBookingStep3 = renderBookingStep3;

export function renderBookingStep4() {
    const bd = state.bookingData;
    const slots = (window.timeSlots || []);

    const isSlotTaken = (t) => {
        if (!bd.date) return false;
        
        const d = bd.date.getDate();
        const m = bd.date.getMonth();
        const yy = bd.date.getFullYear();
        const dd = String(d).padStart(2, '0');
        const mm = String(m + 1).padStart(2, '0');
        
        const dateStrDB = `${dd}.${mm}.${yy}`;
        
        // formatDate fallback
        const monthsNames = ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'];
        const reqDate = d + ' ' + monthsNames[m];

        const todaysBookings = state.bookings.filter(b => 
            b.status !== 'cancelled' && (b.date === dateStrDB || b.date === reqDate) && b.time === t
        );

        if (bd.type === 'master') {
            return todaysBookings.some(b => b.masterId === bd.targetId);
        } else {
            if (bd.masterId) {
                return todaysBookings.some(b => b.masterId === bd.masterId);
            } else {
                const salonMasters = masters.filter(mas => mas.salonId === bd.targetId);
                if (salonMasters.length === 0) return false;
                const busyMasters = todaysBookings.filter(b => salonMasters.some(sm => sm.id === b.masterId));
                return busyMasters.length >= salonMasters.length;
            }
        }
    };

    return `
<div class="space-y-4 animate-fade-in">
    <h3 class="font-bold text-system-text text-lg">Выберите время</h3>
    <p class="text-sm font-medium text-primary-500 bg-primary-50 py-2 px-4 rounded-xl inline-block"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg> ${bd.date ? formatDate(bd.date) : ''}</p>
    <div class="grid grid-cols-4 gap-3">
        ${slots.length > 0 ? slots.map(t => {
            const unavailable = isSlotTaken(t);
            if (unavailable) {
                return `
                <div class="py-4 rounded-2xl border-2 border-system-border text-center text-sm font-black cursor-not-allowed bg-system-main text-system-muted opacity-40">
                    ${t}
                </div>`;
            }
            return `
            <div onclick="state.bookingData.time = '${t}'; goToBookingStep(5)" 
                 class="py-4 rounded-2xl border-2 text-center text-sm font-black cursor-pointer transition-all duration-200
                 ${bd.time === t ? 'border-primary-500 bg-primary-50 text-primary-500 shadow-inner' : 'bg-system-surface border-system-border hover:border-primary-400 text-system-muted shadow-sm'}">
                ${t}
            </div>`;
        }).join('') : '<p class="col-span-4 text-center text-system-muted opacity-70 py-4 font-bold">Слоты времени не найдены</p>'}
    </div>
    <div class="grid grid-cols-2 gap-2 mt-2">
        <button onclick="goToBookingStep(3)" class="w-full py-4 rounded-2xl border-2 border-system-border font-bold text-system-muted opacity-70 hover:bg-system-main transition-colors">← Назад</button>
        <button onclick="nextStepDefault()" class="w-full py-4 rounded-2xl bg-primary-50 text-primary-500 font-bold hover:bg-primary-50 transition-colors">Далее →</button>
    </div>
</div>`;
}

window.renderBookingStep4 = renderBookingStep4;

export function renderBookingStep5() {
    const bd = state.bookingData;
    const svc = services.find(s => s.id === bd.serviceId);
    
    // Определяем целевой объект в зависимости от типа (салон или мастер)
    const target = bd.type === 'salon' 
        ? salons.find(s => s.id === bd.targetId) 
        : masters.find(m => m.id === bd.targetId);

    // Определяем мастера
    const master = bd.type === 'master' 
        ? target 
        : (bd.masterId ? masters.find(m => m.id === bd.masterId) : null);

    // Определяем название локации и итоговую цену
    let placeName = '';
    let price = 0;

    if (bd.type === 'salon') {
        placeName = target ? target.name : 'Салон не найден';
        price = getSalonPrice(bd.targetId, bd.serviceId, services, state.bookingData.masterId);
    } else {
        // Если это запись напрямую к мастеру
        if (target && target.salonId) {
            // Мастер привязан к салону
            const salon = salons.find(s => s.id === target.salonId);
            placeName = salon ? salon.name : 'На выезде';
            price = getSalonPrice(target.salonId, bd.serviceId, services, state.bookingData.masterId);
        } else {
            // Независимый мастер
            placeName = 'На выезде / Частный мастер';
            price = svc ? svc.price : 0;
        }
    }

    return `
<div class="space-y-6 animate-fade-in">
    <div class="bg-system-surface border-2 border-system-border rounded-[32px] p-6 text-system-text shadow-xl relative overflow-hidden">
        <div class="absolute top-0 right-0 p-8 opacity-10 text-6xl text-primary-500">✦</div>
        <h3 class="font-bold text-xl mb-4">Итог записи</h3>
        <div class="space-y-3">
            <div class="flex justify-between items-center text-sm"><span class="text-system-muted font-medium">Услуга</span><span class="font-bold">${svc ? svc.name : ''}</span></div>
            <div class="flex justify-between items-center text-sm"><span class="text-system-muted font-medium">${bd.type === 'salon' ? 'Салон' : 'Локация'}</span><span class="font-bold">${placeName}</span></div>
            <div class="flex justify-between items-center text-sm"><span class="text-system-muted font-medium">Мастер</span><span class="font-bold text-primary-500">${master ? master.name : 'Любой свободный'}</span></div>
            <div class="flex justify-between items-center text-sm"><span class="text-system-muted font-medium">Дата и время</span><span class="font-bold">${bd.date ? formatDate(bd.date) : ''} в ${bd.time}</span></div>
        </div>
        <div class="mt-6 pt-6 border-t border-system-border flex justify-between items-center">
            <span class="text-system-muted font-bold uppercase tracking-widest text-[10px]">К оплате</span>
            <span class="text-3xl font-black text-primary-500">${formatPrice(price)}</span>
        </div>
    </div>
    
    <div class="space-y-4">
        ${!state.currentUser ? `
        <div class="bg-primary-50 border border-primary-100 rounded-2xl p-4 flex items-start gap-3">
            <span class="text-xl mt-0.5">🎁</span>
            <div>
                <p class="text-sm font-bold text-system-text">Вы не авторизованы</p>
                <p class="text-xs text-system-muted mt-1"><button onclick="state.showAuthPage=true; render()" class="text-primary-500 font-semibold hover:underline bg-transparent border-none p-0 cursor-pointer text-left">Войдите или зарегистрируйтесь</button>, чтобы смотреть историю своих визитов и копить бонусы!</p>
            </div>
        </div>
        ` : ''}
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <input type="text" id="clientNameInput" placeholder="Ваше имя" class="w-full px-5 py-4 rounded-2xl border-2 border-system-border focus:border-primary-400 outline-none transition-all font-medium text-base sm:text-sm bg-system-surface text-system-text" 
                   value="${bd.clientName || ''}" oninput="state.bookingData.clientName = this.value">
            <input type="tel" id="clientPhoneInput" placeholder="(+996) ___ ___ ___" oninput="formatPhoneInput(this); state.bookingData.clientPhone = this.value" class="w-full px-5 py-4 rounded-2xl border-2 border-system-border focus:border-primary-400 outline-none transition-all font-medium text-base sm:text-sm bg-system-surface text-system-text"
                   value="${bd.clientPhone || ''}" >
        </div>
        <textarea placeholder="Комментарий к записи (необязательно)" class="w-full px-5 py-4 rounded-2xl border-2 border-system-border focus:border-primary-400 outline-none transition-all font-medium text-base sm:text-sm resize-none bg-system-surface text-system-text"
                  rows="3" oninput="state.bookingData.clientComment = this.value">${bd.clientComment || ''}</textarea>
    </div>

    <div class="flex gap-3">
        <button onclick="goToBookingStep(4)" class="flex-1 py-4 rounded-2xl border-2 border-system-border font-bold text-system-muted opacity-70 hover:bg-system-main transition-colors">Назад</button>
        <button onclick="submitBooking()" class="flex-2 btn-primary py-4 px-8 rounded-2xl text-system-surface font-bold shadow-lg shadow-primary-200 transform transition hover:scale-[1.02] active:scale-95">Подтвердить запись</button>
    </div>
</div>`;
}

window.renderBookingStep5 = renderBookingStep5;

export function renderBookingStep6() {
    const booking = state.lastBooking;
    if (!booking) return '<div class="text-center py-10">Ошибка: Запись не найдена.</div>';
    
    const isGuest = !!booking.trackingCode;

    return `
<div class="text-center py-6 animate-scale-in">
    <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6 text-green-500">
        <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"></path></svg>
    </div>
    <h2 class="text-2xl font-bold text-system-text mb-2">Запись успешно создана!</h2>
    <p class="text-system-muted mb-8">Ждем вас в назначенное время.</p>
    
    ${isGuest ? `
    <div class="bg-system-main border border-system-border rounded-2xl p-6 text-left mb-8 shadow-sm relative overflow-hidden">
        <div class="absolute -right-6 -top-6 w-24 h-24 bg-primary-100 rounded-full opacity-50 blur-xl"></div>
        
        <h3 class="text-sm font-bold text-system-text mb-4 flex items-center gap-2">
            <span class="text-primary-500">📌</span> Ваш код для отслеживания:
        </h3>
        
        <div class="bg-system-surface border-2 border-dashed border-primary-200 rounded-xl p-4 flex items-center justify-between">
            <span class="text-2xl font-mono font-bold text-primary-500 tracking-widest">${booking.trackingCode}</span>
            <button onclick="navigator.clipboard.writeText('${booking.trackingCode}'); showToast('Код скопирован!');" class="text-system-muted opacity-70 hover:text-primary-500 transition-colors" title="Скопировать код">
                <svg class="w-6 h-6 outline-none" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path></svg>
            </button>
        </div>
        
        <p class="text-xs text-system-muted mt-4 leading-relaxed">
            Сохраните этот код. С его помощью вы сможете проверить статус вашей записи или отменить её в разделе <strong class="text-system-text font-semibold text-[13px]">«Проверить статус записи»</strong> на главной странице.
        </p>
        
        <div class="mt-5 pt-5 border-t border-system-border flex flex-col gap-3">
            <p class="text-sm text-system-muted font-medium">Чтобы не потерять запись и копить бонусы:</p>
            <button onclick="closeBookingModal(); setTimeout(() => { state.showAuthPage=true; render(); }, 300)" class="w-full bg-primary-100 text-primary-500 py-3 rounded-xl font-bold text-sm hover:bg-primary-200 transition-colors">
                Зарегистрироваться
            </button>
        </div>
    </div>
    ` : `
    <div class="bg-system-main border border-system-border rounded-2xl p-6 text-left mb-8 shadow-sm">
        <p class="text-system-muted text-sm">Вы можете посмотреть статус этой и других записей в своем профиле, в разделе "Записи".</p>
    </div>
    `}
    
    <button onclick="closeBookingModal(null, true)" class="w-full py-4 rounded-2xl bg-system-main font-bold text-system-text hover:bg-system-border transition-colors">Отлично</button>
</div>`;
}

window.renderBookingStep6 = renderBookingStep6;

export function renderBookingModalOld() {
    return `
    <div class="fixed inset-0 z-50 flex items-end sm:items-center justify-center modal-overlay" onclick="closeBookingModal(event)">
<div class="bg-system-surface w-full sm:max-w-lg sm:rounded-3xl rounded-t-3xl max-h-[90vh] overflow-y-auto animate-slide-up" onclick="event.stopPropagation()">
    <div class="sticky top-0 bg-system-surface border-b border-system-border px-6 py-4 flex items-center justify-between rounded-t-3xl z-10">
        <h2 class="text-lg font-bold text-system-text">
            ${state.bookingStep === 1 ? 'Выберите услугу' : state.bookingStep === 2 ? 'Выберите дату и время' : state.bookingStep === 3 ? 'Подтверждение записи' : 'Запись оформлена'}
        </h2>
        <button onclick="closeBookingModal()" class="w-8 h-8 rounded-full bg-system-main flex items-center justify-center hover:bg-system-border transition-colors">
            <svg class="w-4 h-4 text-system-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
    </div>
    ${state.bookingStep < 4 ? `
    <div class="px-6 py-4 flex items-center gap-2">
        <div class="step-indicator ${state.bookingStep >= 1 ? 'active' : 'pending'}">1</div>
        <div class="step-line ${state.bookingStep >= 2 ? 'active' : ''}"></div>
        <div class="step-indicator ${state.bookingStep >= 2 ? 'active' : 'pending'}">2</div>
        <div class="step-line ${state.bookingStep >= 3 ? 'active' : ''}"></div>
        <div class="step-indicator ${state.bookingStep >= 3 ? 'active' : 'pending'}">3</div>
    </div>` : ''}
    <div class="px-6 pb-6">
        ${state.bookingStep === 1 ? renderBookingStep1() : state.bookingStep === 2 ? renderBookingStep2() : state.bookingStep === 3 ? renderBookingStep3() : renderBookingStep4()}
    </div>
</div>
    </div>`;
}

window.renderBookingModalOld = renderBookingModalOld;

export function renderBookingStep1Old() {
    const bd = state.bookingData;
    let availableServices = [];
    if (bd.type === 'salon') {
        const salon = salons.find(s => s.id === bd.targetId);
        if (salon) availableServices = getSalonServices(salon, services);
    } else if (bd.type === 'master') {
        const master = masters.find(m => m.id === bd.targetId);
        if (master) availableServices = services.filter(s => master.services.includes(s.id));
    }
    const target = bd.type === 'salon' ? salons.find(s => s.id === bd.targetId) : masters.find(m => m.id === bd.targetId);

    return `
${target ? `<div class="flex items-center gap-3 mb-5 p-3 bg-primary-50 rounded-xl">
    ${bd.type === 'salon' ? '<span class="text-2xl"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 6h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 10h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 14h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 18h4"/></svg></span>' : `<img src="${target.avatar}" class="w-10 h-10 rounded-full">`}
    <div><p class="text-sm font-semibold text-system-text">${target.name}</p><p class="text-xs text-system-muted">${bd.type === 'salon' ? 'Салон красоты' : target.specialty}</p></div>
</div>` : ''}
<div class="space-y-2">
    ${availableServices.map(svc => `
        <div class="flex items-center justify-between p-4 rounded-xl border-2 cursor-pointer transition-all ${bd.serviceId === svc.id ? 'border-primary-400 bg-primary-50' : 'border-system-border hover:border-primary-400'}"
             onclick="selectService(${svc.id})">
            <div><h4 class="font-medium text-system-text">${svc.name}</h4><p class="text-xs text-system-muted opacity-70 mt-0.5">${getDurationText(svc.duration)} · <span class="star text-xs">★</span> ${svc.rating}</p></div>
            <p class="font-bold text-system-text">${formatPrice(svc.price)}</p>
        </div>
    `).join('')}
</div>
${availableServices.length === 0 ? '<p class="text-center text-system-muted opacity-70 py-8">Нет доступных услуг</p>' : ''}
<button onclick="goToBookingStep(2)" class="w-full btn-primary py-3.5 rounded-2xl text-system-surface font-semibold mt-5 ${!bd.serviceId ? 'opacity-50 cursor-not-allowed' : ''}" ${!bd.serviceId ? 'disabled' : ''}>Далее</button>`;
}

window.renderBookingStep1Old = renderBookingStep1Old;

export function renderBookingStep2Old() {
    const bd = state.bookingData;
    if (bd.type !== 'salon') return renderBookingStep3();
    const salon = salons.find(s => s.id === bd.targetId);
    const svc = services.find(s => s.id === bd.serviceId);
    const salonMasters = masters.filter(m => m.salonId === bd.targetId && m.available && (!svc || m.services.includes(svc.id)));
    return `
<div class="mb-4 p-3 bg-primary-50 rounded-xl">
    <p class="text-sm font-semibold text-system-text">${svc ? svc.name : ''}</p>
    <p class="text-xs text-system-muted">${salon ? salon.name : ''}</p>
</div>
<div class="space-y-2">
    <div class="flex items-center gap-3 p-4 rounded-xl border-2 cursor-pointer transition-all ${bd.masterId === null ? 'border-primary-400 bg-primary-50' : 'border-system-border hover:border-primary-400'}"
         onclick="selectMaster(null)">
        <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary-400 to-purple-500 flex items-center justify-center text-system-surface text-lg">✦</div>
        <div><h4 class="font-medium text-system-text">Любой мастер</h4><p class="text-xs text-system-muted opacity-70">Салон назначит свободного мастера</p></div>
    </div>
    ${salonMasters.map(m => `
        <div class="flex items-center gap-3 p-4 rounded-xl border-2 cursor-pointer transition-all ${bd.masterId === m.id ? 'border-primary-400 bg-primary-50' : 'border-system-border hover:border-primary-400'}"
             onclick="selectMaster(${m.id})">
            <img src="${m.avatar}" class="w-10 h-10 rounded-full">
            <div class="flex-1">
                <h4 class="font-medium text-system-text">${m.name}</h4>
                <p class="text-xs text-system-muted opacity-70">${m.specialty} · <span class="star text-xs">★</span> ${m.rating}</p>
            </div>
        </div>
    `).join('')}
</div>
${salonMasters.length === 0 ? '<p class="text-sm text-system-muted opacity-70 mt-3">Нет мастеров для этой услуги. Будет назначен свободный мастер.</p>' : ''}
<div class="flex gap-3 mt-5">
    <button onclick="goToBookingStep(1)" class="flex-1 py-3.5 rounded-2xl border-2 border-system-border text-system-text font-semibold hover:border-system-text transition-colors">Назад</button>
    <button onclick="goToBookingStep(3)" class="flex-1 btn-primary py-3.5 rounded-2xl text-system-surface font-semibold">Далее</button>
</div>`;
}

window.renderBookingStep2Old = renderBookingStep2Old;

export function renderBookingStep3Old() {
    const now = new Date();
    const calYear = state._calYear || now.getFullYear();
    const calMonth = state._calMonth !== undefined ? state._calMonth : now.getMonth();
    const days = getDaysOfMonth(calYear, calMonth);
    const today = now.getDate();
    const isCurrentMonth = calYear === now.getFullYear() && calMonth === now.getMonth();
    const bd = state.bookingData;
    const svc = services.find(s => s.id === bd.serviceId);
    const unavailableSlots = timeSlots.filter(() => Math.random() < 0.25);

    return `
${svc ? `<div class="flex items-center justify-between p-3 bg-primary-50 rounded-xl mb-5">
    <div><p class="text-sm font-semibold text-system-text">${svc.name}</p><p class="text-xs text-system-muted">${getDurationText(svc.duration)}</p></div>
    <p class="font-bold text-system-text">${formatPrice(svc.price)}</p>
</div>` : ''}
<div class="mb-5">
    <div class="flex items-center justify-between mb-3">
        <button onclick="changeMonth(-1)" class="w-8 h-8 rounded-full bg-system-main flex items-center justify-center hover:bg-system-border transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
        </button>
        <h3 class="font-semibold text-system-text">${getMonthName(calMonth)} ${calYear}</h3>
        <button onclick="changeMonth(1)" class="w-8 h-8 rounded-full bg-system-main flex items-center justify-center hover:bg-system-border transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
        </button>
    </div>
    <div class="grid grid-cols-7 gap-1 mb-2">
        ${['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'].map(d => `<div class="text-center text-xs text-system-muted font-medium py-1">${d}</div>`).join('')}
    </div>
    <div class="grid grid-cols-7 gap-1">
        ${days.map(d => {
        if (!d) return '<div></div>';
        const isPast = isCurrentMonth && d < today;
        const isSelected = bd.date && bd.date.getDate() === d && bd.date.getMonth() === calMonth;
        const isToday = isCurrentMonth && d === today;
        return `<div class="calendar-day ${isPast ? 'disabled' : ''} ${isSelected ? 'selected' : ''} ${isToday ? 'today' : ''}"
                        onclick="${isPast ? '' : `selectDate(${calYear},${calMonth},${d})`}">${d}</div>`;
    }).join('')}
    </div>
</div>
${bd.date ? `
    <div class="mb-5">
        <h4 class="text-sm font-semibold text-system-text mb-3">Доступное время на ${formatDate(bd.date)}</h4>
        <div class="grid grid-cols-4 gap-2">
            ${timeSlots.map(t => {
        const isUnavailable = unavailableSlots.includes(t);
        const isSelected = bd.time === t;
        return `<div class="time-slot text-center py-2.5 rounded-xl border text-sm font-medium cursor-pointer ${isUnavailable ? 'border-system-border text-system-muted cursor-not-allowed bg-system-main' : isSelected ? 'selected' : 'border-system-border text-system-text hover:border-primary-300'}"
                            onclick="${isUnavailable ? '' : `selectTime('${t}')`}">${t}</div>`;
    }).join('')}
        </div>
    </div>
` : ''}
<div class="flex gap-3">
    <button onclick="goToBookingStep(2)" class="flex-1 py-3.5 rounded-2xl border-2 border-system-border text-system-text font-semibold hover:border-system-text transition-colors">Назад</button>
    <button onclick="goToBookingStep(4)" class="flex-1 btn-primary py-3.5 rounded-2xl text-system-surface font-semibold ${(!bd.date || !bd.time) ? 'opacity-50 cursor-not-allowed' : ''}" ${(!bd.date || !bd.time) ? 'disabled' : ''}>Далее</button>
</div>`;
}

window.renderBookingStep3Old = renderBookingStep3Old;

export function renderBookingStep4Old() {
    const bd = state.bookingData;
    const svc = services.find(s => s.id === bd.serviceId);
    const target = bd.type === 'salon' ? salons.find(s => s.id === bd.targetId) : masters.find(m => m.id === bd.targetId);
    const master = bd.masterId ? masters.find(m => m.id === bd.masterId) : null;
    const price = bd.type === 'salon' ? getSalonPrice(bd.targetId, bd.serviceId, services, state.bookingData.masterId) : svc.price;

    return `
<div class="space-y-4">
    <div class="bg-system-main rounded-2xl p-5 space-y-3">
        <h3 class="font-semibold text-system-text">Детали записи</h3>
        <div class="flex justify-between text-sm"><span class="text-system-muted">Услуга</span><span class="font-medium text-system-text">${svc ? svc.name : ''}</span></div>
        <div class="flex justify-between text-sm"><span class="text-system-muted">${bd.type === 'salon' ? 'Салон' : 'Мастер'}</span><span class="font-medium text-system-text">${target ? target.name : ''}</span></div>
        ${master ? `<div class="flex justify-between text-sm"><span class="text-system-muted">Мастер</span><span class="font-medium text-system-text">${master.name}</span></div>` : bd.type === 'salon' ? `<div class="flex justify-between text-sm"><span class="text-system-muted">Мастер</span><span class="font-medium text-system-text text-primary-500 font-semibold">Любой мастер</span></div>` : ''}
        <div class="flex justify-between text-sm"><span class="text-system-muted">Дата</span><span class="font-medium text-system-text">${bd.date ? formatDate(bd.date) : ''}</span></div>
        <div class="flex justify-between text-sm"><span class="text-system-muted">Время</span><span class="font-medium text-system-text">${bd.time}</span></div>
        <div class="flex justify-between text-sm"><span class="text-system-muted">Длительность</span><span class="font-medium text-system-text">${svc ? getDurationText(svc.duration) : ''}</span></div>
        <div class="border-t border-system-border pt-3 flex justify-between"><span class="font-semibold text-system-text">Итого</span><span class="font-bold text-lg text-system-text">${formatPrice(price)}</span></div>
    </div>
    <div class="space-y-3">
        <h3 class="font-semibold text-system-text">Ваши данные</h3>
        <input type="text" id="clientNameInput" placeholder="Ваше имя" class="w-full px-4 py-3 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm"
            value="${bd.clientName}" oninput="state.bookingData.clientName=this.value">
        <input type="tel" id="bookingPhoneInput" placeholder="+996 ___ ___ ___" oninput="formatPhoneInput(this); state.bookingData.clientPhone=this.value" class="w-full px-4 py-3 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm"
            value="${bd.clientPhone}" >
        <textarea placeholder="Комментарий (необязательно)" rows="2" class="w-full px-4 py-3 rounded-xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-base sm:text-sm resize-none"
            oninput="state.bookingData.clientComment=this.value">${bd.clientComment}</textarea>
    </div>
    <div class="flex gap-3">
        <button onclick="goToBookingStep(3)" class="flex-1 py-3.5 rounded-2xl border-2 border-system-border text-system-text font-semibold hover:border-system-text transition-colors">Назад</button>
        <button onclick="submitBooking()" class="flex-1 btn-primary py-3.5 rounded-2xl text-system-surface font-semibold">Подтвердить запись</button>
    </div>
</div>`;
}

window.renderBookingStep4Old = renderBookingStep4Old;

