// This file is auto-generated by refactor.js

import { render } from '../../core/engine.js';
import { renderPriceHistoryModal } from '../../components/modals.js';
import { 
    processSalonApplication, updateStaffPermissions, deleteStaff, buySubscription, getAvatarPlaceholder
} from '../../api.js';
import { formatPrice, getSalonPrice, getSalonDuration, getDurationText, showToast } from '../../utils.js';
import { assignMasterToBooking, updateBookingTime, handleTimelineDrop, salonConfirmBooking, salonCancelBooking, salonCompleteBooking } from '../../features/booking/actions.js';
import { state, timeSlots, services, salons, masters, users, salonStaff, salonSubscriptions, salonApplications, subscriptionPlans } from '../../state.js';

export function renderSalonDashboard(salon, salonBookings, confirmedRevenue, salonMasters) {
    // Шаг 5: Аналитика
    const pending = salonBookings.filter(b => b.status === 'pending').length;
    const confirmed = salonBookings.filter(b => b.status === 'confirmed').length;
    const cancelled = salonBookings.filter(b => b.status === 'cancelled').length;
    const total = salonBookings.length || 1;
    const confirmRate = Math.round((confirmed / total) * 100);
    const cancelRate = Math.round((cancelled / total) * 100);

    // Utilization Rate по мастерам и расчет дохода
    const totalSlots = timeSlots.length;
    const masterUtil = salonMasters.map(m => {
        const booked = salonBookings.filter(b => b.masterId === m.id && b.status === 'confirmed').length;
        const rate = totalSlots > 0 ? Math.round((booked / totalSlots) * 100) : 0;
        
        let revenue = 0;
        salonBookings.filter(b => b.masterId === m.id && b.status === 'confirmed').forEach(b => {
            revenue += getSalonPrice(salon.id, b.serviceId, services);
        });
        
        const commissionRate = m.commissionRate || 40;
        const earnings = Math.round(revenue * (commissionRate / 100));

        return { ...m, booked, rate: Math.min(rate, 100), revenue, earnings, commissionRate };
    });

    const totalMastersEarnings = masterUtil.reduce((acc, m) => acc + m.earnings, 0);
    const salonNetProfit = confirmedRevenue - totalMastersEarnings;

    // Когортный анализ клиентов (LTV)
    const clientMap = {};
    salonBookings.filter(b => b.clientUserId && b.status === 'confirmed').forEach(b => {
        if (!clientMap[b.clientUserId]) clientMap[b.clientUserId] = { name: b.clientName, visits: 0, revenue: 0 };
        clientMap[b.clientUserId].visits++;
        clientMap[b.clientUserId].revenue += getSalonPrice(salon.id, b.serviceId, services);
    });
    const clientCohorts = Object.values(clientMap).sort((a, b) => b.revenue - a.revenue);

    // Причины отмен
    const cancelReasons = salonBookings.filter(b => b.status === 'cancelled' && b.cancelReason).map(b => b.cancelReason);

    return `
<div class="animate-fade-in">
    <h1 class="text-2xl font-bold text-system-text mb-6">Дашборд — ${salon.name}</h1>

    <!-- Основные метрики -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6">
        <div class="stat-card"><div class="text-2xl mb-1">📅</div><div class="text-2xl font-bold text-system-text">${salonBookings.length}</div><div class="text-xs text-system-muted">Всего записей</div></div>
        <div class="stat-card"><div class="text-2xl mb-1">⏳</div><div class="text-2xl font-bold text-yellow-600">${pending}</div><div class="text-xs text-system-muted">Ожидают</div></div>
        <div class="stat-card"><div class="text-2xl mb-1">💇‍♀️</div><div class="text-2xl font-bold text-system-text">${salonMasters.length}</div><div class="text-xs text-system-muted">Мастеров</div></div>
        <div class="stat-card"><div class="text-2xl mb-1">💼</div><div class="text-2xl font-bold text-green-600">${formatPrice(salonNetProfit)}</div><div class="text-xs text-system-muted">Чистая прибыль салонa</div></div>
    </div>

    <!-- Финансы -->
    <div class="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-6 mb-6 text-white shadow-xl">
        <h3 class="font-bold text-gray-100 mb-4 flex items-center gap-2"><span class="text-xl">💳</span> Бухгалтерия и комиссии</h3>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
                <p class="text-system-muted opacity-70 text-sm mb-1">Общая выручка</p>
                <p class="text-2xl font-bold">${formatPrice(confirmedRevenue)}</p>
            </div>
            <div>
                <p class="text-system-muted opacity-70 text-sm mb-1">Выплачено мастерам</p>
                <p class="text-2xl font-bold text-primary-400">${formatPrice(totalMastersEarnings)}</p>
            </div>
            <div>
                <p class="text-system-muted opacity-70 text-sm mb-1">Чистая прибыль салона</p>
                <p class="text-2xl font-bold text-green-400">${formatPrice(salonNetProfit)}</p>
            </div>
        </div>
    </div>

    <!-- Воронка статусов -->
    <div class="bg-system-surface rounded-2xl border border-system-border p-5 mb-6">
        <h3 class="font-bold text-system-text mb-4">📊 Воронка статусов</h3>
        <div class="space-y-3">
            <div>
                <div class="flex justify-between text-sm mb-1"><span class="text-system-muted">Подтверждено</span><span class="font-bold text-green-600">${confirmRate}%</span></div>
                <div class="w-full bg-system-main rounded-full h-2.5"><div class="bg-green-500 h-2.5 rounded-full transition-all" style="width:${confirmRate}%"></div></div>
            </div>
            <div>
                <div class="flex justify-between text-sm mb-1"><span class="text-system-muted">Ожидают</span><span class="font-bold text-yellow-600">${Math.round((pending / total) * 100)}%</span></div>
                <div class="w-full bg-system-main rounded-full h-2.5"><div class="bg-yellow-400 h-2.5 rounded-full transition-all" style="width:${Math.round((pending / total) * 100)}%"></div></div>
            </div>
            <div>
                <div class="flex justify-between text-sm mb-1"><span class="text-system-muted">Отменено</span><span class="font-bold text-red-500">${cancelRate}%</span></div>
                <div class="w-full bg-system-main rounded-full h-2.5"><div class="bg-red-400 h-2.5 rounded-full transition-all" style="width:${cancelRate}%"></div></div>
            </div>
        </div>
        ${cancelReasons.length > 0 ? `<div class="mt-3 pt-3 border-t border-system-border"><p class="text-xs text-system-muted opacity-70 font-bold mb-1">Причины отмен:</p>${cancelReasons.map(r => `<span class="text-[10px] bg-red-50 text-red-500 px-2 py-0.5 rounded-full mr-1">${r}</span>`).join('')}</div>` : ''}
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <!-- Загрузка мастеров -->
        <div class="bg-system-surface rounded-2xl border border-system-border p-5">
            <h3 class="font-bold text-system-text mb-4">⚡ Мастера: Загрузка и Доход</h3>
            <div class="space-y-4">
                ${masterUtil.map(m => `
                <div>
                    <div class="flex items-center justify-between mb-1">
                        <div class="flex items-center gap-2">
                            <img src="${m.avatar}" class="w-6 h-6 rounded-full object-cover">
                            <div>
                                <div class="text-sm font-medium text-system-text">${m.name}</div>
                                <div class="text-[10px] text-system-muted">Доход: ${formatPrice(m.earnings)} (Выручка: ${formatPrice(m.revenue)} | Ставка: ${m.commissionRate}%)</div>
                            </div>
                        </div>
                        <span class="text-xs font-bold ${m.rate > 70 ? 'text-green-600' : m.rate > 30 ? 'text-yellow-600' : 'text-system-muted opacity-70'}">${m.rate}%</span>
                    </div>
                    <div class="w-full bg-system-main rounded-full h-2"><div class="h-2 rounded-full transition-all ${m.rate > 70 ? 'bg-green-500' : m.rate > 30 ? 'bg-yellow-400' : 'bg-system-border'}" style="width:${m.rate}%"></div></div>
                </div>`).join('')}
            </div>
        </div>

        <!-- Когортный анализ клиентов (LTV) -->
        <div class="bg-system-surface rounded-2xl border border-system-border p-5">
            <h3 class="font-bold text-system-text mb-4">👥 Топ клиенты (LTV)</h3>
            ${clientCohorts.length > 0 ? `
            <div class="space-y-2">
                ${clientCohorts.slice(0, 5).map((c, i) => `
                <div class="flex items-center justify-between p-2 rounded-xl ${i === 0 ? 'bg-primary-50' : 'hover:bg-system-main'} transition-colors">
                    <div class="flex items-center gap-2">
                        <span class="w-5 h-5 rounded-full bg-system-main text-[10px] font-bold flex items-center justify-center text-system-muted">${i + 1}</span>
                        <span class="text-sm font-medium text-system-text">${c.name}</span>
                    </div>
                    <div class="text-right">
                        <div class="text-sm font-bold text-system-text">${formatPrice(c.revenue)}</div>
                        <div class="text-[10px] text-system-muted opacity-70">${c.visits} визит${c.visits > 4 ? 'ов' : c.visits > 1 ? 'а' : ''}</div>
                    </div>
                </div>`).join('')}
            </div>` : '<p class="text-sm text-system-muted opacity-70 text-center py-4">Пока нет данных</p>'}
        </div>
    </div>

    <!-- Pending bookings -->
    ${pending > 0 ? `
        <div class="bg-system-surface rounded-2xl border border-2 border-yellow-400 overflow-hidden">
            <h3 class="font-semibold text-system-text p-4 border-b border-system-border bg-transparent text-yellow-500">⏳ Записи, требующие подтверждения</h3>
            <div class="divide-y divide-system-border">
                ${salonBookings.filter(b => b.status === 'pending').map(b => {
        const svc = services.find(s => s.id === b.serviceId);
        return `<div class="p-4 flex items-center justify-between">
                        <div>
                            <p class="font-medium text-system-text">${svc ? svc.name : 'Услуга'}</p>
                            <p class="text-sm text-system-muted">${b.clientName} · ${b.clientPhone}</p>
                            <p class="text-xs text-system-muted opacity-70">${b.date} в ${b.time}</p>
                        </div>
                        <div class="flex gap-2">
                            <button onclick="salonConfirmBooking('${b.id}')" class="btn-primary px-4 py-2 rounded-xl text-white text-xs font-semibold">Подтвердить</button>
                            <button onclick="salonCancelBooking('${b.id}')" class="px-4 py-2 rounded-xl border border-system-border text-system-muted text-xs font-semibold hover:bg-system-main">Отклонить</button>
                        </div>
                    </div>`;
    }).join('')}
            </div>
        </div>
    ` : '<div class="bg-system-surface rounded-2xl border border-system-border p-8 text-center text-system-muted opacity-70">Нет записей, требующих подтверждения ✓</div>'}
</div>`;
}

window.renderSalonDashboard = renderSalonDashboard;

export function renderSalonPricesTab(salon, allServices) {
    if (!salon.providedServices) {
        salon.providedServices = allServices.filter(s => (salon.categories || []).includes(s.category)).map(s => s.id);
    }

    const currentSubTab = state.salonServicesTab || 'my';

    const navHTML = `
    <div class="flex gap-2 mb-6 border-b border-system-border pb-2">
        <button onclick="state.salonServicesTab='my'; render()" class="px-4 py-2 text-sm font-bold transition-colors ${currentSubTab === 'my' ? 'text-primary-600 border-b-2 border-primary-500' : 'text-system-muted hover:text-system-text'}">Мои услуги</button>
        <button onclick="state.salonServicesTab='all'; render()" class="px-4 py-2 text-sm font-bold transition-colors ${currentSubTab === 'all' ? 'text-primary-600 border-b-2 border-primary-500' : 'text-system-muted hover:text-system-text'}">Все услуги</button>
    </div>`;

    let contentHTML = '';

    if (currentSubTab === 'all') {
        const grouped = allServices.reduce((acc, svc) => {
            const catId = svc.category;
            if (!acc[catId]) { acc[catId] = { cat: categories.find(c => c.id === catId), services: [] }; }
            acc[catId].services.push(svc);
            return acc;
        }, {});

        contentHTML = `
        <div class="space-y-3">
            ${Object.entries(grouped).map(([catId, g]) => {
                const isOpen = state.expandedCategoriesAll === undefined ? true : state.expandedCategoriesAll[catId] !== false;
                const catSelectedCount = g.services.filter(s => salon.providedServices.includes(s.id)).length;
                const isAllCatSelected = catSelectedCount === g.services.length;
                
                return `
            <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden">
                <div class="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-system-main transition-colors" onclick="if (!state.expandedCategoriesAll) state.expandedCategoriesAll={}; state.expandedCategoriesAll[${catId}]=${!isOpen}; render()">
                    <div class="flex items-center gap-3" onclick="event.stopPropagation()">
                        <input type="checkbox" class="w-5 h-5 rounded border-system-border text-primary-500 focus:ring-primary-400" ${isAllCatSelected ? 'checked' : ''} onchange="toggleSalonCategory(${salon.id}, parseInt('${catId}'), this.checked)">
                        <span class="text-xl">${g.cat ? g.cat.icon : '📋'}</span>
                        <h3 class="font-bold text-system-text">${g.cat ? g.cat.name : 'Другое'}</h3>
                        <span class="text-xs text-system-muted opacity-70 bg-system-main px-2 py-0.5 rounded-full">${catSelectedCount}/${g.services.length}</span>
                    </div>
                    <div class="flex items-center gap-2">
                        <span class="text-system-muted opacity-70 transition-transform ${isOpen ? '' : '-rotate-90'}" style="display:inline-block;transition:transform .2s">▾</span>
                    </div>
                </div>
                ${isOpen ? `<div class="border-t border-system-border divide-y divide-system-border">
                    ${g.services.map(svc => {
                        const isSelected = salon.providedServices.includes(svc.id);
                        return `
                    <div class="flex items-center px-5 py-3 hover:bg-system-main transition-colors gap-3 ${!isSelected ? 'opacity-50' : ''}">
                        <input type="checkbox" class="w-4 h-4 rounded border-system-border text-primary-500 focus:ring-primary-400" ${isSelected ? 'checked' : ''} onchange="toggleSalonService(${salon.id}, ${svc.id}, this.checked)">
                        <div>
                            <span class="text-sm font-medium text-system-text block">${svc.name}</span>
                            <span class="text-xs text-system-muted opacity-70 whitespace-nowrap">Базовая: ${formatPrice(svc.price)} / ${svc.duration} мин</span>
                        </div>
                    </div>`;
                    }).join('')}
                </div>` : ''}
            </div>`;
            }).join('')}
        </div>`;
    } else {
        const myServices = allServices.filter(s => salon.providedServices.includes(s.id));
        const grouped = myServices.reduce((acc, svc) => {
            const catId = svc.category;
            if (!acc[catId]) { acc[catId] = { cat: categories.find(c => c.id === catId), services: [] }; }
            acc[catId].services.push(svc);
            return acc;
        }, {});

        contentHTML = myServices.length === 0 ? '<div class="text-center py-12 text-system-muted opacity-70 bg-system-surface rounded-2xl border border-system-border">Нет добавленных услуг</div>' : `
        <div class="space-y-3">
            ${Object.entries(grouped).map(([catId, g]) => {
                const isOpen = state.expandedCategoriesMy === undefined ? true : state.expandedCategoriesMy[catId] !== false;
                
                return `
            <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden">
                <div class="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-system-main transition-colors" onclick="if (!state.expandedCategoriesMy) state.expandedCategoriesMy={}; state.expandedCategoriesMy[${catId}]=${!isOpen}; render()">
                    <div class="flex items-center gap-3">
                        <span class="text-xl">${g.cat ? g.cat.icon : '📋'}</span>
                        <h3 class="font-bold text-system-text">${g.cat ? g.cat.name : 'Другое'}</h3>
                        <span class="text-xs text-system-muted opacity-70 bg-system-main px-2 py-0.5 rounded-full">${g.services.length}</span>
                    </div>
                    <div class="flex items-center gap-2">
                        <button onclick="event.stopPropagation(); batchPriceIncrease(${salon.id},${catId},10)" class="text-[10px] bg-green-50 text-green-600 px-3 py-1 rounded-full font-bold hover:bg-green-100">+10% всем</button>
                        <span class="text-system-muted opacity-70 transition-transform ${isOpen ? '' : '-rotate-90'}" style="display:inline-block;transition:transform .2s">▾</span>
                    </div>
                </div>
                ${isOpen ? `<div class="border-t border-system-border divide-y divide-system-border">
                    ${g.services.map(svc => {
                        const cp = getSalonPrice(salon.id, svc.id, services);
                        const cd = getSalonDuration(salon.id, svc.id, services);
                        
                        return `
                    <div class="flex flex-col sm:flex-row sm:items-center justify-between px-5 py-3 hover:bg-system-main transition-colors gap-3">
                        <div class="flex-1 min-w-0">
                            <span class="text-sm font-medium text-system-text block">${svc.name}</span>
                        </div>
                        <div class="flex items-center gap-3">
                            <div class="flex flex-col items-end">
                                <div class="flex items-center gap-2">
                                    <label class="text-[10px] text-system-muted w-12 text-right">Время:</label>
                                    <input type="number" step="5" min="5" class="w-16 px-2 py-1 rounded-lg border border-system-border text-sm focus:border-primary-400 outline-none history-track-time" 
                                           value="${cd}" 
                                           data-oldsval="${cd}"
                                           onblur="if(this.value!=this.dataset.oldsval){ updateSalonDuration(${salon.id},${svc.id},parseInt(this.value)); this.dataset.oldsval=this.value; showToast('Время обновлено'); }">
                                    <span class="text-[10px] text-system-muted opacity-70 w-6">мин</span>
                                </div>
                                <div class="flex items-center gap-2 mt-1">
                                    <label class="text-[10px] text-system-muted w-12 text-right">Цена:</label>
                                    <input type="number" step="50" min="0" class="w-16 px-2 py-1 rounded-lg border border-system-border text-sm focus:border-primary-400 outline-none history-track-price" 
                                           value="${cp}" 
                                           data-oldsval="${cp}"
                                           onblur="if(this.value!=this.dataset.oldsval){ updateSalonPrice(${salon.id},${svc.id},parseInt(this.value)); this.dataset.oldsval=this.value; showToast('Цена обновлена'); }">
                                    <span class="text-[10px] text-system-muted opacity-70 w-6">сом</span>
                                </div>
                            </div>
                            <div class="flex items-center self-end border-l border-system-border pl-2 ml-1">
                                <button onclick="state.showPriceHistory={salonId:${salon.id},serviceId:${svc.id}}; render()" class="text-primary-500 hover:text-primary-700 text-xl mx-1" title="История изменений">📊</button>
                                <button onclick="state.showServiceEdit=${svc.id}; render()" class="text-blue-500 hover:text-blue-700 text-xl mx-1" title="Редактировать услугу">✏️</button>
                            </div>
                        </div>
                    </div>`;
                    }).join('')}
                </div>` : ''}
            </div>`;
            }).join('')}
        </div>`;
    }

    return `
<div class="animate-fade-in relative">
    <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-system-text">Услуги салона</h1>
        <p class="text-sm text-system-muted">${salon.providedServices.length} услуг выбрано</p>
    </div>
    ${navHTML}
    ${contentHTML}
    ${state.showPriceHistory ? renderPriceHistoryModal() : ''}
    ${state.showServiceEdit ? renderServiceEditModal() : ''}
</div>`;
}

window.renderSalonPricesTab = renderSalonPricesTab;

export function toggleSalonService(salonId, serviceId, checked) {
    const salon = salons.find(s => s.id === salonId);
    if (!salon) return;
    if (!salon.providedServices) salon.providedServices = services.filter(s => (salon.categories || []).includes(s.category)).map(s => s.id);
    if (checked && !salon.providedServices.includes(serviceId)) {
        salon.providedServices.push(serviceId);
    } else if (!checked && salon.providedServices.includes(serviceId)) {
        salon.providedServices = salon.providedServices.filter(id => id !== serviceId);
    }
    render();
}

window.toggleSalonService = toggleSalonService;

export function toggleSalonCategory(salonId, catId, checked) {
    const salon = salons.find(s => s.id === salonId);
    if (!salon) return;
    if (!salon.providedServices) salon.providedServices = services.filter(s => (salon.categories || []).includes(s.category)).map(s => s.id);
    
    const catServiceIds = services.filter(s => s.category === catId).map(s => s.id);
    if (checked) {
        catServiceIds.forEach(id => {
            if (!salon.providedServices.includes(id)) salon.providedServices.push(id);
        });
    } else {
        salon.providedServices = salon.providedServices.filter(id => !catServiceIds.includes(id));
    }
    render();
}

window.toggleSalonCategory = toggleSalonCategory;

export function batchPriceIncrease(salonId, catId, pct) {
    services.filter(s => s.category === parseInt(catId)).forEach(svc => {
        const cur = getSalonPrice(salonId, svc.id, services);
        updateSalonPrice(salonId, svc.id, Math.round(cur * (1 + pct / 100)));
    });
    showToast('Цены категории +' + pct + '%');
    render();
}

window.batchPriceIncrease = batchPriceIncrease;

export function renderServiceEditModal() {
    const serviceId = state.showServiceEdit;
    const svc = services.find(s => s.id === serviceId);
    if (!svc) return '';

    return `
<div class="fixed inset-0 z-50 p-4 flex items-center justify-center modal-overlay" onclick="state.showServiceEdit=null; render()">
    <div class="bg-system-surface w-full max-w-md rounded-3xl shadow-2xl animate-scale-in overflow-hidden flex flex-col" onclick="event.stopPropagation()">
        <div class="px-6 py-4 border-b border-system-border flex items-center justify-between bg-system-main">
            <h2 class="font-bold text-system-text">Редактировать услугу</h2>
            <button onclick="state.showServiceEdit=null; render()" class="w-8 h-8 rounded-full bg-system-surface flex items-center justify-center hover:bg-system-main shadow-sm border border-system-border">
                <svg class="w-4 h-4 text-system-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
            </button>
        </div>
        <div class="p-6 space-y-4">
            <div>
                <label class="block text-sm font-medium text-system-text mb-1.5">Описание</label>
                <textarea class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" rows="3" oninput="services.find(s=>s.id===${serviceId}).description=this.value">${svc.description || ''}</textarea>
            </div>
            <div>
                <label class="block text-sm font-medium text-system-text mb-1.5">URL Фотографии 1</label>
                <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${(svc.images && svc.images[0]) || ''}" oninput="
                    const s = services.find(s=>s.id===${serviceId});
                    if(!s.images) s.images=[];
                    s.images[0]=this.value;
                ">
            </div>
            <div>
                <label class="block text-sm font-medium text-system-text mb-1.5">URL Фотографии 2</label>
                <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${(svc.images && svc.images[1]) || ''}" oninput="
                    const s = services.find(s=>s.id===${serviceId});
                    if(!s.images) s.images=[];
                    s.images[1]=this.value;
                ">
            </div>
            <div>
                <label class="block text-sm font-medium text-system-text mb-1.5">URL Фотографии 3</label>
                <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${(svc.images && svc.images[2]) || ''}" oninput="
                    const s = services.find(s=>s.id===${serviceId});
                    if(!s.images) s.images=[];
                    s.images[2]=this.value;
                ">
            </div>
            <button onclick="state.showServiceEdit=null; showToast('Услуга сохранена'); render()" class="w-full btn-primary py-3 rounded-2xl text-white font-semibold text-sm shadow-xl shadow-primary-200">Готово</button>
        </div>
    </div>
</div>`;
}

window.renderServiceEditModal = renderServiceEditModal;

export function renderBookingEditModal(bookingId, salonMasters) {
    const b = state.bookings.find(x => x.id === bookingId);
    if (!b) return '';
    const svc = services.find(s => s.id === b.serviceId);
    const slots = window.timeSlots || [];

    return `
    <div class="fixed inset-0 z-50 p-4 flex items-center justify-center modal-overlay" onclick="state.editingBookingId=null; render()">
        <div class="bg-system-surface w-full max-w-md rounded-3xl shadow-2xl animate-scale-in overflow-hidden flex flex-col" onclick="event.stopPropagation()">
            <div class="px-6 py-4 border-b border-system-border flex items-center justify-between bg-system-main">
                <div>
                    <h2 class="font-bold text-system-text text-lg">Редактирование записи</h2>
                    <p class="text-[10px] text-system-muted uppercase tracking-widest mt-0.5">ID: ${b.id}</p>
                </div>
                <button onclick="state.editingBookingId=null; render()" class="w-8 h-8 rounded-full bg-system-surface flex items-center justify-center hover:bg-system-main shadow-sm border border-system-border transition-colors group">
                    <svg class="w-4 h-4 text-system-muted opacity-70 group-hover:text-system-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>
            <div class="p-6 space-y-5">
                <div class="flex items-start gap-4 p-4 rounded-2xl bg-primary-50 border border-primary-100/50">
                    <div class="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center shrink-0">
                        <span class="text-xl">🧑</span>
                    </div>
                    <div>
                        <p class="text-xs text-primary-400 font-medium mb-0.5 uppercase tracking-wider">Клиент</p>
                        <p class="font-bold text-system-text">${b.clientName}</p>
                        <p class="text-xs text-system-muted font-medium mt-0.5">${b.clientPhone}</p>
                    </div>
                </div>

                <div>
                    <p class="text-xs text-system-muted opacity-70 font-medium mb-1 uppercase tracking-wider ml-1">Услуга</p>
                    <div class="p-3 rounded-xl border border-system-border bg-system-main font-medium text-system-text flex items-center gap-3">
                        <span class="text-xl">✨</span> ${svc ? svc.name : 'Неизвестно'}
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 pt-2">
                    <div>
                        <label class="text-xs text-system-muted opacity-70 font-medium mb-1 block uppercase tracking-wider ml-1">Мастер</label>
                        <select onchange="window.assignMasterToBooking('${b.id}', this.value); state.editingBookingId=null;" class="w-full text-sm border border-system-border rounded-xl p-3 outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100 bg-system-surface font-medium text-system-text transition-all cursor-pointer">
                            <option value="" ${!b.masterId ? 'selected' : ''}>— Не назначен —</option>
                            ${salonMasters.map(m => `
                                <option value="${m.id}" ${b.masterId === m.id ? 'selected' : ''}>${m.name}</option>
                            `).join('')}
                        </select>
                    </div>
                    <div>
                        <label class="text-xs text-system-muted opacity-70 font-medium mb-1 block uppercase tracking-wider ml-1">Время</label>
                        <select onchange="window.updateBookingTime('${b.id}', this.value); state.editingBookingId=null;" class="w-full text-sm border border-system-border rounded-xl p-3 outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100 bg-system-surface font-medium text-system-text transition-all cursor-pointer">
                            ${slots.map(t => `<option value="${t}" ${b.time === t ? 'selected' : ''}>${t}</option>`).join('')}
                        </select>
                    </div>
                </div>

                <div class="pt-6 mt-2 border-t border-system-border flex flex-wrap gap-2">
                    ${b.status === 'pending' ? `
                        <button onclick="window.salonConfirmBooking('${b.id}'); state.editingBookingId=null;" class="flex-1 bg-green-500 text-white rounded-xl py-3 text-sm font-bold shadow-md shadow-green-200 hover:bg-green-600 transition-all hover:-translate-y-0.5">Подтвердить</button>
                        <button onclick="window.salonCancelBooking('${b.id}'); state.editingBookingId=null;" class="flex-1 bg-red-50 text-red-600 border border-red-100 rounded-xl py-3 text-sm font-bold hover:bg-red-100 transition-colors">Отклонить</button>
                    ` : b.status === 'confirmed' ? `
                        <button onclick="window.salonCompleteBooking('${b.id}'); state.editingBookingId=null;" class="flex-1 bg-blue-500 text-white rounded-xl py-3 text-sm font-bold shadow-md shadow-blue-200 hover:bg-blue-600 transition-all hover:-translate-y-0.5">Завершить</button>
                        <button onclick="window.salonCancelBooking('${b.id}'); state.editingBookingId=null;" class="flex-1 bg-system-main text-system-muted rounded-xl py-3 text-sm font-bold hover:bg-system-border transition-colors">Отменить</button>
                    ` : `
                        <div class="w-full text-center py-3 rounded-xl ${b.status === 'completed' ? 'bg-blue-50 text-blue-700' : 'bg-red-50 text-red-700'} border ${b.status === 'completed' ? 'border-blue-100' : 'border-red-100'}">
                            <span class="font-bold text-sm">Статус: ${b.status === 'completed' ? '✅ Завершена' : '❌ Отменена'}</span>
                        </div>
                    `}
                </div>
            </div>
        </div>
    </div>`;
}

window.renderBookingEditModal = renderBookingEditModal;

export function renderSalonBookings(salonBookings) {
    const statusColors = { pending: 'bg-yellow-100 text-yellow-700', confirmed: 'bg-green-100 text-green-700', completed: 'bg-blue-100 text-blue-700', cancelled: 'bg-red-100 text-red-700' };
    const statusLabels = { pending: 'Ожидает', confirmed: 'Подтверждена', completed: 'Завершена', cancelled: 'Отменена' };
    const salon = salons.find(s => s.id === state.currentUser.salonId);
    const salonMasters = masters.filter(m => m.salonId === salon.id);
    const viewMode = state.salonViewMode || 'table';

    const timelineHTML = (() => {
        if (viewMode !== 'timeline') return '';
        const slots = window.timeSlots || ['09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'];
        const slotWidth = 100; // Increased for better text visibility

        function timeToMinutes(t) {
            if (!t) return 0;
            const [h, m] = t.split(':').map(Number);
            return h * 60 + (m || 0);
        }

        const startOfTimeline = timeToMinutes(slots[0] || '09:00'); 

        return `
        <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden relative shadow-sm">
            <div class="overflow-x-auto min-h-[300px] timeline-container">
                <div style="min-width: ${slots.length * slotWidth + 140}px;" class="relative pb-4">
                    <!-- Header -->
                    <div class="flex border-b border-system-border bg-system-main sticky top-0 z-20">
                        <div class="p-3 text-left font-bold text-system-muted sticky left-0 bg-system-main z-30 border-r border-system-border" style="width: 140px; min-width: 140px;">Мастер</div>
                        ${slots.map(t => `<div class="py-3 text-center text-xs font-medium text-system-muted border-l border-system-border shrink-0" style="width: ${slotWidth}px;"><span class="bg-system-main px-2 py-1 rounded-md">${t}</span></div>`).join('')}
                    </div>
                    
                    <!-- Master Rows -->
                    ${salonMasters.map((m, mIndex) => {
                        const masterBookings = salonBookings.filter(b => b.masterId === m.id && b.status !== 'cancelled');
                        
                        return `
                        <div class="flex border-b ${mIndex === salonMasters.length - 1 ? 'border-transparent' : 'border-system-border'} relative group min-h-[80px]">
                            <!-- Sticky Master Column -->
                            <div class="p-3 sticky left-0 bg-system-surface z-20 border-r border-system-border flex items-center gap-3 shrink-0" style="width: 140px; min-width: 140px;">
                                <img src="${m.avatar}" class="w-10 h-10 rounded-full object-cover border-2 border-white shadow-sm" alt="${m.name}">
                                <span class="font-bold text-system-text text-xs truncate" title="${m.name}">${m.name}</span>
                            </div>
                            
                            <!-- Timeline Grid Background Tracks -->
                            <div class="flex flex-1 relative  bg-repeat">
                                ${slots.map(t => `
                                    <div class="border-l border-system-border/50 shrink-0 hover:bg-primary-50/30 transition-colors" 
                                         style="width: ${slotWidth}px;" 
                                         ondragover="event.preventDefault()" 
                                         ondrop="handleTimelineDrop(event, ${m.id}, '${t}')">
                                    </div>`).join('')}
                                
                                <!-- Absolute position bookings -->
                                ${masterBookings.map(booking => {
                                    const svc = services.find(s => s.id === booking.serviceId);
                                    const tMins = timeToMinutes(booking.time);
                                    let startOffsetMins = tMins - startOfTimeline;
                                    
                                    if (startOffsetMins < 0) startOffsetMins = 0; // Guard against events before timeline start
                                    
                                    const durationMins = getSalonDuration(salon.id, svc ? svc.id : null, services) || (svc ? svc.duration : 60);
                                    
                                    // Calculate pixel position
                                    const leftPx = (startOffsetMins / 60) * slotWidth;
                                    const widthPx = (durationMins / 60) * slotWidth;
                                    
                                    // Prevent zero width
                                    const finalWidthPx = Math.max(widthPx, 40); 
                                    
                                    const isConfirmed = booking.status === 'confirmed';
                                    const isCompleted = booking.status === 'completed';
                                    
                                    let statusColorClass = 'bg-transparent text-yellow-500 hover:bg-yellow-100 text-yellow-800 border-2 border-yellow-400';
                                    if (isConfirmed) statusColorClass = 'bg-green-50 hover:bg-green-100 text-green-800 border-green-200';
                                    if (isCompleted) statusColorClass = 'bg-blue-50 hover:bg-blue-100 text-blue-800 border-blue-200';
                                    
                                    return `
                                    <div draggable="true" 
                                         ondragstart="event.dataTransfer.setData('bookingId','${booking.id}'); event.target.style.opacity='0.5';"
                                         ondragend="event.target.style.opacity='1';"
                                         onclick="state.editingBookingId='${booking.id}'; render()"
                                         class="absolute top-2 bottom-2 rounded-xl p-2 cursor-pointer transition-all shadow-sm hover:shadow-md hover:scale-[1.02] border flex flex-col justify-center overflow-hidden z-10 ${statusColorClass}"
                                         style="left: ${leftPx + 4}px; width: ${finalWidthPx - 8}px;">
                                        <div class="font-bold text-[11px] truncate leading-tight mb-1 opacity-90">${svc ? svc.name : 'Без услуги'}</div>
                                        <div class="flex items-center justify-between mt-auto">
                                            <span class="text-[10px] font-medium truncate opacity-70 pr-1">${booking.clientName}</span>
                                            <span class="text-[9px] px-1 py-0.5 bg-black/5 rounded-md font-bold whitespace-nowrap">${booking.time}</span>
                                        </div>
                                    </div>`;
                                }).join('')}
                            </div>
                        </div>`;
                    }).join('')}
                </div>
            </div>
        </div>`;
    })();

    return `
<div class="animate-fade-in">
    <div class="flex items-center justify-between mb-6">
        <div class="flex items-center gap-4">
            <h1 class="text-2xl font-bold text-system-text">Записи салона</h1>
            <button onclick="window.openBookingForSalon(${salon.id})" class="btn-primary px-4 py-2 rounded-xl text-white font-semibold text-sm flex items-center gap-1"><span class="text-lg leading-none">+</span> Добавить запись</button>
        </div>
        <div class="flex bg-system-main rounded-xl p-0.5">
            <button onclick="state.salonViewMode='table'; render()" class="px-3 py-1.5 rounded-lg text-xs font-bold transition-colors ${viewMode === 'table' ? 'bg-system-surface shadow-sm text-system-text' : 'text-system-muted'}">📋 Таблица</button>
            <button onclick="state.salonViewMode='timeline'; render()" class="px-3 py-1.5 rounded-lg text-xs font-bold transition-colors ${viewMode === 'timeline' ? 'bg-system-surface shadow-sm text-system-text' : 'text-system-muted'}">📅 Timeline</button>
        </div>
    </div>
    
    <!-- ФИЛЬТР ПО СТАТУСУ -->
    <div class="flex items-center gap-2 mb-6 border-b border-system-border pb-2 overflow-x-auto hide-scrollbar">
        <button onclick="state.salonBookingStatusFilter='all'; render()" class="px-4 py-2 font-semibold text-sm whitespace-nowrap border-b-2 transition-colors ${!state.salonBookingStatusFilter || state.salonBookingStatusFilter === 'all' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Все записи</button>
        <button onclick="state.salonBookingStatusFilter='pending'; render()" class="px-4 py-2 font-semibold text-sm whitespace-nowrap border-b-2 transition-colors ${state.salonBookingStatusFilter === 'pending' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Ожидают</button>
        <button onclick="state.salonBookingStatusFilter='confirmed'; render()" class="px-4 py-2 font-semibold text-sm whitespace-nowrap border-b-2 transition-colors ${state.salonBookingStatusFilter === 'confirmed' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Подтвержденные</button>
        <button onclick="state.salonBookingStatusFilter='completed'; render()" class="px-4 py-2 font-semibold text-sm whitespace-nowrap border-b-2 transition-colors ${state.salonBookingStatusFilter === 'completed' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Завершенные</button>
        <button onclick="state.salonBookingStatusFilter='cancelled'; render()" class="px-4 py-2 font-semibold text-sm whitespace-nowrap border-b-2 transition-colors ${state.salonBookingStatusFilter === 'cancelled' ? 'border-primary-500 text-primary-600' : 'border-transparent text-system-muted hover:text-system-text'}">Отмененные</button>
    </div>
    ${(() => {
        const filter = state.salonBookingStatusFilter || 'all';
        const filteredBookings = filter === 'all' ? salonBookings : salonBookings.filter(b => b.status === filter);
        return viewMode === 'timeline' ? timelineHTML : (filteredBookings.length > 0 ? `
        <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden">
            <div class="overflow-x-auto">
                <table class="admin-table w-full text-sm">
                    <thead><tr class="border-b border-system-border">
                        <th class="text-left p-3 font-medium text-system-muted">Клиент</th>
                        <th class="text-left p-3 font-medium text-system-muted">Услуга</th>
                        <th class="text-left p-3 font-medium text-system-muted">Дата/Время</th>
                        <th class="text-left p-3 font-medium text-system-muted">Мастер</th>
                        <th class="text-left p-3 font-medium text-system-muted">Сумма</th>
                        <th class="text-left p-3 font-medium text-system-muted">Статус</th>
                        <th class="text-left p-3 font-medium text-system-muted">Действия</th>
                    </tr></thead>
                    <tbody>
                        ${filteredBookings.map(b => {
                const svc = services.find(s => s.id === b.serviceId);
                return `<tr class="border-b border-system-border">
                                <td data-label="Клиент" class="p-3 text-system-text">
                                    <div class="font-medium">${b.clientName}</div>
                                    <div class="flex items-center gap-1.5 mt-0.5">
                                        <span class="text-xs text-system-muted opacity-70">${b.clientPhone}</span>
                                        <button onclick="window.openWhatsAppModal('${b.id}')" class="text-[#25D366] hover:text-[#128C7E] flex items-center justify-center transition-colors" title="Написать в WhatsApp">
                                            <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 0C5.385 0 0 5.385 0 12.032c0 2.13.551 4.2 1.597 6.03L.044 24l6.096-1.597c1.782.951 3.75 1.452 5.86 1.452h.005c6.641 0 12.023-5.384 12.023-12.031C24 5.21 18.636 0 12.031 0zm0 21.848h-.004c-1.802 0-3.565-.483-5.111-1.398l-.367-.217-3.8.995 1.01-3.7-.238-.378c-1.002-1.59-1.53-3.41-1.53-5.281 0-5.518 4.49-10.005 10.04-10.005 5.518 0 10.006 4.486 10.006 10.005 0 5.517-4.488 10.004-10.006 10.004zm5.519-7.514c-.302-.152-1.79-.884-2.066-.985-.276-.102-.477-.152-.678.151-.202.302-.78 1.01-.956 1.218-.176.208-.352.233-.654.081-1.314-.582-2.5-1.464-3.418-2.548-.286-.337-.123-.5.029-.652.138-.138.303-.353.454-.53.15-.175.2-.301.301-.502.101-.201.05-.378-.026-.53-.075-.151-.678-1.636-.928-2.241-.244-.59-.492-.51-.678-.52-.175-.008-.376-.011-.577-.011-.201 0-.528.075-.804.377-.276.302-1.054 1.03-1.054 2.511s1.079 2.913 1.23 3.115c.15.202 2.122 3.238 5.14 4.54 1.838.79 2.569.851 3.5.72 1.03-.146 3.167-1.294 3.619-2.541.452-1.246.452-2.316.317-2.54-.135-.224-.502-.352-.804-.504z"/></svg>
                                        </button>
                                    </div>
                                </td>
                                <td data-label="Услуга" class="p-3">${svc ? svc.name : '-'}</td>
                                <td data-label="Дата/Время" class="p-3 font-bold">${b.date}<br><span class="text-xs text-system-muted opacity-70">${b.time}</span></td>
                                <td data-label="Мастер" class="p-3">
                                    <select onchange="assignMasterToBooking('${b.id}', this.value)" class="text-xs border-none bg-system-main rounded-lg p-1.5 font-medium outline-none focus:ring-2 focus:ring-primary-200">
                                        <option value="" ${!b.masterId ? 'selected' : ''}>— Назначить —</option>
                                        ${salonMasters.map(m => `
                                            <option value="${m.id}" ${b.masterId === m.id ? 'selected' : ''}>${m.name}</option>
                                        `).join('')}
                                    </select>
                                </td>
                                <td data-label="Сумма" class="p-3 font-bold text-primary-600">${svc ? formatPrice(getSalonPrice(salon.id, svc.id, services)) : '-'}</td>
                                <td data-label="Статус" class="p-3"><span class="badge ${statusColors[b.status]}">${statusLabels[b.status]}</span></td>
                                <td data-label="Действия" class="p-3">
                                    ${b.status === 'pending' ? `
                                        <button onclick="salonConfirmBooking('${b.id}')" class="text-xs text-green-600 hover:text-green-700 font-bold mr-2">OK</button>
                                        <button onclick="salonCancelBooking('${b.id}')" class="text-xs text-red-500 hover:text-red-700 font-bold">✕</button>
                                    ` : b.status === 'confirmed' ? `
                                        <button onclick="salonCompleteBooking('${b.id}')" class="text-xs text-blue-600 hover:text-blue-700 font-bold mr-2">Завершить</button>
                                        <button onclick="salonCancelBooking('${b.id}')" class="text-xs text-system-muted opacity-70 hover:text-red-500 transition-colors">Отменить</button>
                                    ` : ''}
                                </td>
                            </tr>`;
            }).join('')}
                    </tbody>
                </table>
            </div>
        </div>
    ` : '<div class="text-center py-12 text-system-muted opacity-70 bg-system-surface rounded-2xl border border-system-border">Записей пока нет</div>');
    })()}
    ${state.editingBookingId ? renderBookingEditModal(state.editingBookingId, salonMasters) : ''}
    ${state.whatsappBookingId ? renderWhatsAppModal() : ''}
</div>`; 
}

window.renderSalonBookings = renderSalonBookings;

export function renderSalonMasters(salonMasters, salon) {
    const grouped = {};
    getSalonServices(salon, services).forEach(svc => {
        const cat = categories.find(c => c.id === svc.category);
        const key = cat ? cat.id : 0;
        if (!grouped[key]) grouped[key] = { cat, services: [] };
        grouped[key].services.push(svc);
    });

    if (!state.activeMasterId && salonMasters.length > 0) {
        state.activeMasterId = salonMasters[0].id;
    }

    const em = masters.find(m => m.id === state.activeMasterId);

    return `
<div class="animate-fade-in h-[calc(100vh-140px)] flex flex-col">
    <h1 class="text-2xl font-bold text-system-text mb-6 shrink-0">Мастера салона</h1>
    
    <div class="flex flex-col md:flex-row gap-6 flex-1 min-h-0">
        <!-- Left panel: Masters list -->
        <div class="w-full md:w-1/3 bg-system-surface rounded-2xl border border-system-border overflow-y-auto flex flex-col">
            ${salonMasters.length > 0 ? `
                <div class="p-4 space-y-3">
                    ${salonMasters.map(m => `
                        <div class="rounded-xl border ${em && em.id === m.id ? 'border-primary-400 bg-primary-50' : 'border-system-border hover:border-primary-400'} p-4 cursor-pointer transition-colors" onclick="state.activeMasterId=${m.id}; render()">
                            <div class="flex items-center gap-3">
                                <img src="${m.avatar}" class="w-12 h-12 rounded-full object-cover">
                                <div class="flex-1 min-w-0">
                                    <h3 class="font-bold text-system-text truncate">${m.name}</h3>
                                    <p class="text-xs text-primary-500 truncate">${m.specialty}</p>
                                </div>
                            </div>
                            <div class="mt-3 flex items-center justify-between text-[10px] text-system-muted">
                                <span>Услуг: ${(m.services || []).length}</span>
                                <span class="${m.available ? 'text-green-500' : 'text-system-muted opacity-70'}">${m.available ? '● Активна' : '○ Не в смене'}</span>
                            </div>
                        </div>
                    `).join('')}
                </div>
            ` : '<div class="text-center py-12 text-system-muted opacity-70">В салоне пока нет мастеров</div>'}
        </div>

        <!-- Right panel: Master details & commissions -->
        <div class="w-full md:w-2/3 bg-system-surface rounded-2xl border border-system-border overflow-y-auto flex flex-col">
            ${em ? `
                <div class="p-6 border-b border-system-border shrink-0 bg-system-main flex items-center justify-between sticky top-0 z-10 hidden sm:flex">
                    <div class="flex items-center gap-4">
                        <img src="${em.avatar}" class="w-14 h-14 rounded-full object-cover">
                        <div>
                            <h2 class="text-lg font-bold text-system-text">${em.name}</h2>
                            <p class="text-sm text-system-muted">${em.specialty} · Опыт ${em.experience} лет</p>
                        </div>
                    </div>
                </div>
                <div class="p-6 flex-1 overflow-y-auto">
                    <div class="mb-6 bg-primary-50 p-5 rounded-2xl border border-primary-100">
                        <h3 class="text-sm font-bold text-system-text mb-2">Общая комиссия мастера</h3>
                        <div class="flex items-center gap-3">
                            <input type="number" min="0" max="100" class="w-20 px-3 py-2 rounded-xl border border-primary-200 focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-center font-bold" value="${em.commissionRate || 40}" 
                                   onchange="updateMasterCommission(${em.id}, this.value)">
                            <span class="text-system-muted font-medium">%</span>
                            <p class="text-xs text-system-muted ml-2">Применяется ко всем услугам по умолчанию</p>
                        </div>
                    </div>

                    <h3 class="text-sm font-bold text-system-text mb-4 uppercase tracking-wider">Услуги и индивидуальная комиссия</h3>
                    <div class="space-y-6">
                        ${Object.values(grouped).map(g => `
                            <div class="bg-system-main rounded-2xl border border-system-border overflow-hidden">
                                <div class="px-5 py-3 border-b border-system-border bg-system-main flex flex-wrap gap-2 items-center justify-between">
                                    <h4 class="text-sm font-bold text-system-text">${g.cat ? g.cat.icon + ' ' + g.cat.name : 'Другое'}</h4>
                                </div>
                                <div class="divide-y divide-system-border">
                                    ${g.services.map(svc => {
                                        const checked = (em.services || []).includes(svc.id);
                                        const currentComm = lookupMasterServiceCommission(em, svc.id);
                                        return `
                                        <div class="flex items-center gap-3 p-4 hover:bg-system-main transition-colors ${!checked ? 'opacity-60' : ''}">
                                            <input type="checkbox" ${checked ? 'checked' : ''} onchange="toggleMasterService(${em.id}, ${svc.id})"
                                                   class="w-5 h-5 rounded border-system-border text-primary-500 focus:ring-primary-400">
                                            <div class="flex-1 min-w-0">
                                                <span class="text-sm font-medium text-system-text block">${svc.name}</span>
                                                <span class="text-xs text-system-muted opacity-70">${getDurationText(getSalonDuration(salon.id, svc.id, services))} · Цена: ${formatPrice(getSalonPrice(salon.id, svc.id, services))}</span>
                                            </div>
                                            <div class="flex items-center gap-2">
                                                <label class="text-[10px] text-system-muted w-12 text-right leading-tight">Комиссия:<br>(%)</label>
                                                <input type="number" min="0" max="100" class="w-16 px-2 py-1.5 rounded-lg border border-system-border text-sm focus:border-primary-400 outline-none text-center" 
                                                       value="${currentComm}" ${!checked ? 'disabled' : ''} 
                                                       onchange="updateMasterServiceCommission(${em.id}, ${svc.id}, this.value)">
                                            </div>
                                        </div>`;
                                    }).join('')}
                                </div>
                            </div>
                        `).join('')}
                    </div>
                </div>
            ` : '<div class="flex items-center justify-center h-full text-system-muted opacity-70">Выберите мастера для настройки</div>'}
        </div>
    </div>
</div>`;
}

window.renderSalonMasters = renderSalonMasters;

export function toggleMasterService(masterId, serviceId) {
    const m = masters.find(x => x.id === masterId);
    if (!m) return;
    if (!m.services) m.services = [];
    const idx = m.services.indexOf(serviceId);
    if (idx >= 0) { m.services.splice(idx, 1); } 
    else { m.services.push(serviceId); }
    render();
}

window.toggleMasterService = toggleMasterService;

export function updateMasterCommission(masterId, value) {
    const m = masters.find(x => x.id === masterId);
    if (!m) return;
    const rate = parseInt(value, 10);
    if (!isNaN(rate) && rate >= 0 && rate <= 100) {
        m.commissionRate = rate;
        render();
    }
}

window.updateMasterCommission = updateMasterCommission;

export function lookupMasterServiceCommission(master, serviceId) {
    if (master.serviceCommissions && master.serviceCommissions[serviceId] !== undefined) {
        return master.serviceCommissions[serviceId];
    }
    return master.commissionRate || 40;
}

window.lookupMasterServiceCommission = lookupMasterServiceCommission;

export function updateMasterServiceCommission(masterId, serviceId, value) {
    const m = masters.find(x => x.id === masterId);
    if (!m) return;
    const rate = parseInt(value, 10);
    if (!m.serviceCommissions) m.serviceCommissions = {};
    if (!isNaN(rate) && rate >= 0 && rate <= 100) {
        m.serviceCommissions[serviceId] = rate;
        render();
    }
}

window.updateMasterServiceCommission = updateMasterServiceCommission;

export function renderSalonProfile(salon) {
    return `
<div class="animate-fade-in max-w-lg">
    <h1 class="text-2xl font-bold text-system-text mb-6">Профиль салона</h1>
    <div class="bg-system-surface rounded-2xl border border-system-border p-6 space-y-4">
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Название</label>
            <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${salon.name}" oninput="salons.find(s=>s.id===${salon.id}).name=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Адрес</label>
            <input type="text" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${salon.address}" oninput="salons.find(s=>s.id===${salon.id}).address=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Время работы</label>
            <div class="flex gap-3">
                <input type="text" class="auth-input flex-1 px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${salon.openTime}" oninput="salons.find(s=>s.id===${salon.id}).openTime=this.value">
                <span class="flex items-center text-system-muted opacity-70">—</span>
                <input type="text" class="auth-input flex-1 px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm" value="${salon.closeTime}" oninput="salons.find(s=>s.id===${salon.id}).closeTime=this.value">
            </div>
        </div>
        <button onclick="showToast('Профиль салона сохранён')" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">Сохранить</button>
    </div>
</div>`;
}

window.renderSalonProfile = renderSalonProfile;

export function updateServiceField(id, field, value) {
    const svc = services.find(s => s.id === id);
    if (!svc) return;
    if (field === 'price' || field === 'duration' || field === 'category') {
        svc[field] = parseInt(value, 10);
    } else {
        svc[field] = value;
    }
    render();
}

window.updateServiceField = updateServiceField;

export function deleteService(id) {
    const idx = services.findIndex(s => s.id === id);
    if (idx >= 0) services.splice(idx, 1);
    render();
}

window.deleteService = deleteService;

export function addService() {
    const name = document.getElementById('newSvcName').value;
    const category = parseInt(document.getElementById('newSvcCat').value, 10);
    const gender = document.getElementById('newSvcGender') ? document.getElementById('newSvcGender').value : 'all';
    const price = parseInt(document.getElementById('newSvcPrice').value, 10) || 1000;
    const duration = parseInt(document.getElementById('newSvcTime').value, 10) || 60;
    if (!name) return;
    const newId = services.length ? Math.max(...services.map(s => s.id)) + 1 : 1;
    services.push({ id: newId, category, name, gender, price, duration, rating: '5.0', popular: false });
    render();
}

window.addService = addService;

export function verifySalon(salonId) {
    const salon = salons.find(s => s.id === salonId);
    if (salon) { salon.verified = true; showToast('Салон подтверждён'); render(); }
}

window.verifySalon = verifySalon;

// ---- Новые вкладки управления салоном ----

export function renderSalonApplicationsTab(salon) {
    const apps = salonApplications.filter(a => a.salonId === salon.id);
    const pendingApps = apps.filter(a => a.status === 'pending');
    const historyApps = apps.filter(a => a.status !== 'pending');

    return `
    <div class="animate-fade-in space-y-6">
        <div class="flex items-center justify-between">
            <h1 class="text-2xl font-bold text-system-text">Заявки на вступление</h1>
            <span class="badge bg-blue-100 text-blue-600">${pendingApps.length} новых</span>
        </div>

        <div class="space-y-4">
            <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">Новые заявки</h3>
            ${pendingApps.length === 0 ? '<div class="p-8 bg-system-surface rounded-2xl border border-dashed border-system-border text-center text-system-muted opacity-70 italic">Нет новых заявок</div>' : `
                <div class="grid grid-cols-1 gap-4">
                    ${pendingApps.map(app => {
                        const user = users.find(u => u.id === app.userId);
                        return `
                        <div class="bg-system-surface p-5 rounded-2xl border border-system-border flex items-center justify-between shadow-sm">
                            <div class="flex items-center gap-4">
                                <img src="${getAvatarPlaceholder(user?.name)}" class="w-12 h-12 rounded-xl object-cover">
                                <div>
                                    <h4 class="font-bold text-system-text">${user?.name || 'Пользователь'}</h4>
                                    <p class="text-xs text-system-muted">${user?.phone} • Желаемая роль: <span class="font-medium text-system-text">${app.baseRole}</span></p>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <button onclick="handleProcessApp('${app.id}', 'reject')" class="px-4 py-2 rounded-xl border border-red-100 text-red-500 text-sm font-medium hover:bg-red-50 transition-colors">Отклонить</button>
                                <button onclick="handleProcessApp('${app.id}', 'approve')" class="px-4 py-2 rounded-xl bg-blue-600 text-white text-sm font-medium hover:bg-blue-700 transition-colors shadow-lg shadow-blue-200">Принять</button>
                            </div>
                        </div>
                        `;
                    }).join('')}
                </div>
            `}
        </div>

        ${historyApps.length > 0 ? `
            <div class="space-y-4 pt-4">
                <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">История</h3>
                <div class="bg-system-surface rounded-2xl border border-system-border overflow-hidden shadow-sm">
                    <table class="w-full text-left text-sm">
                        <thead class="bg-system-main border-b border-system-border">
                            <tr>
                                <th class="px-6 py-4 font-bold text-system-muted">Кандидат</th>
                                <th class="px-6 py-4 font-bold text-system-muted">Роль</th>
                                <th class="px-6 py-4 font-bold text-system-muted">Дата</th>
                                <th class="px-6 py-4 font-bold text-system-muted">Статус</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-system-border">
                            ${historyApps.map(app => {
                                const user = users.find(u => u.id === app.userId);
                                const statusColor = app.status === 'approved' ? 'text-green-600 bg-green-50' : 'text-red-600 bg-red-50';
                                return `
                                <tr>
                                    <td class="px-6 py-4 font-medium text-system-text">${user?.name || '---'}</td>
                                    <td class="px-6 py-4 text-system-muted">${app.baseRole}</td>
                                    <td class="px-6 py-4 text-system-muted opacity-70 font-mono text-xs">${new Date(app.createdAt).toLocaleDateString()}</td>
                                    <td class="px-6 py-4">
                                        <span class="px-2 py-1 rounded-lg text-xs font-bold ${statusColor}">${app.status}</span>
                                    </td>
                                </tr>
                                `;
                            }).join('')}
                        </tbody>
                    </table>
                </div>
            </div>
        ` : ''}
    </div>
    `;
}

window.renderSalonApplicationsTab = renderSalonApplicationsTab;

async function handleProcessApp(appId, decision) {
    const res = await processSalonApplication(appId, decision);
    if (res.success) {
        showToast(decision === 'approve' ? 'Заявка принята' : 'Заявка отклонена');
        render();
    } else {
        showToast(res.error || 'Ошибка', 'error');
    }
}
window.handleProcessApp = handleProcessApp;

export function renderSalonStaffTab(salon) {
    const staffList = salonStaff.filter(s => s.salonId === salon.id);
    const modules = [
        { id: 'dashboard', label: '📊 Дашборд' },
        { id: 'bookings', label: '📅 Записи' },
        { id: 'masters', label: '💇‍♀️ Мастера' },
        { id: 'applications', label: '📩 Заявки' },
        { id: 'staff', label: '👥 Штат' },
        { id: 'services', label: '💰 Услуги' },
        { id: 'subscription', label: '💳 Подписка' },
        { id: 'profile', label: '⚙️ Профиль' }
    ];
    const actions = [
        { id: 'view', label: 'Просмотр' },
        { id: 'edit', label: 'Ред.' },
        { id: 'delete', label: 'Удал.' }
    ];

    return `
    <div class="animate-fade-in space-y-6">
        <h1 class="text-2xl font-bold text-system-text">Управление персоналом и доступом</h1>
        
        <div class="space-y-6">
            ${staffList.map(item => {
                const user = users.find(u => u.id === item.userId);
                const isOwner = item.baseRole === 'owner';
                const isMaster = item.baseRole === 'master';
                
                return `
                <div class="bg-system-surface rounded-3xl border border-system-border shadow-xl overflow-hidden">
                    <div class="p-6 border-b border-system-border bg-system-main flex items-center justify-between">
                        <div class="flex items-center gap-4">
                            <img src="${getAvatarPlaceholder(user?.name)}" class="w-12 h-12 rounded-2xl">
                            <div>
                                <div class="font-extrabold text-system-text flex items-center gap-2">
                                    ${user?.name || '---'}
                                    <span class="px-2 py-0.5 rounded-lg text-[10px] uppercase tracking-wider ${isOwner ? 'bg-purple-100 text-purple-600' : 'bg-blue-100 text-blue-600'}">
                                        ${item.baseRole}
                                    </span>
                                </div>
                                <div class="text-xs text-system-muted opacity-70 font-medium">${user?.phone}</div>
                            </div>
                        </div>
                        ${!isOwner ? `<button onclick="handleDeleteStaff('${item.id}')" class="p-2 text-red-400 hover:text-red-500 hover:bg-system-surface rounded-xl transition-all shadow-sm">🗑️</button>` : ''}
                    </div>
                    
                    <div class="p-6">
                        <div class="overflow-x-auto">
                            <table class="w-full text-left text-xs border-collapse">
                                <thead>
                                    <tr class="text-system-muted opacity-70 uppercase tracking-widest font-bold">
                                        <th class="pb-4 pl-2">Модуль</th>
                                        ${actions.map(a => `<th class="pb-4 text-center">${a.label}</th>`).join('')}
                                    </tr>
                                </thead>
                                <tbody class="divide-y divide-system-border">
                                    ${modules.map(mod => {
                                        return `
                                        <tr>
                                            <td class="py-3 font-bold text-system-text pl-2">${mod.label}</td>
                                            ${actions.map(action => {
                                                const permKey = `${mod.id}:${action.id}`;
                                                const has = isOwner || (item.permissions && item.permissions.includes(permKey));
                                                const isDisabled = isOwner || isMaster;
                                                return `
                                                <td class="py-3 text-center">
                                                    <label class="inline-flex items-center cursor-pointer ${isDisabled ? 'opacity-50 cursor-not-allowed' : ''}">
                                                        <input type="checkbox" class="hidden" 
                                                            ${has ? 'checked' : ''} 
                                                            ${isDisabled ? 'disabled' : ''}
                                                            onchange="handleTogglePermission('${item.id}', '${permKey}', this.checked)">
                                                        <div class="w-10 h-6 bg-system-main rounded-full p-1 transition-all ${has ? 'bg-blue-500' : ''}">
                                                            <div class="w-4 h-4 bg-system-surface rounded-full shadow-sm transform transition-transform ${has ? 'translate-x-4' : ''}"></div>
                                                        </div>
                                                    </label>
                                                </td>
                                                `;
                                            }).join('')}
                                        </tr>
                                        `;
                                    }).join('')}
                                </tbody>
                            </table>
                        </div>
                        ${isOwner ? `<p class="mt-4 text-[10px] text-purple-400 italic font-medium px-2">● Владелец имеет полный доступ ко всем функциям по умолчанию</p>` : ''}
                        ${isMaster ? `<p class="mt-4 text-[10px] text-blue-400 italic font-medium px-2">● Права мастеров ограничены их функциональной ролью (расписание и услуги)</p>` : ''}
                    </div>
                </div>
                `;
            }).join('')}
        </div>
    </div>
    `;
}

window.renderSalonStaffTab = renderSalonStaffTab;

async function handleTogglePermission(staffId, key, val) {
    const res = await updateStaffPermissions(staffId, key, val);
    if (res.success) {
        showToast('Права обновлены');
        render();
    }
}
window.handleTogglePermission = handleTogglePermission;

async function handleDeleteStaff(staffId) {
    if (confirm('Вы уверены, что хотите удалить этого сотрудника?')) {
        const res = await deleteStaff(staffId);
        if (res.success) {
            showToast('Сотрудник удален');
            render();
        }
    }
}
window.handleDeleteStaff = handleDeleteStaff;

export function renderSalonSubscriptionTab(salon) {
    const sub = salonSubscriptions.find(s => s.salonId === salon.id);
    const plan = sub ? subscriptionPlans.find(p => p.id === sub.planId) : null;
    const history = salonTransactions.filter(t => t.salonId === salon.id).sort((a,b) => new Date(b.date) - new Date(a.date));

    return `
    <div class="animate-fade-in space-y-8">
        <div class="flex items-center justify-between">
            <h1 class="text-2xl font-bold text-system-text">Управление подпиской</h1>
            ${sub && sub.status === 'active' ? `
                <div class="flex items-center gap-2 px-4 py-2 bg-green-50 rounded-2xl border border-green-100">
                    <span class="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
                    <span class="text-xs font-bold text-green-700 uppercase tracking-wider">Подписка активна</span>
                </div>
            ` : `
                <div class="px-4 py-2 bg-red-50 rounded-2xl border border-red-100">
                    <span class="text-xs font-bold text-red-700 uppercase tracking-wider">Подписка неактивна</span>
                </div>
            `}
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            ${subscriptionPlans.map(p => {
                const isCurrent = sub && sub.planId === p.id;
                return `
                <div class="bg-system-surface rounded-3xl p-8 border-2 transition-all relative ${isCurrent ? 'border-blue-500 shadow-2xl shadow-blue-100' : 'border-system-border shadow-sm hover:border-system-text'}">
                    ${isCurrent ? `<span class="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 bg-blue-500 text-white rounded-full text-[10px] font-bold uppercase tracking-widest">Текущий план</span>` : ''}
                    <h3 class="text-xl font-bold text-system-text mb-2">${p.name}</h3>
                    <div class="flex items-baseline gap-1 mb-6">
                        <span class="text-4xl font-extrabold text-blue-600">${p.price}</span>
                        <span class="text-system-muted opacity-70 font-medium font-mono text-sm">сом/мес</span>
                    </div>
                    <ul class="space-y-4 mb-8">
                        ${p.features.map(f => `
                            <li class="flex items-start gap-3 text-sm text-system-muted">
                                <span class="text-green-500">✓</span> ${f}
                            </li>
                        `).join('')}
                    </ul>
                    <button onclick="handleBuySub('${p.id}')" class="w-full py-4 rounded-2xl font-bold text-sm transition-all ${isCurrent ? 'bg-system-main text-system-muted cursor-default' : 'bg-system-text text-system-surface hover:opacity-90 shadow-lg shadow-primary-200/20'}">
                        ${isCurrent ? 'Активен' : 'Выбрать план'}
                    </button>
                </div>
                `;
            }).join('') || ''}
        </div>

        <div class="space-y-4 pt-6">
            <h3 class="text-sm font-bold text-system-muted opacity-70 uppercase tracking-wider">История транзакций</h3>
            <div class="bg-system-surface rounded-3xl border border-system-border overflow-hidden shadow-xl">
                <table class="w-full text-left text-sm border-collapse">
                    <thead class="bg-system-main border-b border-system-border">
                        <tr>
                            <th class="px-6 py-4 font-bold text-system-muted">ID Транзакции</th>
                            <th class="px-6 py-4 font-bold text-system-muted">Тариф</th>
                            <th class="px-6 py-4 font-bold text-system-muted">Дата</th>
                            <th class="px-6 py-4 font-bold text-system-muted">Сумма</th>
                            <th class="px-6 py-4 font-bold text-system-muted">Статус</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-system-border">
                        ${history.map(trx => {
                            const p = subscriptionPlans.find(plan => plan.id === trx.planId);
                            return `
                            <tr>
                                <td class="px-6 py-4 font-mono text-xs text-system-muted opacity-70">${trx.id}</td>
                                <td class="px-6 py-4 font-bold text-system-text">${p?.name || '---'}</td>
                                <td class="px-6 py-4 text-system-muted">${new Date(trx.date).toLocaleDateString()}</td>
                                <td class="px-6 py-4 font-bold text-blue-600">${trx.amount} сом</td>
                                <td class="px-6 py-4">
                                    <span class="px-2 py-1 rounded-lg text-[10px] font-bold uppercase bg-green-50 text-green-600">Успешно</span>
                                </td>
                            </tr>
                            `;
                        }).join('')}
                        ${history.length === 0 ? '<tr><td colspan="5" class="px-6 py-8 text-center text-system-muted opacity-70 italic">История платежей пуста</td></tr>' : ''}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    `;
}

window.renderSalonSubscriptionTab = renderSalonSubscriptionTab;

async function handleBuySub(planId) {
    const salon = salons.find(s => s.id === state.currentUser.salonId);
    const res = await buySubscription(salon.id, planId);
    if (res.success) {
        showToast('Подписка успешно оформлена');
        render();
    }
}
window.handleBuySub = handleBuySub;



export function renderWhatsAppModal() {
    if (!state.whatsappBookingId) return '';
    const b = state.bookings.find(x => x.id === state.whatsappBookingId);
    if (!b) return '';
    const salon = salons.find(s => s.id === (state.currentUser && state.currentUser.salonId)) || salons.find(s => s.id === b.targetId) || salons[0];
    
    const phone = (b.clientPhone || '').replace(/\D/g, ''); 
    if (phone.length < 9) {
        return `<div class="fixed inset-0 z-[100] p-4 flex items-center justify-center modal-overlay" onclick="window.closeWhatsAppModal()">
            <div class="bg-system-surface max-w-sm w-full rounded-2xl p-6 text-center shadow-xl" onclick="event.stopPropagation()">
                <div class="w-12 h-12 bg-red-50 text-red-500 rounded-full flex items-center justify-center text-xl mx-auto mb-4">⚠️</div>
                <h3 class="font-bold text-system-text mb-2">Некорректный номер телефона</h3>
                <p class="text-system-muted text-sm mb-6">Отредактируйте номер клиента перед отправкой сообщения.</p>
                <button onclick="window.closeWhatsAppModal()" class="w-full btn-primary py-3 rounded-xl font-bold">Закрыть</button>
            </div>
        </div>`;
    }

    return `
    <div class="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onclick="window.closeWhatsAppModal()">
        <div class="bg-system-surface w-full max-w-md rounded-2xl shadow-xl animate-scale-in" onclick="event.stopPropagation()">
            <div class="p-6 border-b border-system-border bg-system-main flex items-center justify-between">
                <div class="flex items-center gap-2">
                    <svg class="w-5 h-5 text-[#25D366]" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 0C5.385 0 0 5.385 0 12.032c0 2.13.551 4.2 1.597 6.03L.044 24l6.096-1.597c1.782.951 3.75 1.452 5.86 1.452h.005c6.641 0 12.023-5.384 12.023-12.031C24 5.21 18.636 0 12.031 0zm0 21.848h-.004c-1.802 0-3.565-.483-5.111-1.398l-.367-.217-3.8.995 1.01-3.7-.238-.378c-1.002-1.59-1.53-3.41-1.53-5.281 0-5.518 4.49-10.005 10.04-10.005 5.518 0 10.006 4.486 10.006 10.005 0 5.517-4.488 10.004-10.006 10.004zm5.519-7.514c-.302-.152-1.79-.884-2.066-.985-.276-.102-.477-.152-.678.151-.202.302-.78 1.01-.956 1.218-.176.208-.352.233-.654.081-1.314-.582-2.5-1.464-3.418-2.548-.286-.337-.123-.5.029-.652.138-.138.303-.353.454-.53.15-.175.2-.301.301-.502.101-.201.05-.378-.026-.53-.075-.151-.678-1.636-.928-2.241-.244-.59-.492-.51-.678-.52-.175-.008-.376-.011-.577-.011-.201 0-.528.075-.804.377-.276.302-1.054 1.03-1.054 2.511s1.079 2.913 1.23 3.115c.15.202 2.122 3.238 5.14 4.54 1.838.79 2.569.851 3.5.72 1.03-.146 3.167-1.294 3.619-2.541.452-1.246.452-2.316.317-2.54-.135-.224-.502-.352-.804-.504z"/></svg>
                    <h3 class="text-lg font-bold text-system-text">Написать клиенту</h3>
                </div>
                <button onclick="window.closeWhatsAppModal()" class="w-8 h-8 rounded-full bg-system-surface flex items-center justify-center text-system-muted hover:text-system-text shadow-sm border border-system-border text-lg">&times;</button>
            </div>
            
            <div class="p-6">
                <div class="p-3 bg-system-main rounded-xl border border-system-border mb-5">
                    <div class="text-sm font-semibold text-system-text">${b.clientName}</div>
                    <div class="text-xs text-system-muted font-mono">${b.clientPhone}</div>
                </div>
                
                <p class="text-xs font-bold uppercase tracking-wider text-system-muted opacity-70 mb-3 ml-1">Шаблоны сообщений</p>
                <div class="space-y-3 mb-2">
                    
                    <button onclick="window.sendWhatsAppMessage('${phone}', 'Добрый день, ${b.clientName}! Пишем из ${salon.name}. Записали вас на ${b.date} в ${b.time}. Ожидаем вас!')" class="w-full text-left p-4 rounded-xl border border-system-border bg-system-surface hover:border-[#25D366] hover:bg-[#25D366] hover:bg-opacity-5 transition-all group">
                        <div class="flex items-center justify-between mb-1">
                            <div class="text-sm font-semibold text-system-text group-hover:text-[#128C7E]">Подтверждение записи</div>
                            <svg class="w-4 h-4 text-[#25D366] opacity-0 group-hover:opacity-100 transition-opacity" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                        </div>
                        <div class="text-xs text-system-muted mt-2 line-clamp-2 leading-relaxed tracking-wide">«Добрый день, ${b.clientName}! Пишем из ${salon.name}. Записали вас на ${b.date} в ${b.time}. Ожидаем вас!»</div>
                    </button>
                    
                    
                    <button onclick="window.sendWhatsAppMessage('${phone}', 'Добрый день, ${b.clientName}! Напоминаем о записи на ${b.date} в ${b.time} в ${salon.name}. Наш адрес: ${salon.address || ''}. Будем рады видеть вас!')" class="w-full text-left p-4 rounded-xl border border-system-border bg-system-surface hover:border-[#25D366] hover:bg-[#25D366] hover:bg-opacity-5 transition-all group">
                        <div class="flex items-center justify-between mb-1">
                            <div class="text-sm font-semibold text-system-text group-hover:text-[#128C7E]">Напоминание и адрес</div>
                            <svg class="w-4 h-4 text-[#25D366] opacity-0 group-hover:opacity-100 transition-opacity" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                        </div>
                        <div class="text-xs text-system-muted mt-2 line-clamp-2 leading-relaxed tracking-wide">«Добрый день, ${b.clientName}! Напоминаем о записи на ${b.date} в ${b.time}...»</div>
                    </button>
                    
                    
                    <button onclick="window.sendWhatsAppMessage('${phone}', 'Добрый день, ${b.clientName}! У вас запись на ${b.date} в ${b.time} в ${salon.name}. Подскажите, пожалуйста, задержитесь ли вы?')" class="w-full text-left p-4 rounded-xl border border-system-border bg-system-surface hover:border-[#25D366] hover:bg-[#25D366] hover:bg-opacity-5 transition-all group">
                        <div class="flex items-center justify-between mb-1">
                            <div class="text-sm font-semibold text-system-text group-hover:text-[#128C7E]">Уточнение (Опоздание)</div>
                            <svg class="w-4 h-4 text-[#25D366] opacity-0 group-hover:opacity-100 transition-opacity" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                        </div>
                        <div class="text-xs text-system-muted mt-2 line-clamp-2 leading-relaxed tracking-wide">«Добрый день, ${b.clientName}! У вас запись на ${b.date} в ${b.time}...»</div>
                    </button>
                </div>
            </div>
            
        </div>
    </div>`;
}

window.renderWhatsAppModal = renderWhatsAppModal;

window.openWhatsAppModal = (id) => {
    state.whatsappBookingId = id;
    render();
};

window.closeWhatsAppModal = () => {
    state.whatsappBookingId = null;
    render();
};

window.sendWhatsAppMessage = (phone, text) => {
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/${phone}?text=${encoded}`, '_blank');
    window.closeWhatsAppModal();
};
