// This file is auto-generated by refactor.js

import { openBookingForSalon, openBookingForMaster } from '../features/booking/actions.js';
import { openSalonDetail, openMasterDetail, openServiceDetail } from '../apps/client/pages.js';
import { formatPrice, getDurationText, getPriceLevel } from '../utils.js';

export function renderServiceCard(svc) {
    const cat = categories.find(c => c.id === svc.category);
    const genderMap = { male: '👨 Муж', female: '👩 Жен', all: '🚻 Всем' };
    const genderBadge = svc.gender ? `<span class="badge ${svc.gender === 'male' ? 'bg-blue-50 text-blue-600' : svc.gender === 'female' ? 'bg-primary-50 text-primary-600' : 'bg-system-main text-system-text'} ml-2">${genderMap[svc.gender] || svc.gender}</span>` : '';
    const providerMasters = masters.filter(m => m.services && m.services.includes(svc.id));
    let providerInfoHtml = '';
    if (providerMasters.length > 0) {
        const firstMaster = providerMasters[0];
        const salonInfo = firstMaster.salonId ? salons.find(s => s.id === firstMaster.salonId) : null;
        providerInfoHtml = `
            <div class="mb-3 text-xs text-system-muted">
                <p class="font-medium text-primary-600">📍 ${salonInfo ? salonInfo.name : 'На выезде'}</p>
                <p class="text-system-muted mt-0.5">✂️ Мастер: ${firstMaster.name} ${providerMasters.length > 1 ? `и еще ${providerMasters.length - 1}` : ''}</p>
            </div>
        `;
    }

    return `
    <div class="island-card p-5 cursor-pointer animate-fade-in flex flex-col h-full" onclick="openServiceDetail(${svc.id})">
<div class="flex items-center gap-2 mb-3">
    <span class="text-lg">${cat ? cat.icon : ''}</span>
    <span class="text-xs text-system-muted font-medium">${cat ? cat.name : ''}</span>
    ${genderBadge}
    
</div>
<h3 class="font-semibold text-system-text mb-2">${svc.name}</h3>
${providerInfoHtml}
<div class="mt-auto">
    <div class="flex items-center gap-1 mb-3">
        <span class="star text-sm">★</span>
        <span class="text-sm font-medium text-system-text">${svc.rating}</span>
        <span class="text-xs text-system-muted">(${svc.reviews || 0})</span>
    </div>
    <div class="flex items-center justify-between">
        <div>
            <span class="text-lg font-bold text-system-text">${formatPrice(svc.price)}</span>
            <span class="text-xs text-system-muted ml-2">${getDurationText(svc.duration)}</span>
        </div>
        <button class="btn-primary px-4 py-2 rounded-xl text-white text-xs font-semibold" onclick="event.stopPropagation();openBookingForService(${svc.id})">Записаться</button>
    </div>
</div>
    </div>`;
}

window.renderServiceCard = renderServiceCard;

export function renderSalonCard(salon) {
    return `
    <div class="island-card overflow-hidden cursor-pointer animate-fade-in" onclick="openSalonDetail(${salon.id})">
<img src="${salon.image}" alt="${salon.name}" class="salon-card-img">
<div class="p-5">
    <div class="flex items-center gap-2 mb-2">
        <h3 class="font-bold text-system-text text-lg">${salon.name}</h3>
        ${salon.verified ? '<span class="badge bg-blue-100 text-blue-600">✓ Проверен</span>' : ''}
    </div>
    <div class="flex items-center gap-1 mb-2">
        <span class="star text-sm">★</span>
        <span class="text-sm font-semibold text-system-text">${salon.rating}</span>
        <span class="text-xs text-system-muted">(${salon.reviews} отзывов)</span>
        <span class="text-xs text-system-muted ml-2">${getPriceLevel(salon.priceLevel)}</span>
    </div>
    <p class="text-sm text-system-muted mb-3">📍 ${salon.address} · ${salon.city || 'Бишкек'}</p>
    <div class="flex flex-wrap gap-1.5 mb-4">
        ${salon.categories.map(catId => {
        const cat = categories.find(c => c.id === catId);
        return cat ? `<span class="badge bg-system-main text-system-muted">${cat.icon} ${cat.name}</span>` : '';
    }).join('')}
    </div>
    <div class="flex items-center justify-between">
        <span class="text-xs text-system-muted">${salon.masters} мастеров · ${salon.openTime}–${salon.closeTime}</span>
        <button class="btn-primary px-4 py-2 rounded-xl text-white text-xs font-semibold" onclick="event.stopPropagation();openBookingForSalon(${salon.id})">Записаться</button>
    </div>
</div>
    </div>`;
}

window.renderSalonCard = renderSalonCard;

export function renderMasterCard(master) {
    const salonInfo = master.salonId ? salons.find(s => s.id === master.salonId) : null;
    return `
    <div class="island-card p-5 cursor-pointer animate-fade-in flex flex-col h-full" onclick="openMasterDetail(${master.id})">
<div class="flex items-start gap-4">
    <img src="${master.avatar}" alt="${master.name}" class="master-avatar flex-shrink-0">
    <div class="min-w-0">
        <h3 class="font-bold text-system-text">${master.name}</h3>
        <p class="text-sm text-primary-500 font-medium">${master.specialty}</p>
        <p class="text-xs text-system-muted mt-1 font-medium text-primary-600">📍 ${salonInfo ? salonInfo.name : 'На выезде'}</p>
        <p class="text-xs text-system-muted opacity-80 mt-0.5">Опыт ${master.experience} лет</p>
    </div>
</div>
<div class="flex items-center gap-1 mt-3">
    <span class="star text-sm">★</span>
    <span class="text-sm font-semibold text-system-text opacity-90">${master.rating}</span>
    <span class="text-xs text-system-muted opacity-80">(${master.reviews})</span>
    <span class="text-xs text-system-muted opacity-80 ml-2">${getPriceLevel(master.priceLevel)}</span>
</div>
<div class="flex flex-wrap gap-1.5 mt-3">
    ${(master.categories || []).map(catId => {
        const cat = categories.find(c => c.id === catId);
        return cat ? `<span class="badge bg-system-main text-system-muted">${cat.icon} ${cat.name}</span>` : '';
    }).join('')}
</div>
<div class="flex items-center justify-between mt-auto pt-4">
    ${master.available
            ? '<span class="text-xs text-green-500 font-medium">● Доступна</span>'
            : '<span class="text-xs text-system-muted opacity-80 font-medium">○ Занят(а)</span>'
        }
    ${master.available
            ? `<button class="btn-primary px-4 py-2 rounded-xl text-white text-xs font-semibold" onclick="event.stopPropagation();openBookingForMaster(${master.id})">Записаться</button>`
            : ''
        }
</div>
    </div>`;
}

window.renderMasterCard = renderMasterCard;

