// This file is auto-generated by refactor.js

import { render } from '../core/engine.js';
import { ThemeManager } from '../utils.js';
import { cancelBooking } from '../features/booking/actions.js';
import { state, users, salons, masters, services } from '../state.js';
import { formatPrice, showToast, getSalonPriceHistory } from '../utils.js';

export function renderProfileEditModal() {
    const user = state.currentUser;
    return `
    <div class="fixed inset-0 z-50 flex items-end sm:items-center justify-center modal-overlay" onclick="closeProfileEdit(event)">
<div class="bg-system-surface w-full sm:max-w-md sm:rounded-3xl rounded-t-3xl animate-slide-up" onclick="event.stopPropagation()">
    <div class="px-6 py-4 border-b border-system-border flex items-center justify-between">
        <h2 class="text-lg font-bold text-system-text">Мой профиль</h2>
        <button onclick="state.showProfileEdit=false;render()" class="w-8 h-8 rounded-full bg-system-main flex items-center justify-center hover:bg-system-border">
            <svg class="w-4 h-4 text-system-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
    </div>
    <div class="p-6 space-y-4">
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Имя</label>
            <input type="text" id="profile-name" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm bg-system-surface text-system-text"
                value="${user.name || ''}" oninput="state.currentUser.name=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Телефон</label>
            <input type="tel" class="w-full px-4 py-3 rounded-xl border border-system-border bg-system-main outline-none text-base sm:text-sm text-system-muted"
                value="${user.phone}" disabled>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Email</label>
            <input type="email" id="profile-email" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm bg-system-surface text-system-text"
                value="${user.email || ''}" oninput="state.currentUser.email=this.value">
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Пол</label>
            <select class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm bg-system-surface text-system-text" onchange="state.currentUser.gender=this.value">
                <option value="female" ${user.gender === 'female' ? 'selected' : ''}>Женский</option>
                <option value="male" ${user.gender === 'male' ? 'selected' : ''}>Мужской</option>
            </select>
        </div>
        <div>
            <label class="block text-sm font-medium text-system-text mb-1.5">Тема оформления</label>
            <div class="flex items-center">
                <select class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-base sm:text-sm bg-system-surface text-system-text" onchange="state.currentUser.theme=this.value; ThemeManager.setTheme(this.value);">
                <option value="beauty" ${user.theme === 'beauty' ? 'selected' : ''}>Beauty (Лепесток)</option>
                <option value="barber" ${user.theme === 'barber' ? 'selected' : ''}>Barber (Уголь)</option>
                <option value="hair" ${user.theme === 'hair' ? 'selected' : ''}>Hair (Лаванда)</option>
                <option value="eco" ${user.theme === 'eco' ? 'selected' : ''}>Eco (Шалфей)</option>
                <option value="medical" ${user.theme === 'medical' ? 'selected' : ''}>Medical (Аква)</option>
            </select>
            </div>
        </div>
        <div class="bg-primary-50 rounded-xl p-4">
            <div class="flex justify-between items-center mb-3">
                <p class="text-sm font-semibold text-system-text mb-0">Текущая роль: ${{ client: 'Клиент', master: 'Мастер', salon: 'Салон', superadmin: 'Супер-админ', admin: 'Супер-админ' }[user.role]}</p>
            </div>
            <div class="space-y-2">
                ${user.role !== 'client' ? `<button onclick="state.currentUser.role='client'; window.navigate('home'); window.render()" class="w-full text-left px-3 py-2 text-sm bg-white rounded-lg border border-primary-100 hover:border-primary-300 transition-colors flex items-center gap-2">👤 Перейти в SuluuMarket</button>` : ''}
                
                ${user.role !== 'master' ? 
                    (user.masterId ? 
                        `<button onclick="state.currentUser.role='master'; window.navigate('schedule'); window.render()" class="w-full text-left px-3 py-2 text-sm bg-white rounded-lg border border-primary-100 hover:border-primary-300 transition-colors flex items-center gap-2">✂️ Перейти в SuluuMaster</button>` 
                        : `<button onclick="state.showBecomeMasterModal=true; render()" class="w-full text-left px-3 py-2 text-sm bg-white rounded-lg border border-primary-100 hover:border-primary-300 transition-colors flex items-center gap-2 text-primary-600 font-medium shadow-sm">✂️ Стать мастером</button>`)
                : ''}

                ${user.role !== 'salon' ? 
                    (user.salonId ? 
                        `<button onclick="state.currentUser.role='salon'; window.navigate('dashboard'); window.render()" class="w-full text-left px-3 py-2 text-sm bg-white rounded-lg border border-primary-100 hover:border-primary-300 transition-colors flex items-center gap-2">🏢 Перейти в SuluuBusiness</button>`
                        : `<button onclick="state.showBecomeSalonModal=true; render()" class="w-full text-left px-3 py-2 text-sm bg-white rounded-lg border border-primary-100 hover:border-primary-300 transition-colors flex items-center gap-2 text-primary-600 font-medium shadow-sm">🏢 Открыть салон</button>`)
                : ''}
            </div>
        </div>
        <button onclick="saveProfile()" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">Сохранить</button>
    </div>
</div>
    </div>`;
}

window.renderProfileEditModal = renderProfileEditModal;

export function closeProfileEdit(event) {
    if (event && event.target !== event.currentTarget) return;
    state.showProfileEdit = false;
    render();
}

window.closeProfileEdit = closeProfileEdit;

export function saveProfile() {
    const user = users.find(u => u.id === state.currentUser.id);
    if (user) {
        user.name = state.currentUser.name;
        user.email = state.currentUser.email;
        user.gender = state.currentUser.gender;
        user.theme = state.currentUser.theme;
    }
    if (state.currentUser.theme) {
        ThemeManager.setTheme(state.currentUser.theme);
    }
    state.showProfileEdit = false;
    showToast('Профиль сохранён');
    render();
}

window.saveProfile = saveProfile;

export function renderReviewModal() {
    if (!state.reviewRating) state.reviewRating = 0;
    return `
    <div class="fixed inset-0 z-50 flex items-center justify-center modal-overlay" onclick="closeReviewModal(event)">
<div class="bg-system-surface w-full max-w-sm rounded-3xl animate-slide-up p-6 relative" onclick="event.stopPropagation()">
    <button onclick="closeReviewModal(event, true)" class="absolute top-4 right-4 text-system-muted hover:bg-system-main rounded-full p-2 transition-colors">✕</button>
    <h3 class="text-xl font-bold text-system-text mb-6 text-center">Оставить отзыв</h3>
    <div class="flex justify-center gap-2 mb-6">
        ${[1,2,3,4,5].map(i => `
            <button onclick="state.reviewRating = ${i}; render();" class="text-4xl focus:outline-none transition-transform hover:scale-110 ${state.reviewRating >= i ? 'text-yellow-400' : 'text-system-border'}">★</button>
        `).join('')}
    </div>
    <textarea id="reviewComment" rows="4" placeholder="Поделитесь вашими впечатлениями..." class="w-full px-4 py-3 rounded-2xl border border-system-border focus:border-primary-400 focus:ring-2 focus:ring-primary-100 outline-none text-sm bg-system-surface text-system-text mb-6 resize-none"></textarea>
    <button onclick="submitReview()" class="btn-primary w-full py-4 rounded-2xl text-white font-bold text-sm shadow-xl shadow-primary-200" ${state.reviewRating === 0 ? 'disabled style="opacity:0.5"' : ''}>Отправить отзыв</button>
</div>
    </div>`;
}

window.renderReviewModal = renderReviewModal;

export function submitReview() {
    const comment = document.getElementById('reviewComment').value.trim();
    const rating = state.reviewRating;
    if (rating === 0) return showToast('Выберите оценку');

    const { type, id } = state.reviewModalTarget;
    const newReview = {
        id: 'R' + Date.now(),
        targetType: type,
        targetId: id,
        userId: state.currentUser.id,
        userName: state.currentUser.name,
        rating: rating,
        comment: comment,
        date: new Date().toLocaleDateString('ru-RU')
    };

    state.reviews.push(newReview);
    
    // Recalculate average rating for the target
    let targetList;
    if(type === 'salon') targetList = salons;
    else if(type === 'master') targetList = masters;
    else if(type === 'service') targetList = services;

    if (targetList) {
        const targetObj = targetList.find(x => x.id === id);
        if (targetObj) {
            const allRs = state.reviews.filter(r => r.targetType === type && r.targetId === id);
            const avg = allRs.reduce((sum, r) => sum + r.rating, 0) / allRs.length;
            targetObj.rating = parseFloat(avg.toFixed(1));
            if (targetObj.reviews !== undefined) targetObj.reviews = allRs.length;
        }
    }

    state.reviewModalTarget = null;
    state.reviewRating = 0;
    showToast('Отзыв успешно добавлен!');
    render();
};

window.submitReview = submitReview;

export function closeReviewModal(e, force = false) {
    if (force || e.target.classList.contains('modal-overlay')) {
        state.reviewModalTarget = null;
        state.reviewRating = 0;
        render();
    }
};

window.closeReviewModal = closeReviewModal;

export function renderTrackModal() {
    if (!state.trackModalTarget) return '';
    const b = state.trackModalTarget;
    const svc = services.find(s => s.id === b.serviceId);
    const salon = salons.find(s => s.id === b.targetId);
    const master = masters.find(m => m.id === b.masterId);
    
    const statusConfig = { 
        pending: { color: 'text-yellow-600', bg: 'bg-yellow-50', border: 'border-yellow-200', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 22h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M5 2h14"/><path stroke-linecap="round" stroke-linejoin="round" d="M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22"/><path stroke-linecap="round" stroke-linejoin="round" d="M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2"/></svg>', text: 'Ожидает' },
        confirmed: { color: 'text-green-600', bg: 'bg-green-50', border: 'border-green-200', icon: '✓', text: 'Подтверждена' },
        completed: { color: 'text-blue-600', bg: 'bg-blue-50', border: 'border-blue-200', icon: '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m12 2 3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>', text: 'Завершена' },
        cancelled: { color: 'text-red-600', bg: 'bg-red-50', border: 'border-red-200', icon: '✕', text: 'Отменена' }
    };
    const sConf = statusConfig[b.status] || statusConfig.pending;

    return `
    <div class="fixed inset-0 z-50 flex items-center justify-center p-4 modal-overlay bg-black/40 backdrop-blur-sm" onclick="closeTrackModal(event)">
<div class="bg-system-surface w-full max-w-sm rounded-[32px] overflow-hidden shadow-2xl animate-scale-in" onclick="event.stopPropagation()">
    <div class="relative px-6 py-8 text-center text-white bg-primary-500">
        <button onclick="closeTrackModal(event, true)" class="absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-full bg-black/10 hover:bg-black/20 text-white transition-colors" title="Закрыть">✕</button>
        <h3 class="text-2xl font-bold mb-1">Детали записи</h3>
        <div class="text-sm opacity-90 font-mono tracking-widest mt-2 bg-black/10 inline-block px-3 py-1 rounded-lg">Код: ${b.trackingCode}</div>
    </div>
    
    <div class="p-6">
        <div class="flex items-center gap-3 p-4 rounded-2xl ${sConf.bg} ${sConf.border} border mb-6">
            <span class="text-2xl">${sConf.icon}</span>
            <div>
                <div class="text-sm font-bold ${sConf.color}">Статус: ${sConf.text}</div>
                ${b.status === 'pending' ? '<div class="text-xs text-system-muted mt-0.5">Ожидайте подтверждения от салона</div>' : ''}
            </div>
        </div>

        <div class="space-y-4 mb-8">
            <div class="flex items-start gap-4">
                <div class="w-10 h-10 rounded-xl bg-system-main flex items-center justify-center text-xl shrink-0"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg></div>
                <div>
                    <div class="text-sm font-medium text-system-text">${b.date} в ${b.time}</div>
                    <div class="text-xs text-system-muted">Дата и время</div>
                </div>
            </div>
            
            ${svc ? `
            <div class="flex items-start gap-4">
                <div class="w-10 h-10 rounded-xl bg-system-main flex items-center justify-center text-xl shrink-0"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7h-3a2 2 0 0 1-2-2V2"/><path stroke-linecap="round" stroke-linejoin="round" d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2 2Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 15h6"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 18h6"/></svg></div>
                <div>
                    <div class="text-sm font-medium text-system-text">${svc.name}</div>
                    <div class="text-xs text-system-muted text-primary-600 font-semibold">${formatPrice(svc.price)}</div>
                </div>
            </div>
            ` : ''}

            ${salon ? `
            <div class="flex items-start gap-4">
                <div class="w-10 h-10 rounded-xl bg-system-main flex items-center justify-center text-xl shrink-0"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 6h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 10h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 14h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 18h4"/></svg></div>
                <div>
                    <div class="text-sm font-medium text-system-text">${salon.name}</div>
                    <div class="text-xs text-system-muted">${salon.address}</div>
                </div>
            </div>
            ` : ''}

            ${master ? `
            <div class="flex items-start gap-4">
                <div class="w-10 h-10 rounded-xl bg-system-main flex items-center justify-center text-xl shrink-0">
                    <img src="${master.avatar}" alt="Master" class="w-full h-full object-cover rounded-xl border border-white">
                </div>
                <div>
                    <div class="text-sm font-medium text-system-text">${master.name}</div>
                    <div class="text-xs text-system-muted">Ваш мастер</div>
                </div>
            </div>
            ` : ''}
        </div>

        <div class="flex flex-col gap-3">
            ${(b.status === 'pending' || b.status === 'confirmed') ? 
                `<button onclick="if(confirm('Вы уверены, что хотите отменить запись?')){ cancelBooking('${b.id}'); setTimeout(() => {closeTrackModal(null, true)}, 500); }" class="w-full py-3.5 rounded-xl border-2 border-red-100 text-red-500 font-bold hover:bg-red-50 transition-colors">Отменить запись</button>` 
            : ''}
            <button onclick="closeTrackModal(null, true)" class="w-full py-3.5 rounded-xl bg-system-main text-system-text font-bold hover:bg-system-border transition-colors">Закрыть</button>
        </div>
    </div>
</div>
    </div>`;
}

window.renderTrackModal = renderTrackModal;

export function closeTrackModal(e, force = false) {
    if (force || e.target.classList.contains('modal-overlay')) {
        state.trackModalTarget = null;
        render();
    }
};

window.closeTrackModal = closeTrackModal;

export function renderPriceHistoryModal() {
    const { salonId, serviceId } = state.showPriceHistory;
    const history = getSalonPriceHistory(salonId, serviceId);
    const svc = services.find(s => s.id === serviceId);

    return `
<div class="fixed inset-0 z-50 p-4 flex items-center justify-center modal-overlay" onclick="state.showPriceHistory=null; render()">
    <div class="bg-system-surface w-full max-w-md rounded-3xl shadow-2xl animate-scale-in overflow-hidden flex flex-col" onclick="event.stopPropagation()">
        <div class="px-6 py-4 border-b border-system-border flex items-center justify-between bg-system-main">
            <h2 class="font-bold text-system-text">История изменений</h2>
            <button onclick="state.showPriceHistory=null; render()" class="w-8 h-8 rounded-full bg-system-surface flex items-center justify-center hover:bg-system-main shadow-sm border border-system-border">
                <svg class="w-4 h-4 text-system-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
            </button>
        </div>
        <div class="p-6 overflow-y-auto max-h-[60vh]">
            <div class="mb-6">
                <p class="text-sm text-system-muted">Услуга:</p>
                <p class="font-bold text-system-text">${svc ? svc.name : ''}</p>
            </div>
            ${history.length === 0 ? '<p class="text-center text-system-muted py-4">История пуста</p>' : `
            <div class="space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-system-border before:to-transparent">
                ${history.slice().reverse().map((h, i) => `
                    <div class="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                        <div class="flex items-center justify-center w-3 h-3 rounded-full border-2 border-white bg-slate-300 group-[.is-active]:bg-primary-500 shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 ml-[1.125rem] md:ml-0 z-10 shadow"></div>
                        <div class="w-[calc(100%-3rem)] md:w-[calc(50%-1.5rem)] p-3 rounded-xl border border-slate-200 bg-system-surface shadow-sm">
                            <div class="flex items-center justify-between mb-1">
                                <div class="font-bold text-slate-900 text-xs">${h.type === 'time' ? '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6l4 2"/></svg> Время' : (h.type === 'price' ? '<svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path stroke-linecap="round" stroke-linejoin="round" d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 18V6"/></svg> Цена' : 'Изменение')}</div>
                                <time class="text-[10px] text-primary-500 font-medium">${h.date}</time>
                            </div>
                            <div class="text-slate-500 text-xs mt-1">
                                ${h.oldValue !== undefined ? `
                                    <span class="line-through opacity-70">${h.type === 'time' ? window.getDurationText(h.oldValue) : formatPrice(h.oldValue)}</span> &rarr;
                                ` : ''}
                                <strong class="text-slate-900">${h.type === 'time' ? window.getDurationText(h.newValue) : formatPrice(h.newValue || h.price)}</strong>
                            </div>
                        </div>
                    </div>
                `).join('')}
            </div>
            `}
        </div>
    </div>
</div>`;
}

window.renderPriceHistoryModal = renderPriceHistoryModal;


export function renderBecomeMasterModal() {
    return `
    <div class="fixed inset-0 z-[100] flex items-center justify-center modal-overlay" onclick="state.showBecomeMasterModal=false; render()">
        <div class="bg-system-surface w-full max-w-md rounded-3xl p-6 animate-slide-up" onclick="event.stopPropagation()">
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-xl font-bold text-system-text">Стать мастером</h2>
                <button onclick="state.showBecomeMasterModal=false; render()" class="text-system-muted hover:bg-system-main rounded-full w-8 h-8 flex items-center justify-center">✕</button>
            </div>
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">Специальность *</label>
                    <input type="text" id="bm-specialty" placeholder="Например: Стилист-колорист" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bmSpecialty || ''}" oninput="state.bmSpecialty=this.value">
                </div>
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">Опыт работы (лет)</label>
                    <input type="number" id="bm-experience" placeholder="5" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bmExperience || ''}" oninput="state.bmExperience=this.value">
                </div>
                ${state.bmError ? `<p class="text-red-500 text-sm font-medium">${state.bmError}</p>` : ''}
                <button onclick="submitBecomeMaster()" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm">Создать профиль мастера</button>
            </div>
        </div>
    </div>`;
}

window.renderBecomeMasterModal = renderBecomeMasterModal;

export function submitBecomeMaster() {
    const specialty = (state.bmSpecialty || '').trim();
    if (!specialty) {
        state.bmError = 'Введите специальность';
        render();
        return;
    }
    
    // Add master to state
    const newMasterId = state.masters.length + 1;
    const newMaster = {
        id: newMasterId, 
        name: state.currentUser.name || 'Новый мастер', 
        specialty: specialty,
        experience: parseInt(state.bmExperience) || 0,
        rating: 0, reviews: 0, priceLevel: 2,
        avatar: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><circle cx="40" cy="40" r="40" fill="#fce7f3"/><circle cx="40" cy="32" r="14" fill="#f9a8d4"/><ellipse cx="40" cy="65" rx="22" ry="18" fill="#f9a8d4"/></svg>'),
        categories: [], salonId: null, worksInSalon: false,
        services: [], available: true, userId: state.currentUser.id,
        about: ''
    };
    state.masters.push(newMaster);
    
    // Update user
    state.currentUser.masterId = newMasterId;
    state.currentUser.role = 'master'; // Automatically switch to master role
    
    // Clean up
    state.showBecomeMasterModal = false;
    state.bmError = '';
    state.bmSpecialty = '';
    state.bmExperience = '';
    
    window.showToast('Профиль мастера создан!');
    window.navigate('schedule');
    render();
}

window.submitBecomeMaster = submitBecomeMaster;

export function renderBecomeSalonModal() {
    return `
    <div class="fixed inset-0 z-[100] flex items-center justify-center p-4 modal-overlay overflow-y-auto" onclick="state.showBecomeSalonModal=false; render()">
        <div class="bg-system-surface w-full max-w-md rounded-3xl p-6 animate-slide-up my-auto shadow-2xl" onclick="event.stopPropagation()">
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-xl font-bold text-system-text">Регистрация салона</h2>
                <button onclick="state.showBecomeSalonModal=false; render()" class="text-system-muted hover:bg-system-main rounded-full w-8 h-8 flex items-center justify-center">✕</button>
            </div>
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">Форма собственности (ИП, ОсОО) *</label>
                    <input type="text" placeholder="Например: ОсОО 'Аура'" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bsOrgType || ''}" oninput="state.bsOrgType=this.value">
                </div>
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">ИНН *</label>
                    <input type="text" placeholder="14-значный ИНН" maxlength="14" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bsInn || ''}" oninput="state.bsInn=this.value.replace(/[^0-9]/g, '')">
                </div>
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">Название салона *</label>
                    <input type="text" placeholder="Suluu Luxe" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bsName || ''}" oninput="state.bsName=this.value">
                </div>
                <div>
                    <label class="block text-sm font-medium text-system-text mb-1.5">Адрес *</label>
                    <input type="text" placeholder="ул. Токтогула, 125" class="auth-input w-full px-4 py-3 rounded-xl border border-system-border outline-none text-sm bg-system-surface" value="${state.bsAddress || ''}" oninput="state.bsAddress=this.value">
                </div>
                ${state.bsError ? `<p class="text-red-500 text-sm font-medium">${state.bsError}</p>` : ''}
                <button onclick="submitBecomeSalon()" class="w-full btn-primary py-3.5 rounded-2xl text-white font-semibold text-sm mt-2">Открыть салон</button>
            </div>
        </div>
    </div>`;
}

window.renderBecomeSalonModal = renderBecomeSalonModal;

export function submitBecomeSalon() {
    const org = (state.bsOrgType || '').trim();
    const inn = (state.bsInn || '').trim();
    const name = (state.bsName || '').trim();
    const address = (state.bsAddress || '').trim();

    if (!org) { state.bsError = 'Введите форму собственности'; render(); return; }
    if (inn.length !== 14) { state.bsError = 'ИНН должен состоять из 14 цифр'; render(); return; }
    if (!name) { state.bsError = 'Введите название салона'; render(); return; }
    if (!address) { state.bsError = 'Введите адрес салона'; render(); return; }

    const newSalonId = state.salons.length + 1;
    const newSalon = {
        id: newSalonId, 
        name: name, 
        address: address,
        inn: inn,
        orgType: org,
        city: 'Бишкек', metro: '', rating: 0, reviews: 0, priceLevel: 2,
        image: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200"><rect width="400" height="200" fill="#fce7f3"/><text x="200" y="100" text-anchor="middle" font-size="48"><svg class="w-5 h-5 inline-block" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 6h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 10h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 14h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 18h4"/></svg></text></svg>'),
        categories: [], masters: 0, openTime: '9:00', closeTime: '21:00',
        features: [], verified: false, ownerId: state.currentUser.id
    };
    state.salons.push(newSalon);
    
    // Add staff
    state.salonStaff.push({
        id: 'ST' + Date.now(),
        userId: state.currentUser.id,
        salonId: newSalonId,
        baseRole: 'owner',
        permissions: ['view_all_schedules', 'manage_bookings', 'view_applications', 'process_applications', 'manage_staff_permissions', 'manage_services', 'manage_salon_settings'],
        status: 'active'
    });

    state.salonSubscriptions.push({
        salonId: newSalonId,
        planId: 'basic',
        status: 'active',
        expiresAt: new Date(Date.now() + 7*24*60*60*1000).toISOString()
    });

    state.currentUser.salonId = newSalonId;
    state.currentUser.role = 'salon';

    state.showBecomeSalonModal = false;
    state.bsError = '';
    state.bsOrgType = '';
    state.bsInn = '';
    state.bsName = '';
    state.bsAddress = '';

    window.showToast('Салон успешно зарегистрирован!');
    window.navigate('dashboard');
    render();
}

window.submitBecomeSalon = submitBecomeSalon;
