// This file is auto-generated by refactor.js

import { render } from '../core/engine.js';
import { handleLogout } from '../features/auth/actions.js';
import { navigate } from '../core/router.js';
import { state, salons, masters, users, checkPermission, getSalonRole } from '../state.js';
import { getUserBookings, ThemeManager } from '../utils.js';

export function renderThemeSwitcher() {
    const currentTheme = document.documentElement.getAttribute('data-theme') || 'beauty';
    
    const themeIcons = {
        beauty: '<svg class="w-5 h-5 inline-block text-primary-500" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 22c-4.97-1.63-8-6-8-12a8 8 0 0 1 16 0c0 6-3.03 10.37-8 12Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 22V10"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 10a4 4 0 1 1 0-8 4 4 0 0 1 0 8Z"/></svg>',
        barber: '<svg class="w-5 h-5 inline-block text-blue-500" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/><path d="M12 14v7"/></svg>',
        hair: '<svg class="w-5 h-5 inline-block text-purple-500" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 12v.01"/></svg>',
        eco: '<svg class="w-5 h-5 inline-block text-green-500" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></svg>',
        medical: '<svg class="w-5 h-5 inline-block text-cyan-500" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7Z"/></svg>',
        graphite: '<svg class="w-5 h-5 inline-block text-slate-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" /></svg>'
    };

    const themeNames = {
        beauty: 'Бьюти',
        barber: 'Барбер',
        hair: 'Волосы',
        eco: 'Эко',
        medical: 'Мед',
        graphite: 'Графит'
    };

    const dropdown = state.showThemeDropdown ? `
        <div class="fixed inset-0 z-[90]" onclick="event.stopPropagation(); state.showThemeDropdown = false; window.render()"></div>
        <div class="absolute top-full mt-2 right-0 bg-system-surface border border-system-border rounded-xl shadow-xl p-2 z-[100] flex flex-row gap-1 animate-fade-in"
             onclick="event.stopPropagation()">
            ${Object.keys(themeIcons).map(theme => `
                <button class="flex items-center justify-center p-2 rounded-lg hover:bg-system-main transition-colors ${currentTheme === theme ? 'bg-system-main text-primary-600' : 'text-system-text'}"
                        onclick="ThemeManager.setTheme('${theme}'); state.showThemeDropdown = false; window.render()">
                    <span>${themeIcons[theme]}</span>
                </button>
            `).join('')}
        </div>
    ` : '';

    return `
        <div class="relative b-theme__switcher" onclick="state.showThemeDropdown = !state.showThemeDropdown; window.render()">
            <div class="w-9 h-9 rounded-full bg-system-main border border-system-border hover:bg-system-border flex items-center justify-center cursor-pointer transition-colors" title="Сменить тему">
                <span class="text-base sm:text-lg">${themeIcons[currentTheme]}</span>
            </div>
            ${dropdown}
        </div>
    `;
}

window.renderThemeSwitcher = renderThemeSwitcher;

export function renderToast() {
    return `<div class="toast bg-system-text text-system-surface px-6 py-3 rounded-2xl shadow-2xl flex items-center gap-3 animate-slide-up"><span class="text-green-400">✓</span><span class="text-sm font-medium">${state.toast}</span></div>`;
}

window.renderToast = renderToast;

export function renderClientMobileNav() {
    const bookingsClick = "navigate('bookings')";
    const profileClick = state.currentUser ? "state.showProfileEdit=true;render()" : "state.showAuthPage=true;render()";
    
    const profileIcon = `<svg class="w-6 h-6 mb-1" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>`;
    const profileLabel = state.currentUser ? "Профиль" : "Войти";

    return `
    <div class="fixed bottom-4 left-4 right-4 z-[90] md:hidden">
        <nav class="island-mobile-nav flex justify-around items-center px-2 py-3">
            <a href="#" onclick="navigate('home')" class="flex flex-col items-center w-1/4 transition-colors ${state.currentPage === 'home' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                <svg class="w-6 h-6 mb-1" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg>
                <span class="text-[10px] font-bold">Главная</span>
            </a>
            <a href="#" onclick="navigate('salons')" class="flex flex-col items-center w-1/4 transition-colors ${state.currentPage === 'salons' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                <svg class="w-6 h-6 mb-1" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"/></svg>
                <span class="text-[10px] font-bold">Салоны</span>
            </a>
            <a href="#" onclick="${bookingsClick}" class="flex flex-col items-center w-1/4 relative transition-colors ${state.currentPage === 'bookings' ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                <svg class="w-6 h-6 mb-1" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                <span class="text-[10px] font-bold">Записи</span>
                ${getUserBookings().filter(b => b.status === 'pending').length > 0 ? `<span class="absolute top-0 right-3 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-system-surface shadow-sm"></span>` : ''}
            </a>
            <a href="#" onclick="${profileClick}" class="flex flex-col items-center w-1/4 transition-colors text-system-muted hover:text-system-text">
                ${profileIcon}
                <span class="text-[10px] font-bold">${profileLabel}</span>
            </a>
        </nav>
    </div>`;
}

window.renderClientMobileNav = renderClientMobileNav;

export function renderSalonMobileNav() {
    const salon = salons.find(s => s.id === (state.currentUser && state.currentUser.salonId));
    if (!salon) return '';

    const tabs = [
        { id: 'dashboard', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 3v18h18"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 17V9"/><path stroke-linecap="round" stroke-linejoin="round" d="M13 17V5"/><path stroke-linecap="round" stroke-linejoin="round" d="M8 17v-3"/></svg>', label: 'Дашборд', show: checkPermission(state.currentUser.id, salon.id, 'dashboard:view') },
        { id: 'cash_shift', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/></svg>', label: 'Кассовая смена', show: ['owner', 'manager', 'receptionist'].includes(getSalonRole(state.currentUser.id, salon.id) || 'owner') },
        { id: 'bookings', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg>', label: 'Записи', show: checkPermission(state.currentUser.id, salon.id, 'bookings:view') },
        { id: 'masters_catalog', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line stroke-linecap="round" stroke-linejoin="round" x1="20" x2="8.12" y1="4" y2="15.88"/><line stroke-linecap="round" stroke-linejoin="round" x1="14.47" x2="14.48" y1="14.48" y2="14.48"/><line stroke-linecap="round" stroke-linejoin="round" x1="20" x2="8.12" y1="20" y2="8.12"/></svg>', label: 'Мастера', show: true },
        { id: 'staff', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path stroke-linecap="round" stroke-linejoin="round" d="M22 21v-2a4 4 0 0 0-3-3.87"/><path stroke-linecap="round" stroke-linejoin="round" d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>', label: 'Штат', show: checkPermission(state.currentUser.id, salon.id, 'staff:view') },
        { id: 'services', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7h-3a2 2 0 0 1-2-2V2"/><path stroke-linecap="round" stroke-linejoin="round" d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2-2Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 15h6"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 18h6"/></svg>', label: 'Услуги', show: checkPermission(state.currentUser.id, salon.id, 'services:view') },
        { id: 'subscription', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 3h12l4 6-10 13L2 9Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M11 3 8 9l4 13"/><path stroke-linecap="round" stroke-linejoin="round" d="M13 3l3 6-4 13"/></svg>', label: 'Подписка', show: checkPermission(state.currentUser.id, salon.id, 'subscription:view') },
        { id: 'profile', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>', label: 'Профиль', show: checkPermission(state.currentUser.id, salon.id, 'profile:view') }
    ];

    const visibleTabs = tabs.filter(t => t.show);
    const mainTabs = visibleTabs.slice(0, 4);
    const menuTabs = visibleTabs.slice(4);

    const menuIcon = `<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="12" y2="12"/><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="6" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="18" y2="18"/></svg>`;

    return `
    <div class="fixed bottom-4 left-4 right-4 z-[90] md:hidden">
        ${state.showSalonMobileMenu ? `
        <div class="absolute bottom-full mb-2 left-0 right-0 bg-system-surface/95 backdrop-blur-md border border-system-border rounded-2xl shadow-xl p-2 flex flex-col gap-1 animate-fade-in">
            ${menuTabs.map(tab => `
                <a href="#" onclick="state.salonTab='${tab.id}'; state.showSalonMobileMenu=false; render()" class="flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${state.salonTab === tab.id ? 'bg-system-main text-primary-600 font-bold' : 'text-system-muted hover:bg-system-main hover:text-system-text'}">
                    <span>${tab.icon}</span>
                    <span>${tab.label}</span>
                </a>
            `).join('')}
        </div>
        ` : ''}
        <nav class="island flex justify-around items-center px-2 py-3 bg-system-surface/80 backdrop-blur-xl border border-system-border/50 shadow-2xl rounded-2xl">
            ${mainTabs.map(tab => `
                <a href="#" onclick="state.salonTab='${tab.id}'; state.showSalonMobileMenu=false; render()" class="flex flex-col items-center w-1/5 py-1 ${state.salonTab === tab.id ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                    <div class="mb-1 ${state.salonTab === tab.id ? 'scale-110' : ''} transition-transform">${tab.icon}</div>
                    <span class="text-[10px] font-bold truncate w-full text-center">${tab.label}</span>
                </a>
            `).join('')}
            ${menuTabs.length > 0 ? `
                <a href="#" onclick="state.showSalonMobileMenu=!state.showSalonMobileMenu; render()" class="flex flex-col items-center w-1/5 py-1 ${state.showSalonMobileMenu ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                    <div class="mb-1 ${state.showSalonMobileMenu ? 'scale-110' : ''} transition-transform">${menuIcon}</div>
                    <span class="text-[10px] font-bold">Меню</span>
                </a>
            ` : ''}
        </nav>
    </div>
    `;
}

window.renderSalonMobileNav = renderSalonMobileNav;

export function renderMasterMobileNav() {
    const tabs = [
        { id: 'bookings', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18"/><path stroke-linecap="round" stroke-linejoin="round" d="M12 7v5l3 3"/></svg>', label: 'Записи' },
        { id: 'my_salons', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M6 12H4a2 2 0 0 0-2-2V6a2 2 0 0 0 2 2h2"/><path stroke-linecap="round" stroke-linejoin="round" d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 6h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 10h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 14h4"/><path stroke-linecap="round" stroke-linejoin="round" d="M10 18h4"/></svg>', label: 'Салоны' },
        { id: 'services', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7h-3a2 2 0 0 1-2-2V2"/><path stroke-linecap="round" stroke-linejoin="round" d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2-2Z"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 15h6"/><path stroke-linecap="round" stroke-linejoin="round" d="M3 18h6"/></svg>', label: 'Услуги' },
        { id: 'profile', icon: '<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>', label: 'Профиль' },
    ];
    
    const mainTabs = tabs.slice(0, 4);
    const menuTabs = tabs.slice(4);
    const menuIcon = `<svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="12" y2="12"/><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="6" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="4" x2="20" y1="18" y2="18"/></svg>`;

    return `
    <div class="fixed bottom-4 left-4 right-4 z-[90] md:hidden">
        ${state.showMasterMobileMenu ? `
        <div class="absolute bottom-full mb-2 left-0 right-0 bg-system-surface/95 backdrop-blur-md border border-system-border rounded-2xl shadow-xl p-2 flex flex-col gap-1 animate-fade-in">
            ${menuTabs.map(tab => `
                <a href="#" onclick="state.masterTab='${tab.id}'; state.showMasterMobileMenu=false; render()" class="flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${state.masterTab === tab.id ? 'bg-system-main text-primary-600 font-bold' : 'text-system-muted hover:bg-system-main hover:text-system-text'}">
                    <span>${tab.icon}</span>
                    <span>${tab.label}</span>
                </a>
            `).join('')}
        </div>
        ` : ''}
        <nav class="island flex justify-around items-center px-2 py-3 bg-system-surface/80 backdrop-blur-xl border border-system-border/50 shadow-2xl rounded-2xl">
            ${mainTabs.map(tab => `
                <a href="#" onclick="state.masterTab='${tab.id}'; state.showMasterMobileMenu=false; render()" class="flex flex-col items-center w-1/5 py-1 ${state.masterTab === tab.id ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                    <div class="mb-1 ${state.masterTab === tab.id ? 'scale-110' : ''} transition-transform">${tab.icon}</div>
                    <span class="text-[10px] font-bold truncate w-full text-center">${tab.label}</span>
                </a>
            `).join('')}
            ${menuTabs.length > 0 ? `
                <a href="#" onclick="state.showMasterMobileMenu=!state.showMasterMobileMenu; render()" class="flex flex-col items-center w-1/5 py-1 ${state.showMasterMobileMenu ? 'text-primary-600' : 'text-system-muted hover:text-system-text'}">
                    <div class="mb-1 ${state.showMasterMobileMenu ? 'scale-110' : ''} transition-transform">${menuIcon}</div>
                    <span class="text-[10px] font-bold">Меню</span>
                </a>
            ` : ''}
        </nav>
    </div>`;
}

window.renderMasterMobileNav = renderMasterMobileNav;

export function renderClientFooter() {
    return `
    <footer class="pb-12 px-4 sm:px-6"><div class="island max-w-7xl mx-auto text-system-muted py-12">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
        <div>
            <div class="flex items-center gap-2 mb-4">
                <div class="w-8 h-8 rounded-lg bg-primary-500 flex items-center justify-center"><span class="text-white text-sm">✦</span></div>
                <span class="text-lg font-bold text-system-text">Suluu</span>
            </div>
            <p class="text-sm leading-relaxed">Маркетплейс beauty-услуг в Кыргызстане. Находите лучших мастеров и записывайтесь онлайн.</p>
        </div>
        <div>
            <h4 class="text-system-text font-semibold mb-3">Клиентам</h4>
            <ul class="space-y-2 text-sm">
                <li><a href="#" onclick="navigate('services')" class="hover:text-primary-600 transition-colors">Услуги</a></li>
                <li><a href="#" onclick="navigate('salons')" class="hover:text-primary-600 transition-colors">Салоны</a></li>
                <li><a href="#" onclick="navigate('masters')" class="hover:text-primary-600 transition-colors">Мастера</a></li>
            </ul>
        </div>
        <div>
            <h4 class="text-system-text font-semibold mb-3">Мастерам</h4>
            <ul class="space-y-2 text-sm">
                <li><a href="#" onclick="handleLogout()" class="hover:text-primary-600 transition-colors">Стать мастером</a></li>
                <li><a href="#" onclick="handleLogout()" class="hover:text-primary-600 transition-colors">Панель управления</a></li>
            </ul>
        </div>
        <div>
            <h4 class="text-system-text font-semibold mb-3">Партнёрам</h4>
            <ul class="space-y-2 text-sm">
                <li><a href="#" onclick="handleLogout()" class="hover:text-primary-600 transition-colors">Подключить салон</a></li>
                <li><a href="#" onclick="handleLogout()" class="hover:text-primary-600 transition-colors">Для корпоративных клиентов</a></li>
            </ul>
        </div>
    </div>
    <div class="border-t border-system-border pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm">
        <p>© 2024 Suluu. Все права защищены.</p>
    </div>
</div></footer>`;
}

window.renderClientFooter = renderClientFooter;

export function renderUserDropdown() {
    const userName = (state.currentUser && state.currentUser.name) || (state.currentUser && state.currentUser.phone);
    const roleLabels = { client: 'Клиент', master: 'Мастер', salon: 'Салон', superadmin: 'Админ', admin: 'Админ' };
    return `
    <div class="absolute right-0 top-full mt-2 w-64 bg-system-surface rounded-2xl shadow-xl border border-system-border z-50 animate-scale-in">
<div class="p-4 border-b border-system-border">
    <p class="font-semibold text-system-text text-sm">${userName}</p>
    <p class="text-xs text-system-muted">${state.currentUser?.phone}</p>
    <span class="badge bg-primary-100 text-primary-600 mt-1">${roleLabels[state.currentUser?.role]}</span>
</div>
<div class="p-2">
    <a href="#" onclick="state.showProfileEdit=true;state.mobileMenu=false;render()" class="flex items-center gap-3 px-3 py-2 rounded-xl text-sm text-system-text hover:bg-system-main transition-colors">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
        Мой профиль
    </a>
    <a href="#" onclick="navigate('bookings');state.mobileMenu=false" class="flex items-center gap-3 px-3 py-2 rounded-xl text-sm text-system-text hover:bg-system-main transition-colors">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line stroke-linecap="round" stroke-linejoin="round" x1="16" x2="16" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="8" x2="8" y1="2" y2="6"/><line stroke-linecap="round" stroke-linejoin="round" x1="3" x2="21" y1="10" y2="10"/></svg>
        Мои записи
    </a>
    <div class="border-t border-system-border my-1"></div>
    <a href="#" onclick="handleLogout()" class="flex items-center gap-3 px-3 py-2 rounded-xl text-sm text-red-500 hover:bg-red-50 transition-colors">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline stroke-linecap="round" stroke-linejoin="round" points="16 17 21 12 16 7"/><line stroke-linecap="round" stroke-linejoin="round" x1="21" x2="9" y1="12" y2="12"/></svg>
        Выйти
    </a>
</div>
    </div>`;
}

window.renderUserDropdown = renderUserDropdown;

export function toggleMobileMenu() {
    state.mobileMenu = !state.mobileMenu;
    render();
}

window.toggleMobileMenu = toggleMobileMenu;
